// Code generated by applegen; DO NOT EDIT.

package arkit

import (
	"unsafe"

	"github.com/tmc/swiftui"
)

// withCString calls fn with a null-terminated C string pointer.
func withCString(s string, fn func(*byte)) {
	b := append([]byte(s), 0)
	fn(&b[0])
}

// gostring copies a null-terminated C string to a Go string.
func gostring(p *byte) string {
	if p == nil {
		return ""
	}
	var buf []byte
	for ptr := p; *ptr != 0; ptr = (*byte)(unsafe.Add(unsafe.Pointer(ptr), 1)) {
		buf = append(buf, *ptr)
	}
	return string(buf)
}

// gostringFree copies a C string and frees it.
func gostringFree(p *byte) string {
	if p == nil {
		return ""
	}
	s := gostring(p)
	_ARS_FreeString(p)
	return s
}

// NewARView creates an ARView wrapped as a SwiftUI view.
func NewARView() swiftui.View {
	return swiftui.ViewFromPointer(_ARS_ARViewCreate())
}
