// Code generated by applegen; DO NOT EDIT.

import LocalAuthentication
import SwiftUI


// MARK: - NewLocalAuthView

@_cdecl("LAS_LocalAuthViewCreate")
@MainActor
public func LAS_LocalAuthViewCreate(_ reason: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let r = String(cString: reason)
    let context = LAContext()
    let view = AnyView(
        Button(r) {
            context.evaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, localizedReason: r) { _, _ in }
        }
    )
    return Unmanaged.passRetained(Box(view)).toOpaque()
}
