// Code generated by applegen; DO NOT EDIT.

import Foundation
import LocalAuthentication
import SwiftUI

// Box wraps a value type so it can be stored in Unmanaged.
final class Box<T>: @unchecked Sendable {
    var value: T
    init(_ value: T) { self.value = value }
}

@_cdecl("LAS_Retain")
public func LAS_Retain(_ ptr: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    _ = Unmanaged<AnyObject>.fromOpaque(ptr).retain()
    return ptr
}

@_cdecl("LAS_Release")
public func LAS_Release(_ ptr: UnsafeMutableRawPointer) {
    Unmanaged<AnyObject>.fromOpaque(ptr).release()
}

@_cdecl("LAS_FreeString")
public func LAS_FreeString(_ ptr: UnsafeMutablePointer<CChar>) {
    ptr.deallocate()
}
