// Code generated by applegen; DO NOT EDIT.

import SwiftUI
import AppKit


class SUIAppDelegate: NSObject, NSApplicationDelegate {
    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        return true
    }
}

nonisolated(unsafe) var _appDelegate: SUIAppDelegate?
nonisolated(unsafe) var _menuBarDelegate: SUIMenuBarAppDelegate?
nonisolated(unsafe) var _statusItem: NSStatusItem?
nonisolated(unsafe) var _popover: NSPopover?

// suiOnMainSync runs body on the main thread, returning its result. The app
// run functions below always call it, so it is defined here (the default
// surface) rather than in the converged-surface chunk to keep a default regen
// self-contained and compilable.
@inline(__always)
func suiOnMainSync<T>(_ body: () -> T) -> T {
    if Thread.isMainThread {
        return body()
    }
    return DispatchQueue.main.sync(execute: body)
}

class SUIMenuBarAppDelegate: NSObject, NSApplicationDelegate {
    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        return false
    }

    @MainActor @objc func togglePopover(_ sender: AnyObject?) {
        guard let popover = _popover, let button = _statusItem?.button else { return }
        if popover.isShown {
            popover.performClose(sender)
        } else {
            // Activate the app before showing so the popover's window can
            // become key; otherwise (accessory activation policy + transient
            // popover) the window never becomes key and SwiftUI swallows the
            // Button mouse-up, so taps render but never fire into Go.
            NSApp.activate(ignoringOtherApps: true)
            // .minY anchors the popover below the status-bar button, which is
            // correct for the top menu bar.
            popover.show(relativeTo: button.bounds, of: button, preferredEdge: .minY)
            popover.contentViewController?.view.window?.makeKey()
        }
    }

    @MainActor func openPopoverOnLaunch() {
        guard let popover = _popover, let button = _statusItem?.button else { return }
        if !popover.isShown {
            NSApp.activate(ignoringOtherApps: true)
            popover.show(relativeTo: button.bounds, of: button, preferredEdge: .minY)
            popover.contentViewController?.view.window?.makeKey()
        }
    }
}

// suiBuildWindow constructs the standard borrowed-runner NSWindow for a hosted
// SwiftUI root view and orders it front. Shared by SUIRunApp (window construction
// lives in one place).
@MainActor
func suiBuildWindow(_ view: AnyView, title: String, width: Double, height: Double) {
    let sized = AnyView(view.frame(minWidth: width, minHeight: height))
    let hc = NSHostingController(rootView: sized)
    hc.sizingOptions = []

    let window = NSWindow(
        contentRect: NSRect(x: 0, y: 0, width: width, height: height),
        styleMask: [.titled, .closable, .resizable, .miniaturizable],
        backing: .buffered, defer: false
    )
    window.title = title
    window.contentViewController = hc
    window.setContentSize(NSSize(width: width, height: height))
    window.minSize = NSSize(width: 300, height: 200)
    window.center()
    window.makeKeyAndOrderFront(nil)
}

// suiBuildStatusItem installs the menu bar (status bar) item wired to toggle the
// popover. If content is nil the status item has no popover (a bare menu bar
// item; an NSMenu can be attached later).
@MainActor
func suiBuildStatusItem(delegate: SUIMenuBarAppDelegate, label: String, systemImage: String,
                        content: AnyView?, width: Double, height: Double, openOnLaunch: Bool) {
    let item = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    if let img = NSImage(systemSymbolName: systemImage, accessibilityDescription: label) {
        item.button?.image = img
    }
    item.button?.title = " " + label
    item.button?.target = delegate
    item.button?.action = #selector(SUIMenuBarAppDelegate.togglePopover(_:))
    _statusItem = item

    guard let content = content else { return }

    let popover = NSPopover()
    popover.contentSize = NSSize(width: width, height: height)
    popover.behavior = .transient
    let hc = NSHostingController(rootView: AnyView(content.frame(minWidth: width, minHeight: height)))
    popover.contentViewController = hc
    _popover = popover

    if openOnLaunch {
        DispatchQueue.main.async {
            delegate.openPopoverOnLaunch()
        }
    }
}

// SUIRunApp is the unified application runner. It presents an optional window
// (rootView != nil), an optional menu bar item (hasMenuBar != 0; with an
// optional popover when menuContent != nil), under an activation policy
// (0=auto, 1=regular, 2=accessory, 3=prohibited). The older SUIRun,
// SUIRunMenuBar, SUIRunMenuBarEx, and SUIRunWithMenuBar entry points are thin
// shims over this function, kept for ABI compatibility.
@_cdecl("SUIRunApp")
@MainActor
public func SUIRunApp(_ policy: Int32,
                       _ rootView: UnsafeMutableRawPointer?,
                       _ title: UnsafePointer<CChar>,
                       _ width: Double, _ height: Double,
                       _ hasMenuBar: Int32,
                       _ menuLabel: UnsafePointer<CChar>,
                       _ menuSystemImage: UnsafePointer<CChar>,
                       _ menuContent: UnsafeMutableRawPointer?,
                       _ menuWidth: Double, _ menuHeight: Double,
                       _ openOnLaunch: Int32) {
    suiOnMainSync {
        let app = NSApplication.shared

        let hasWindow = rootView != nil
        let wantsMenuBar = hasMenuBar != 0

        // Resolve the activation policy. 0 = auto: a window implies .regular, a
        // menu-bar-only app implies .accessory.
        let resolved: NSApplication.ActivationPolicy
        switch policy {
        case 1: resolved = .regular
        case 2: resolved = .accessory
        case 3: resolved = .prohibited
        default: resolved = hasWindow ? .regular : .accessory
        }
        app.setActivationPolicy(resolved)

        // A menu-bar app must keep running after its (absent) windows close; a
        // windowed app should terminate with its last window. Pick the delegate
        // by which surfaces are present.
        if wantsMenuBar {
            let delegate = SUIMenuBarAppDelegate()
            _menuBarDelegate = delegate
            app.delegate = delegate
        } else {
            let delegate = SUIAppDelegate()
            _appDelegate = delegate
            app.delegate = delegate
        }

        if let rootView = rootView {
            let view = Unmanaged<Box<AnyView>>.fromOpaque(rootView).takeUnretainedValue().value
            suiBuildWindow(view, title: String(cString: title), width: width, height: height)
        }

        if wantsMenuBar, let delegate = _menuBarDelegate {
            var content: AnyView?
            if let menuContent = menuContent {
                content = Unmanaged<Box<AnyView>>.fromOpaque(menuContent).takeUnretainedValue().value
            }
            suiBuildStatusItem(delegate: delegate,
                               label: String(cString: menuLabel),
                               systemImage: String(cString: menuSystemImage),
                               content: content,
                               width: menuWidth, height: menuHeight,
                               openOnLaunch: openOnLaunch != 0)
        }

        app.activate()
        app.run()
    }
}

@_cdecl("SUIRun")
@MainActor
public func SUIRun(_ rootView: UnsafeMutableRawPointer, _ title: UnsafePointer<CChar>,
                    _ width: Double, _ height: Double) {
    SUIRunApp(1, rootView, title, width, height, 0, title, title, nil, 0, 0, 0)
}

@_cdecl("SUIRunMenuBar")
@MainActor
public func SUIRunMenuBar(_ label: UnsafePointer<CChar>,
                           _ systemImage: UnsafePointer<CChar>,
                           _ content: UnsafeMutableRawPointer,
                           _ width: Double, _ height: Double) {
    SUIRunMenuBarEx(label, systemImage, content, width, height, 0)
}

@_cdecl("SUIRunMenuBarEx")
@MainActor
public func SUIRunMenuBarEx(_ label: UnsafePointer<CChar>,
                             _ systemImage: UnsafePointer<CChar>,
                             _ content: UnsafeMutableRawPointer,
                             _ width: Double, _ height: Double,
                             _ openOnLaunch: Int32) {
    SUIRunApp(2, nil, label, 0, 0, 1, label, systemImage, content, width, height, openOnLaunch)
}

@_cdecl("SUIRunWithMenuBar")
@MainActor
public func SUIRunWithMenuBar(_ rootView: UnsafeMutableRawPointer,
                               _ title: UnsafePointer<CChar>,
                               _ width: Double, _ height: Double,
                               _ menuLabel: UnsafePointer<CChar>,
                               _ menuSystemImage: UnsafePointer<CChar>,
                               _ menuContent: UnsafeMutableRawPointer,
                               _ menuWidth: Double, _ menuHeight: Double) {
    SUIRunApp(1, rootView, title, width, height, 1, menuLabel, menuSystemImage, menuContent, menuWidth, menuHeight, 0)
}

@_cdecl("SUIUpdateMenuBarLabel")
public func SUIUpdateMenuBarLabel(_ label: UnsafePointer<CChar>) {
	let str = String(cString: label)
    DispatchQueue.main.async {
        _statusItem?.button?.title = " " + str
    }
}

@_cdecl("SUIUpdateMenuBarLabelStyled")
public func SUIUpdateMenuBarLabelStyled(_ label: UnsafePointer<CChar>,
                                        _ monospacedDigits: Int32,
                                        _ animated: Int32) {
    let str = String(cString: label)
    DispatchQueue.main.async {
        guard let button = _statusItem?.button else { return }

        let applyLabel = {
            if monospacedDigits != 0 {
                let font = NSFont.monospacedDigitSystemFont(ofSize: NSFont.systemFontSize, weight: .regular)
                let attr = NSAttributedString(string: " " + str, attributes: [.font: font])
                button.attributedTitle = attr
            } else {
                button.attributedTitle = NSAttributedString(string: "")
                button.title = " " + str
            }
        }

        if animated != 0 {
            NSAnimationContext.runAnimationGroup({ context in
                context.duration = 0.08
                button.animator().alphaValue = 0.65
            })
            applyLabel()
            NSAnimationContext.runAnimationGroup({ context in
                context.duration = 0.12
                button.animator().alphaValue = 1.0
            })
        } else {
            applyLabel()
        }
    }
}

@_cdecl("SUIPlaySystemSound")
public func SUIPlaySystemSound(_ name: UnsafePointer<CChar>) {
    let soundName = String(cString: name)
    DispatchQueue.main.async {
        NSSound(named: NSSound.Name(soundName))?.play()
    }
}
