// Code generated by applegen; DO NOT EDIT.

import AppKit
import SwiftUI
@MainActor
private func snapshotPNG(
    view: AnyView,
    width: Double,
    height: Double,
    scale: Double
) -> Data? {
    let renderScale = scale > 0 ? scale : 1

    _ = NSApplication.shared

    let sized = AnyView(
        view.frame(
            minWidth: width,
            idealWidth: width,
            maxWidth: width,
            minHeight: height,
            idealHeight: height,
            maxHeight: height,
            alignment: .topLeading
        )
    )

    let renderer = ImageRenderer(content: sized)
    renderer.scale = renderScale
    guard let cgImage = renderer.cgImage else {
        return nil
    }
    return NSBitmapImageRep(cgImage: cgImage).representation(using: .png, properties: [:])
}

@_cdecl("SUIRenderPNG")
@MainActor
public func SUIRenderPNG(
    _ rootView: UnsafeMutableRawPointer,
    _ path: UnsafePointer<CChar>,
    _ width: Double,
    _ height: Double,
    _ scale: Double
) -> UnsafeMutablePointer<CChar>? {
    let view = Unmanaged<Box<AnyView>>.fromOpaque(rootView).takeUnretainedValue().value
    let outputPath = String(cString: path)
    let outputURL = URL(fileURLWithPath: outputPath)
    guard let png = snapshotPNG(view: view, width: width, height: height, scale: scale) else {
        return strdup("failed to encode png representation")
    }

    do {
        try png.write(to: outputURL, options: .atomic)
        return nil
    } catch {
        return strdup("write png: \(error.localizedDescription)")
    }
}
