// Code generated by github.com/tmc/appledocs/cmd/applegen; DO NOT EDIT.

import SwiftUI
import AppKit
import Foundation
import WebKit


@_cdecl("SUIText")
public func SUIText(_ s: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let text = String(cString: s)
    let view = AnyView(Text(text))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIImage")
public func SUIImage(_ systemName: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let name = String(cString: systemName)
    let view = AnyView(Image(systemName: name))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIVStack")
public func SUIVStack(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let stack = AnyView(VStack {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(stack)).toOpaque()
}

@_cdecl("SUIVStackSpaced")
public func SUIVStackSpaced(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32, _ spacing: Double) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let stack = AnyView(VStack(spacing: spacing) {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(stack)).toOpaque()
}

@_cdecl("SUIHStack")
public func SUIHStack(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let stack = AnyView(HStack {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(stack)).toOpaque()
}

@_cdecl("SUIHStackSpaced")
public func SUIHStackSpaced(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32, _ spacing: Double) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let stack = AnyView(HStack(spacing: spacing) {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(stack)).toOpaque()
}

@_cdecl("SUIButton")
public func SUIButton(_ label: UnsafePointer<CChar>, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let title = String(cString: label)
    let id = callbackID
    let view = AnyView(Button(title) {
        _SUIButtonCallback?(id)
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIButtonWithImage")
public func SUIButtonWithImage(_ systemName: UnsafePointer<CChar>, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let name = String(cString: systemName)
    let id = callbackID
    let view = AnyView(Button(action: {
        _SUIButtonCallback?(id)
    }) {
        Image(systemName: name)
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIButtonWithLabel")
public func SUIButtonWithLabel(_ text: UnsafePointer<CChar>, _ systemImage: UnsafePointer<CChar>, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let t = String(cString: text)
    let img = String(cString: systemImage)
    let id = callbackID
    let view = AnyView(Button(action: {
        _SUIButtonCallback?(id)
    }) {
        Label(t, systemImage: img)
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUISpacer")
public func SUISpacer() -> UnsafeMutableRawPointer {
    let view = AnyView(Spacer())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIDivider")
public func SUIDivider() -> UnsafeMutableRawPointer {
    let view = AnyView(Divider())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUILabel")
public func SUILabel(_ text: UnsafePointer<CChar>, _ systemImage: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let t = String(cString: text)
    let img = String(cString: systemImage)
    let view = AnyView(Label(t, systemImage: img))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIProgressViewSpinning")
public func SUIProgressViewSpinning() -> UnsafeMutableRawPointer {
    let view = AnyView(ProgressView())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIProgressViewLinear")
public func SUIProgressViewLinear(_ value: Double, _ total: Double) -> UnsafeMutableRawPointer {
    let view = AnyView(ProgressView(value: value, total: total))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIGroupBox")
public func SUIGroupBox(_ labelPtr: UnsafePointer<CChar>, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let label = String(cString: labelPtr)
    let content = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(GroupBox(label) { content })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIEmptyView")
public func SUIEmptyView() -> UnsafeMutableRawPointer {
    let view = AnyView(EmptyView())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIScrollView")
public func SUIScrollView(_ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let content = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(ScrollView { content })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Additional containers

@_cdecl("SUIZStack")
public func SUIZStack(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let stack = AnyView(ZStack {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(stack)).toOpaque()
}

@_cdecl("SUILazyVStack")
public func SUILazyVStack(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let stack = AnyView(LazyVStack {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(stack)).toOpaque()
}

@_cdecl("SUILazyHStack")
public func SUILazyHStack(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let stack = AnyView(LazyHStack {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(stack)).toOpaque()
}

@_cdecl("SUIList")
@MainActor
public func SUIList(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let list = AnyView(List {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(list)).toOpaque()
}

@_cdecl("SUIForm")
public func SUIForm(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let form = AnyView(Form {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(form)).toOpaque()
}

@_cdecl("SUISection")
public func SUISection(_ headerPtr: UnsafePointer<CChar>, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let header = String(cString: headerPtr)
    let content = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(Section(header) { content })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUITabView")
public func SUITabView(_ children: UnsafePointer<UnsafeMutableRawPointer>, _ count: Int32) -> UnsafeMutableRawPointer {
    let views = (0..<Int(count)).map { i in
        Unmanaged<Box<AnyView>>.fromOpaque(children[i]).takeUnretainedValue().value
    }
    let tab = AnyView(TabView {
        ForEach(views.indices, id: \.self) { i in
            views[i]
        }
    })
    return Unmanaged.passRetained(Box(tab)).toOpaque()
}

@_cdecl("SUINavigationLink")
public func SUINavigationLink(_ labelPtr: UnsafePointer<CChar>, _ destRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let label = String(cString: labelPtr)
    let dest = Unmanaged<Box<AnyView>>.fromOpaque(destRef).takeUnretainedValue().value
    let view = AnyView(NavigationLink(label) { dest })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUINavigationStack")
@MainActor
public func SUINavigationStack(_ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let content = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(NavigationStack { content })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIMenu")
public func SUIMenu(_ labelPtr: UnsafePointer<CChar>, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let label = String(cString: labelPtr)
    let content = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(Menu(label) { content })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Shapes and display views

@_cdecl("SUIColor")
public func SUIColor(_ r: Double, _ g: Double, _ b: Double, _ a: Double) -> UnsafeMutableRawPointer {
    let view = AnyView(Color(red: r, green: g, blue: b, opacity: a))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUICircle")
public func SUICircle() -> UnsafeMutableRawPointer {
    let view = AnyView(Circle())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIRectangle")
public func SUIRectangle() -> UnsafeMutableRawPointer {
    let view = AnyView(Rectangle())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIRoundedRectangle")
public func SUIRoundedRectangle(_ cornerRadius: Double) -> UnsafeMutableRawPointer {
    let view = AnyView(RoundedRectangle(cornerRadius: cornerRadius))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUICapsule")
public func SUICapsule() -> UnsafeMutableRawPointer {
    let view = AnyView(Capsule())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUILink")
public func SUILink(_ titlePtr: UnsafePointer<CChar>, _ urlPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let title = String(cString: titlePtr)
    let urlString = String(cString: urlPtr)
    let view: AnyView
    if let url = URL(string: urlString) {
        view = AnyView(Link(title, destination: url))
    } else {
        view = AnyView(Text(title))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIGauge")
public func SUIGauge(_ value: Double, _ labelPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let label = String(cString: labelPtr)
    let view = AnyView(Gauge(value: value) { Text(label) })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIWebPageCreate")
@MainActor
public func SUIWebPageCreate() -> UnsafeMutableRawPointer {
    let page = WebPage()
    return Unmanaged.passRetained(page).toOpaque()
}

@_cdecl("SUIWebPageLoadURL")
@MainActor
public func SUIWebPageLoadURL(_ pageRef: UnsafeMutableRawPointer, _ urlPtr: UnsafePointer<CChar>) {
    let page = Unmanaged<WebPage>.fromOpaque(pageRef).takeUnretainedValue()
    let urlString = String(cString: urlPtr)
    guard let url = URL(string: urlString) else {
        return
    }
    page.load(URLRequest(url: url))
}

@_cdecl("SUIWebPageReload")
@MainActor
public func SUIWebPageReload(_ pageRef: UnsafeMutableRawPointer) {
    let page = Unmanaged<WebPage>.fromOpaque(pageRef).takeUnretainedValue()
    page.reload()
}

@_cdecl("SUIWebViewPage")
@MainActor
public func SUIWebViewPage(_ pageRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let page = Unmanaged<WebPage>.fromOpaque(pageRef).takeUnretainedValue()
    let view = AnyView(WebView(page))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Binding views

@_cdecl("SUIToggle")
@MainActor
public func SUIToggle(_ labelPtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let label = String(cString: labelPtr)
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedToggle(label: label, state: state, callbackID: callbackID))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedToggle: View {
    let label: String
    var state: BridgedIntState
    let callbackID: UInt

    var body: some View {
        Toggle(label, isOn: Binding(
            get: { state.value != 0 },
            set: { newValue in
                state.value = newValue ? 1 : 0
                _SUIButtonCallback?(callbackID)
            }
        ))
    }
}

@_cdecl("SUITextField")
@MainActor
public func SUITextField(_ placeholderPtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ onSubmitID: UInt) -> UnsafeMutableRawPointer {
    let placeholder = String(cString: placeholderPtr)
    let state = Unmanaged<BridgedStringState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedTextField(placeholder: placeholder, state: state, onSubmitID: onSubmitID))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedTextField: View {
    let placeholder: String
    var state: BridgedStringState
    let onSubmitID: UInt

    var body: some View {
        TextField(placeholder, text: Binding(
            get: { state.value },
            set: { state.value = $0 }
        ))
        .onSubmit {
            _SUIButtonCallback?(onSubmitID)
        }
    }
}

@_cdecl("SUISecureField")
@MainActor
public func SUISecureField(_ placeholderPtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ onSubmitID: UInt) -> UnsafeMutableRawPointer {
    let placeholder = String(cString: placeholderPtr)
    let state = Unmanaged<BridgedStringState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedSecureField(placeholder: placeholder, state: state, onSubmitID: onSubmitID))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedSecureField: View {
    let placeholder: String
    var state: BridgedStringState
    let onSubmitID: UInt

    var body: some View {
        SecureField(placeholder, text: Binding(
            get: { state.value },
            set: { state.value = $0 }
        ))
        .onSubmit {
            _SUIButtonCallback?(onSubmitID)
        }
    }
}

@_cdecl("SUITextEditor")
@MainActor
public func SUITextEditor(_ stateRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let state = Unmanaged<BridgedStringState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedTextEditor(state: state))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedTextEditor: View {
    var state: BridgedStringState

    var body: some View {
        TextEditor(text: Binding(
            get: { state.value },
            set: { state.value = $0 }
        ))
    }
}

@_cdecl("SUISlider")
@MainActor
public func SUISlider(_ labelPtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ min: Double, _ max: Double, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let label = String(cString: labelPtr)
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedSlider(label: label, state: state, minValue: min, maxValue: max, callbackID: callbackID))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedSlider: View {
    let label: String
    var state: BridgedIntState
    let minValue: Double
    let maxValue: Double
    let callbackID: UInt

    var body: some View {
        Slider(value: Binding(
            get: { Double(state.value) },
            set: { state.value = Int($0) }
        ), in: minValue...maxValue) {
            Text(label)
        } onEditingChanged: { editing in
            if !editing {
                _SUIButtonCallback?(callbackID)
            }
        }
    }
}

@_cdecl("SUIPickerSegmented")
@MainActor
public func SUIPickerSegmented(_ labelPtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ optionsRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let label = String(cString: labelPtr)
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let options = Unmanaged<Box<AnyView>>.fromOpaque(optionsRef).takeUnretainedValue().value
    let view = AnyView(BridgedPicker(label: label, state: state, options: options, callbackID: callbackID))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedPicker: View {
    let label: String
    var state: BridgedIntState
    let options: AnyView
    let callbackID: UInt

    var body: some View {
        Picker(label, selection: Binding(
            get: { state.value },
            set: { newValue in
                state.value = newValue
                _SUIButtonCallback?(callbackID)
            }
        )) {
            options
        }
        .pickerStyle(.segmented)
    }
}

@_cdecl("SUIStepperInt")
@MainActor
public func SUIStepperInt(_ labelPtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ min: Int32, _ max: Int32, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let label = String(cString: labelPtr)
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedStepper(label: label, state: state, minValue: Int(min), maxValue: Int(max), callbackID: callbackID))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedStepper: View {
    let label: String
    var state: BridgedIntState
    let minValue: Int
    let maxValue: Int
    let callbackID: UInt

    var body: some View {
        Stepper(label, value: Binding(
            get: { state.value },
            set: { newValue in
                state.value = newValue
                _SUIButtonCallback?(callbackID)
            }
        ), in: minValue...maxValue)
    }
}

@_cdecl("SUIPickerMenu")
@MainActor
public func SUIPickerMenu(_ labelPtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ optionsRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let label = String(cString: labelPtr)
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let options = Unmanaged<Box<AnyView>>.fromOpaque(optionsRef).takeUnretainedValue().value
    let view = AnyView(BridgedPickerMenu(label: label, state: state, options: options, callbackID: callbackID))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedPickerMenu: View {
    let label: String
    var state: BridgedIntState
    let options: AnyView
    let callbackID: UInt

    var body: some View {
        Picker(label, selection: Binding(
            get: { state.value },
            set: { newValue in
                state.value = newValue
                _SUIButtonCallback?(callbackID)
            }
        )) {
            options
        }
        .pickerStyle(.menu)
    }
}
