// Code generated by applegen; DO NOT EDIT.

import SwiftUI
import WebKit


// MARK: - View modifiers

@_cdecl("SUIViewPadding")
public func SUIViewPadding(_ viewRef: UnsafeMutableRawPointer, _ amount: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.padding(amount))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewPaddingEdge")
public func SUIViewPaddingEdge(_ viewRef: UnsafeMutableRawPointer, _ edges: Int32, _ amount: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let edgeSet = Edge.Set(rawValue: Int8(edges))
    let view = AnyView(base.padding(edgeSet, amount))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFont")
public func SUIViewFont(_ viewRef: UnsafeMutableRawPointer, _ fontRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let font = Unmanaged<Box<Font>>.fromOpaque(fontRef).takeUnretainedValue().value
    let view = AnyView(base.font(font))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFrame")
public func SUIViewFrame(_ viewRef: UnsafeMutableRawPointer, _ width: Double, _ height: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.frame(width: width, height: height))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewMaxFrame")
public func SUIViewMaxFrame(_ viewRef: UnsafeMutableRawPointer, _ maxWidth: Double, _ maxHeight: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    var w: CGFloat? = nil
    if maxWidth < 0 { w = .infinity } else if maxWidth > 0 { w = CGFloat(maxWidth) }
    var h: CGFloat? = nil
    if maxHeight < 0 { h = .infinity } else if maxHeight > 0 { h = CGFloat(maxHeight) }
    let view = AnyView(base.frame(maxWidth: w, maxHeight: h))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewForegroundStyle")
public func SUIViewForegroundStyle(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.foregroundStyle(color))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewForegroundStyleName")
public func SUIViewForegroundStyleName(_ viewRef: UnsafeMutableRawPointer, _ name: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let styleName = String(cString: name)
    let style: any ShapeStyle = switch styleName {
    case "primary": .primary
    case "secondary": .secondary
    case "tertiary": .tertiary
    case "quaternary": .quaternary
    default: .primary
    }
    let view = AnyView(base.foregroundStyle(style))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewButtonStyle")
@MainActor
public func SUIViewButtonStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 0: view = AnyView(base.buttonStyle(.automatic))
    case 1: view = AnyView(base.buttonStyle(.bordered))
    case 2: view = AnyView(base.buttonStyle(.borderedProminent))
    case 3: view = AnyView(base.buttonStyle(.borderless))
    case 4: view = AnyView(base.buttonStyle(.plain))
    default: view = AnyView(base.buttonStyle(.automatic))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewControlSize")
public func SUIViewControlSize(_ viewRef: UnsafeMutableRawPointer, _ size: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let cs: ControlSize
    switch size {
    case 0: cs = .mini
    case 1: cs = .small
    case 2: cs = .regular
    case 3: cs = .large
    case 4: cs = .extraLarge
    default: cs = .regular
    }
    let view = AnyView(base.controlSize(cs))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewImageScale")
public func SUIViewImageScale(_ viewRef: UnsafeMutableRawPointer, _ scale: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let s: Image.Scale
    switch scale {
    case 0: s = .small
    case 1: s = .medium
    case 2: s = .large
    default: s = .medium
    }
    let view = AnyView(base.imageScale(s))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFontWeight")
public func SUIViewFontWeight(_ viewRef: UnsafeMutableRawPointer, _ weight: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let w: Font.Weight
    switch weight {
    case 0: w = .ultraLight
    case 1: w = .thin
    case 2: w = .light
    case 3: w = .regular
    case 4: w = .medium
    case 5: w = .semibold
    case 6: w = .bold
    case 7: w = .heavy
    case 8: w = .black
    default: w = .regular
    }
    let view = AnyView(base.fontWeight(w))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFontDesign")
public func SUIViewFontDesign(_ viewRef: UnsafeMutableRawPointer, _ design: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let d: Font.Design
    switch design {
    case 0: d = .default
    case 1: d = .rounded
    case 2: d = .monospaced
    case 3: d = .serif
    default: d = .default
    }
    let view = AnyView(base.fontDesign(d))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewMonospacedDigit")
public func SUIViewMonospacedDigit(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.monospacedDigit())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewMultilineTextAlignment")
public func SUIViewMultilineTextAlignment(_ viewRef: UnsafeMutableRawPointer, _ alignment: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let a: TextAlignment
    switch alignment {
    case 0: a = .leading
    case 1: a = .center
    case 2: a = .trailing
    default: a = .center
    }
    let view = AnyView(base.multilineTextAlignment(a))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOpacity")
public func SUIViewOpacity(_ viewRef: UnsafeMutableRawPointer, _ opacity: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.opacity(opacity))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewDisabled")
public func SUIViewDisabled(_ viewRef: UnsafeMutableRawPointer, _ disabled: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.disabled(disabled != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewHelp")
public func SUIViewHelp(_ viewRef: UnsafeMutableRawPointer, _ text: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.help(String(cString: text)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBackground")
public func SUIViewBackground(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.background(color))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBackgroundRoundedRect")
public func SUIViewBackgroundRoundedRect(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double, _ cornerRadius: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.background(RoundedRectangle(cornerRadius: cornerRadius).fill(color)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewClipRoundedRect")
public func SUIViewClipRoundedRect(_ viewRef: UnsafeMutableRawPointer, _ cornerRadius: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.clipShape(RoundedRectangle(cornerRadius: cornerRadius)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOverlay")
public func SUIViewOverlay(_ viewRef: UnsafeMutableRawPointer, _ overlayRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let overlay = Unmanaged<Box<AnyView>>.fromOpaque(overlayRef).takeUnretainedValue().value
    let view = AnyView(base.overlay(overlay))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBackgroundStyle")
public func SUIViewBackgroundStyle(_ viewRef: UnsafeMutableRawPointer, _ name: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let styleName = String(cString: name)
    let view: AnyView
    switch styleName {
    case "regularMaterial": view = AnyView(base.background(.regularMaterial))
    case "thinMaterial": view = AnyView(base.background(.thinMaterial))
    case "ultraThinMaterial": view = AnyView(base.background(.ultraThinMaterial))
    case "thickMaterial": view = AnyView(base.background(.thickMaterial))
    case "bar": view = AnyView(base.background(.bar))
    case "separator": view = AnyView(base.background(Color(nsColor: .separatorColor)))
    case "windowBackground": view = AnyView(base.background(Color(nsColor: .windowBackgroundColor)))
    case "controlBackground": view = AnyView(base.background(Color(nsColor: .controlBackgroundColor)))
    case "textBackground": view = AnyView(base.background(Color(nsColor: .textBackgroundColor)))
    default: view = AnyView(base.background(.background))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewLineLimit")
public func SUIViewLineLimit(_ viewRef: UnsafeMutableRawPointer, _ limit: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    if limit <= 0 {
        view = AnyView(base.lineLimit(nil))
    } else {
        view = AnyView(base.lineLimit(Int(limit)))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewTextFieldStyle")
public func SUIViewTextFieldStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 0: view = AnyView(base.textFieldStyle(.automatic))
    case 1: view = AnyView(base.textFieldStyle(.roundedBorder))
    case 2: view = AnyView(base.textFieldStyle(.plain))
    default: view = AnyView(base.textFieldStyle(.automatic))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Font constructors

@_cdecl("SUIFontSystem")
public func SUIFontSystem(_ size: Double) -> UnsafeMutableRawPointer {
    let font = Font.system(size: size)
    return Unmanaged.passRetained(Box(font)).toOpaque()
}

@_cdecl("SUIFontSystemDesign")
public func SUIFontSystemDesign(_ size: Double, _ weight: Int32, _ design: Int32) -> UnsafeMutableRawPointer {
    let w: Font.Weight
    switch weight {
    case 0: w = .ultraLight
    case 1: w = .thin
    case 2: w = .light
    case 3: w = .regular
    case 4: w = .medium
    case 5: w = .semibold
    case 6: w = .bold
    case 7: w = .heavy
    case 8: w = .black
    default: w = .regular
    }
    let d: Font.Design
    switch design {
    case 0: d = .default
    case 1: d = .rounded
    case 2: d = .monospaced
    case 3: d = .serif
    default: d = .default
    }
    let font = Font.system(size: size, weight: w, design: d)
    return Unmanaged.passRetained(Box(font)).toOpaque()
}

@_cdecl("SUIFontNamed")
public func SUIFontNamed(_ name: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let fontName = String(cString: name)
    let font: Font
    switch fontName {
    case "largeTitle": font = .largeTitle
    case "title": font = .title
    case "title2": font = .title2
    case "title3": font = .title3
    case "headline": font = .headline
    case "subheadline": font = .subheadline
    case "body": font = .body
    case "callout": font = .callout
    case "footnote": font = .footnote
    case "caption": font = .caption
    case "caption2": font = .caption2
    default: font = .body
    }
    return Unmanaged.passRetained(Box(font)).toOpaque()
}

@_cdecl("SUIViewAnimation")
public func SUIViewAnimation(_ viewRef: UnsafeMutableRawPointer, _ kind: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch kind {
    case 0: view = AnyView(base.animation(.easeInOut, value: true))
    case 1: view = AnyView(base.animation(.easeIn, value: true))
    case 2: view = AnyView(base.animation(.easeOut, value: true))
    case 3: view = AnyView(base.animation(.spring, value: true))
    case 4: view = AnyView(base.animation(.bouncy, value: true))
    default: view = AnyView(base.animation(.default, value: true))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Additional modifiers

@_cdecl("SUIViewShadow")
public func SUIViewShadow(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double, _ radius: Double, _ x: Double, _ y: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.shadow(color: color, radius: radius, x: x, y: y))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBorder")
public func SUIViewBorder(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double, _ width: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.border(color, width: width))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewCornerRadius")
public func SUIViewCornerRadius(_ viewRef: UnsafeMutableRawPointer, _ radius: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.clipShape(RoundedRectangle(cornerRadius: radius)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewScaleEffect")
public func SUIViewScaleEffect(_ viewRef: UnsafeMutableRawPointer, _ scale: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.scaleEffect(scale))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewRotationEffect")
public func SUIViewRotationEffect(_ viewRef: UnsafeMutableRawPointer, _ degrees: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.rotationEffect(.degrees(degrees)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOffset")
public func SUIViewOffset(_ viewRef: UnsafeMutableRawPointer, _ x: Double, _ y: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.offset(x: x, y: y))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewAllowsHitTesting")
public func SUIViewAllowsHitTesting(_ viewRef: UnsafeMutableRawPointer, _ enabled: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.allowsHitTesting(enabled != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOnTapGesture")
public func SUIViewOnTapGesture(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onTapGesture {
        _SUIButtonCallback?(id)
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFocusable")
public func SUIViewFocusable(_ viewRef: UnsafeMutableRawPointer, _ focusable: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.focusable(focusable != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewNavigationTitle")
public func SUIViewNavigationTitle(_ viewRef: UnsafeMutableRawPointer, _ titlePtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let title = String(cString: titlePtr)
    let view = AnyView(base.navigationTitle(title))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewTabItem")
public func SUIViewTabItem(_ viewRef: UnsafeMutableRawPointer, _ labelPtr: UnsafePointer<CChar>, _ systemImagePtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let label = String(cString: labelPtr)
    let img = String(cString: systemImagePtr)
    let view = AnyView(base.tabItem { Label(label, systemImage: img) })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewTag")
public func SUIViewTag(_ viewRef: UnsafeMutableRawPointer, _ tag: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.tag(Int(tag)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFill")
public func SUIViewFill(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.foregroundStyle(color))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewStroke")
public func SUIViewStroke(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double, _ lineWidth: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.overlay(
        RoundedRectangle(cornerRadius: 0).stroke(color, lineWidth: lineWidth)
    ))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Lifecycle and interaction modifiers

@_cdecl("SUIViewOnAppear")
public func SUIViewOnAppear(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onAppear { _SUIButtonCallback?(id) })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOnDisappear")
public func SUIViewOnDisappear(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onDisappear { _SUIButtonCallback?(id) })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOnHover")
public func SUIViewOnHover(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onHover { _ in _SUIButtonCallback?(id) })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewTint")
public func SUIViewTint(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.tint(color))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFixedSize")
public func SUIViewFixedSize(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.fixedSize())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFixedSizeAxis")
public func SUIViewFixedSizeAxis(_ viewRef: UnsafeMutableRawPointer, _ horizontal: Int32, _ vertical: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.fixedSize(horizontal: horizontal != 0, vertical: vertical != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewAspectRatio")
public func SUIViewAspectRatio(_ viewRef: UnsafeMutableRawPointer, _ ratio: Double, _ contentMode: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let mode: ContentMode = contentMode == 1 ? .fill : .fit
    let view = AnyView(base.aspectRatio(ratio, contentMode: mode))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewSheet")
@MainActor
public func SUIViewSheet(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let sheetContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(BridgedSheetView(base: base, state: state, sheetContent: sheetContent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedSheetView: View {
    let base: AnyView
    var state: BridgedIntState
    let sheetContent: AnyView

    var body: some View {
        base.sheet(isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.value = 0 } }
        )) {
            sheetContent
        }
    }
}

@_cdecl("SUIViewAlert")
@MainActor
public func SUIViewAlert(_ viewRef: UnsafeMutableRawPointer, _ titlePtr: UnsafePointer<CChar>, _ messagePtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let title = String(cString: titlePtr)
    let message = String(cString: messagePtr)
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedAlertView(base: base, title: title, message: message, state: state))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedAlertView: View {
    let base: AnyView
    let title: String
    let message: String
    var state: BridgedIntState

    var body: some View {
        base.alert(title, isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.value = 0 } }
        )) {
            Button("OK") {}
        } message: {
            Text(message)
        }
    }
}

@_cdecl("SUIViewConfirmationDialog")
@MainActor
public func SUIViewConfirmationDialog(_ viewRef: UnsafeMutableRawPointer, _ titlePtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ actionsRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let title = String(cString: titlePtr)
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let actions = Unmanaged<Box<AnyView>>.fromOpaque(actionsRef).takeUnretainedValue().value
    let view = AnyView(BridgedConfirmationDialogView(base: base, title: title, state: state, actions: actions))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedConfirmationDialogView: View {
    let base: AnyView
    let title: String
    var state: BridgedIntState
    let actions: AnyView

    var body: some View {
        base.confirmationDialog(title, isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.value = 0 } }
        )) {
            actions
        }
    }
}

@_cdecl("SUIViewContextMenu")
public func SUIViewContextMenu(_ viewRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let menuContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(base.contextMenu { menuContent })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Text appearance modifiers

@_cdecl("SUIViewBold")
public func SUIViewBold(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.bold())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewItalic")
public func SUIViewItalic(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.italic())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewUnderline")
public func SUIViewUnderline(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.underline())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewStrikethrough")
public func SUIViewStrikethrough(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.strikethrough())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewTruncationMode")
public func SUIViewTruncationMode(_ viewRef: UnsafeMutableRawPointer, _ mode: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let m: Text.TruncationMode
    switch mode {
    case 0: m = .head
    case 1: m = .middle
    case 2: m = .tail
    default: m = .tail
    }
    let view = AnyView(base.truncationMode(m))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewSymbolRenderingMode")
public func SUIViewSymbolRenderingMode(_ viewRef: UnsafeMutableRawPointer, _ mode: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let m: SymbolRenderingMode
    switch mode {
    case 0: m = .monochrome
    case 1: m = .hierarchical
    case 2: m = .palette
    case 3: m = .multicolor
    default: m = .monochrome
    }
    let view = AnyView(base.symbolRenderingMode(m))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Layout modifiers

@_cdecl("SUIViewZIndex")
public func SUIViewZIndex(_ viewRef: UnsafeMutableRawPointer, _ index: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.zIndex(index))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewLayoutPriority")
public func SUIViewLayoutPriority(_ viewRef: UnsafeMutableRawPointer, _ priority: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.layoutPriority(priority))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBlur")
public func SUIViewBlur(_ viewRef: UnsafeMutableRawPointer, _ radius: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.blur(radius: radius))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewClipped")
public func SUIViewClipped(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.clipped())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewMask")
public func SUIViewMask(_ viewRef: UnsafeMutableRawPointer, _ maskRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let maskView = Unmanaged<Box<AnyView>>.fromOpaque(maskRef).takeUnretainedValue().value
    let view = AnyView(base.mask { maskView })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Accessibility modifiers

@_cdecl("SUIViewAccessibilityLabel")
public func SUIViewAccessibilityLabel(_ viewRef: UnsafeMutableRawPointer, _ labelPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let label = String(cString: labelPtr)
    let view = AnyView(base.accessibilityLabel(label))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewAccessibilityHint")
public func SUIViewAccessibilityHint(_ viewRef: UnsafeMutableRawPointer, _ hintPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let hint = String(cString: hintPtr)
    let view = AnyView(base.accessibilityHint(hint))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewAccessibilityHidden")
public func SUIViewAccessibilityHidden(_ viewRef: UnsafeMutableRawPointer, _ hidden: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.accessibilityHidden(hidden != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - List modifiers

@_cdecl("SUIViewListStyle")
public func SUIViewListStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 0: view = AnyView(base.listStyle(.automatic))
    case 1: view = AnyView(base.listStyle(.sidebar))
    case 2: view = AnyView(base.listStyle(.inset))
    case 3: view = AnyView(base.listStyle(.plain))
    default: view = AnyView(base.listStyle(.automatic))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewListRowBackground")
public func SUIViewListRowBackground(_ viewRef: UnsafeMutableRawPointer, _ bgRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let bg = Unmanaged<Box<AnyView>>.fromOpaque(bgRef).takeUnretainedValue().value
    let view = AnyView(base.listRowBackground(bg))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewBackForwardNavigationGestures")
@MainActor
public func SUIViewWebViewBackForwardNavigationGestures(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    if #available(macOS 26.0, *) {
        let mode: WebView.BackForwardNavigationGesturesBehavior
        switch behavior {
        case 1: mode = .enabled
        case 2: mode = .disabled
        default: mode = .automatic
        }
        view = AnyView(base.webViewBackForwardNavigationGestures(mode))
    } else {
        view = base
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewContentBackground")
@MainActor
public func SUIViewWebViewContentBackground(_ viewRef: UnsafeMutableRawPointer, _ visibility: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    if #available(macOS 26.0, *) {
        let mode: Visibility
        switch visibility {
        case 1: mode = .visible
        case 2: mode = .hidden
        default: mode = .automatic
        }
        view = AnyView(base.webViewContentBackground(mode))
    } else {
        view = base
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewElementFullscreenBehavior")
@MainActor
public func SUIViewWebViewElementFullscreenBehavior(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    if #available(macOS 26.0, *) {
        let mode: WebView.ElementFullscreenBehavior
        switch behavior {
        case 1: mode = .enabled
        case 2: mode = .disabled
        default: mode = .automatic
        }
        view = AnyView(base.webViewElementFullscreenBehavior(mode))
    } else {
        view = base
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewLinkPreviews")
@MainActor
public func SUIViewWebViewLinkPreviews(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    if #available(macOS 26.0, *) {
        let mode: WebView.LinkPreviewBehavior
        switch behavior {
        case 1: mode = .enabled
        case 2: mode = .disabled
        default: mode = .automatic
        }
        view = AnyView(base.webViewLinkPreviews(mode))
    } else {
        view = base
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewMagnificationGestures")
@MainActor
public func SUIViewWebViewMagnificationGestures(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    if #available(macOS 26.0, *) {
        let mode: WebView.MagnificationGesturesBehavior
        switch behavior {
        case 1: mode = .enabled
        case 2: mode = .disabled
        default: mode = .automatic
        }
        view = AnyView(base.webViewMagnificationGestures(mode))
    } else {
        view = base
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewTextSelection")
@MainActor
public func SUIViewWebViewTextSelection(_ viewRef: UnsafeMutableRawPointer, _ enabled: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    if #available(macOS 26.0, *) {
        let mode: TextSelectability = enabled != 0 ? .enabled : .disabled
        view = AnyView(base.webViewTextSelection(mode))
    } else {
        view = base
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Presentation modifiers

@_cdecl("SUIViewPopover")
@MainActor
public func SUIViewPopover(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let popoverContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(BridgedPopoverView(base: base, state: state, popoverContent: popoverContent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedPopoverView: View {
    let base: AnyView
    var state: BridgedIntState
    let popoverContent: AnyView

    var body: some View {
        base.popover(isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.value = 0 } }
        )) {
            popoverContent
        }
    }
}

@_cdecl("SUIViewFullScreenCover")
@MainActor
public func SUIViewFullScreenCover(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let coverContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(BridgedFullScreenCoverView(base: base, state: state, coverContent: coverContent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedFullScreenCoverView: View {
    let base: AnyView
    var state: BridgedIntState
    let coverContent: AnyView

    var body: some View {
        // fullScreenCover is iOS-only; use sheet on macOS.
        #if os(iOS)
        base.fullScreenCover(isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.value = 0 } }
        )) {
            coverContent
        }
        #else
        base.sheet(isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.value = 0 } }
        )) {
            coverContent
        }
        #endif
    }
}
