// Code generated by applegen; DO NOT EDIT.

import SwiftUI

private func bridgedGlass(
    variant: Int32,
    tintSet: Int32,
    r: Double,
    g: Double,
    b: Double,
    a: Double,
    interactiveSet: Int32,
    interactiveEnabled: Int32
) -> Glass {
    let base: Glass
    switch variant {
    case 1:
        base = .clear
    case 2:
        base = .identity
    default:
        base = .regular
    }

    let tinted: Glass
    if tintSet != 0 {
        tinted = base.tint(Color(red: r, green: g, blue: b, opacity: a))
    } else {
        tinted = base
    }

    if interactiveSet != 0 {
        return tinted.interactive(interactiveEnabled != 0)
    }
    return tinted
}

@_cdecl("SUINamespaceCreate")
public func SUINamespaceCreate() -> UnsafeMutableRawPointer {
    let namespace = Namespace().wrappedValue
    return Unmanaged.passRetained(Box(namespace)).toOpaque()
}

@_cdecl("SUIGlassEffectContainer")
@MainActor
public func SUIGlassEffectContainer(_ contentRef: UnsafeMutableRawPointer, _ spacing: Double) -> UnsafeMutableRawPointer {
    let content = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view: AnyView
    if spacing < 0 {
        view = AnyView(GlassEffectContainer {
            content
        })
    } else {
        view = AnyView(GlassEffectContainer(spacing: spacing) {
            content
        })
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewGlassEffect")
public func SUIViewGlassEffect(
    _ viewRef: UnsafeMutableRawPointer,
    _ variant: Int32,
    _ tintSet: Int32,
    _ r: Double,
    _ g: Double,
    _ b: Double,
    _ a: Double,
    _ interactiveSet: Int32,
    _ interactiveEnabled: Int32,
    _ shape: Int32,
    _ cornerRadius: Double
) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let glass = bridgedGlass(
        variant: variant,
        tintSet: tintSet,
        r: r,
        g: g,
        b: b,
        a: a,
        interactiveSet: interactiveSet,
        interactiveEnabled: interactiveEnabled
    )

    let view: AnyView
    switch shape {
    case 0:
        view = AnyView(base.glassEffect(glass, in: RoundedRectangle(cornerRadius: cornerRadius)))
    case 1:
        view = AnyView(base.glassEffect(glass, in: Capsule()))
    case 2:
        view = AnyView(base.glassEffect(glass, in: Circle()))
    default:
        view = AnyView(base.glassEffect(glass))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewGlassEffectID")
public func SUIViewGlassEffectID(
    _ viewRef: UnsafeMutableRawPointer,
    _ id: UnsafePointer<CChar>,
    _ namespaceRef: UnsafeMutableRawPointer
) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let namespace = Unmanaged<Box<Namespace.ID>>.fromOpaque(namespaceRef).takeUnretainedValue().value
    let view = AnyView(base.glassEffectID(String(cString: id), in: namespace))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewGlassEffectUnion")
@MainActor
public func SUIViewGlassEffectUnion(
    _ viewRef: UnsafeMutableRawPointer,
    _ id: UnsafePointer<CChar>,
    _ namespaceRef: UnsafeMutableRawPointer
) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let namespace = Unmanaged<Box<Namespace.ID>>.fromOpaque(namespaceRef).takeUnretainedValue().value
    let view = AnyView(base.glassEffectUnion(id: String(cString: id), namespace: namespace))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewGlassEffectTransition")
@MainActor
public func SUIViewGlassEffectTransition(_ viewRef: UnsafeMutableRawPointer, _ transition: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let resolved: GlassEffectTransition
    switch transition {
    case 1:
        resolved = .matchedGeometry
    case 2:
        resolved = .materialize
    default:
        resolved = .identity
    }
    let view = AnyView(base.glassEffectTransition(resolved))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewGlassButtonStyle")
@MainActor
public func SUIViewGlassButtonStyle(
    _ viewRef: UnsafeMutableRawPointer,
    _ variant: Int32,
    _ tintSet: Int32,
    _ r: Double,
    _ g: Double,
    _ b: Double,
    _ a: Double,
    _ interactiveSet: Int32,
    _ interactiveEnabled: Int32
) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let glass = bridgedGlass(
        variant: variant,
        tintSet: tintSet,
        r: r,
        g: g,
        b: b,
        a: a,
        interactiveSet: interactiveSet,
        interactiveEnabled: interactiveEnabled
    )
    let view = AnyView(base.buttonStyle(.glass(glass)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewGlassProminentButtonStyle")
@MainActor
public func SUIViewGlassProminentButtonStyle(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.buttonStyle(.glassProminent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}
