// Code generated by applegen; DO NOT EDIT.

import SwiftUI
import WebKit


// MARK: - View modifiers

@_cdecl("SUIViewPadding")
public func SUIViewPadding(_ viewRef: UnsafeMutableRawPointer, _ amount: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.padding(amount))
    return retainDerivedView(from: viewRef, view)
}

@_cdecl("SUIViewPaddingEdge")
public func SUIViewPaddingEdge(_ viewRef: UnsafeMutableRawPointer, _ edges: Int32, _ amount: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let edgeSet = Edge.Set(rawValue: Int8(edges))
    let view = AnyView(base.padding(edgeSet, amount))
    return retainDerivedView(from: viewRef, view)
}

@_cdecl("SUIViewFont")
public func SUIViewFont(_ viewRef: UnsafeMutableRawPointer, _ fontRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let font = Unmanaged<Box<Font>>.fromOpaque(fontRef).takeUnretainedValue().value
    let view = AnyView(base.font(font))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFrame")
public func SUIViewFrame(_ viewRef: UnsafeMutableRawPointer, _ width: Double, _ height: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.frame(width: width, height: height))
    return retainDerivedView(from: viewRef, view)
}

@_cdecl("SUIViewMaxFrame")
public func SUIViewMaxFrame(_ viewRef: UnsafeMutableRawPointer, _ maxWidth: Double, _ maxHeight: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    var w: CGFloat? = nil
    if maxWidth < 0 { w = .infinity } else if maxWidth > 0 { w = CGFloat(maxWidth) }
    var h: CGFloat? = nil
    if maxHeight < 0 { h = .infinity } else if maxHeight > 0 { h = CGFloat(maxHeight) }
    let view = AnyView(base.frame(maxWidth: w, maxHeight: h))
    return retainDerivedView(from: viewRef, view)
}

@_cdecl("SUIViewForegroundStyle")
public func SUIViewForegroundStyle(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.foregroundStyle(color))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewForegroundStyleName")
public func SUIViewForegroundStyleName(_ viewRef: UnsafeMutableRawPointer, _ name: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let styleName = String(cString: name)
    let style: any ShapeStyle = switch styleName {
    case "primary": .primary
    case "secondary": .secondary
    case "tertiary": .tertiary
    case "quaternary": .quaternary
    default: .primary
    }
    let view = AnyView(base.foregroundStyle(style))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewButtonStyle")
@MainActor
public func SUIViewButtonStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 0: view = AnyView(base.buttonStyle(.automatic))
    case 1: view = AnyView(base.buttonStyle(.bordered))
    case 2: view = AnyView(base.buttonStyle(.borderedProminent))
    case 3: view = AnyView(base.buttonStyle(.borderless))
    case 4: view = AnyView(base.buttonStyle(.plain))
    default: view = AnyView(base.buttonStyle(.automatic))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewToggleStyle")
@MainActor
public func SUIViewToggleStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 0: view = AnyView(base.toggleStyle(.automatic))
    case 1: view = AnyView(base.toggleStyle(.button))
    case 2: view = AnyView(base.toggleStyle(.checkbox))
    case 3: view = AnyView(base.toggleStyle(.switch))
    default: view = AnyView(base.toggleStyle(.automatic))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewControlSize")
public func SUIViewControlSize(_ viewRef: UnsafeMutableRawPointer, _ size: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let cs: ControlSize
    switch size {
    case 0: cs = .mini
    case 1: cs = .small
    case 2: cs = .regular
    case 3: cs = .large
    case 4: cs = .extraLarge
    default: cs = .regular
    }
    let view = AnyView(base.controlSize(cs))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewImageScale")
public func SUIViewImageScale(_ viewRef: UnsafeMutableRawPointer, _ scale: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let s: Image.Scale
    switch scale {
    case 0: s = .small
    case 1: s = .medium
    case 2: s = .large
    default: s = .medium
    }
    let view = AnyView(base.imageScale(s))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFontWeight")
public func SUIViewFontWeight(_ viewRef: UnsafeMutableRawPointer, _ weight: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let w: Font.Weight
    switch weight {
    case 0: w = .ultraLight
    case 1: w = .thin
    case 2: w = .light
    case 3: w = .regular
    case 4: w = .medium
    case 5: w = .semibold
    case 6: w = .bold
    case 7: w = .heavy
    case 8: w = .black
    default: w = .regular
    }
    let view = AnyView(base.fontWeight(w))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFontDesign")
public func SUIViewFontDesign(_ viewRef: UnsafeMutableRawPointer, _ design: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let d: Font.Design
    switch design {
    case 0: d = .default
    case 1: d = .rounded
    case 2: d = .monospaced
    case 3: d = .serif
    default: d = .default
    }
    let view = AnyView(base.fontDesign(d))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewMonospacedDigit")
public func SUIViewMonospacedDigit(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.monospacedDigit())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewMultilineTextAlignment")
public func SUIViewMultilineTextAlignment(_ viewRef: UnsafeMutableRawPointer, _ alignment: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let a: TextAlignment
    switch alignment {
    case 0: a = .leading
    case 1: a = .center
    case 2: a = .trailing
    default: a = .center
    }
    let view = AnyView(base.multilineTextAlignment(a))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOpacity")
public func SUIViewOpacity(_ viewRef: UnsafeMutableRawPointer, _ opacity: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.opacity(opacity))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewDisabled")
public func SUIViewDisabled(_ viewRef: UnsafeMutableRawPointer, _ disabled: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.disabled(disabled != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewHelp")
public func SUIViewHelp(_ viewRef: UnsafeMutableRawPointer, _ text: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.help(String(cString: text)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBackground")
public func SUIViewBackground(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.background(color))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBackgroundRoundedRect")
public func SUIViewBackgroundRoundedRect(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double, _ cornerRadius: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let shape = RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
    let view = AnyView(base.background(color, in: shape))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewClipRoundedRect")
public func SUIViewClipRoundedRect(_ viewRef: UnsafeMutableRawPointer, _ cornerRadius: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.clipShape(RoundedRectangle(cornerRadius: cornerRadius)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewContentShapeRectangle")
public func SUIViewContentShapeRectangle(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.contentShape(Rectangle()))
    return retainDerivedView(from: viewRef, view)
}

@_cdecl("SUIViewOverlay")
public func SUIViewOverlay(_ viewRef: UnsafeMutableRawPointer, _ overlayRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let overlay = Unmanaged<Box<AnyView>>.fromOpaque(overlayRef).takeUnretainedValue().value
    let view = AnyView(base.overlay(overlay))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBackgroundStyle")
public func SUIViewBackgroundStyle(_ viewRef: UnsafeMutableRawPointer, _ name: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let styleName = String(cString: name)
    let view: AnyView
    switch styleName {
    case "regularMaterial": view = AnyView(base.background(.regularMaterial))
    case "thinMaterial": view = AnyView(base.background(.thinMaterial))
    case "ultraThinMaterial": view = AnyView(base.background(.ultraThinMaterial))
    case "thickMaterial": view = AnyView(base.background(.thickMaterial))
    case "bar": view = AnyView(base.background(.bar))
    case "separator": view = AnyView(base.background(Color(nsColor: .separatorColor)))
    case "windowBackground": view = AnyView(base.background(Color(nsColor: .windowBackgroundColor)))
    case "controlBackground": view = AnyView(base.background(Color(nsColor: .controlBackgroundColor)))
    case "textBackground": view = AnyView(base.background(Color(nsColor: .textBackgroundColor)))
    default: view = AnyView(base.background(.background))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewLabelsHidden")
public func SUIViewLabelsHidden(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.labelsHidden())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewLineLimit")
public func SUIViewLineLimit(_ viewRef: UnsafeMutableRawPointer, _ limit: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    if limit <= 0 {
        view = AnyView(base.lineLimit(nil))
    } else {
        view = AnyView(base.lineLimit(Int(limit)))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewTextFieldStyle")
public func SUIViewTextFieldStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 0: view = AnyView(base.textFieldStyle(.automatic))
    case 1: view = AnyView(base.textFieldStyle(.roundedBorder))
    case 2: view = AnyView(base.textFieldStyle(.plain))
    default: view = AnyView(base.textFieldStyle(.automatic))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Font constructors

@_cdecl("SUIFontSystem")
public func SUIFontSystem(_ size: Double) -> UnsafeMutableRawPointer {
    let font = Font.system(size: size)
    return Unmanaged.passRetained(Box(font)).toOpaque()
}

@_cdecl("SUIFontSystemDesign")
public func SUIFontSystemDesign(_ size: Double, _ weight: Int32, _ design: Int32) -> UnsafeMutableRawPointer {
    let w: Font.Weight
    switch weight {
    case 0: w = .ultraLight
    case 1: w = .thin
    case 2: w = .light
    case 3: w = .regular
    case 4: w = .medium
    case 5: w = .semibold
    case 6: w = .bold
    case 7: w = .heavy
    case 8: w = .black
    default: w = .regular
    }
    let d: Font.Design
    switch design {
    case 0: d = .default
    case 1: d = .rounded
    case 2: d = .monospaced
    case 3: d = .serif
    default: d = .default
    }
    let font = Font.system(size: size, weight: w, design: d)
    return Unmanaged.passRetained(Box(font)).toOpaque()
}

@_cdecl("SUIFontNamed")
public func SUIFontNamed(_ name: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let fontName = String(cString: name)
    let font: Font
    switch fontName {
    case "largeTitle": font = .largeTitle
    case "title": font = .title
    case "title2": font = .title2
    case "title3": font = .title3
    case "headline": font = .headline
    case "subheadline": font = .subheadline
    case "body": font = .body
    case "callout": font = .callout
    case "footnote": font = .footnote
    case "caption": font = .caption
    case "caption2": font = .caption2
    default: font = .body
    }
    return Unmanaged.passRetained(Box(font)).toOpaque()
}

@_cdecl("SUIViewAnimation")
public func SUIViewAnimation(_ viewRef: UnsafeMutableRawPointer, _ kind: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch kind {
    case 0: view = AnyView(base.animation(.easeInOut, value: true))
    case 1: view = AnyView(base.animation(.easeIn, value: true))
    case 2: view = AnyView(base.animation(.easeOut, value: true))
    case 3: view = AnyView(base.animation(.spring, value: true))
    case 4: view = AnyView(base.animation(.bouncy, value: true))
    default: view = AnyView(base.animation(.default, value: true))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Additional modifiers

@_cdecl("SUIViewShadow")
public func SUIViewShadow(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double, _ radius: Double, _ x: Double, _ y: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.shadow(color: color, radius: radius, x: x, y: y))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBorder")
public func SUIViewBorder(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double, _ width: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.border(color, width: width))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewCornerRadius")
public func SUIViewCornerRadius(_ viewRef: UnsafeMutableRawPointer, _ radius: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.clipShape(RoundedRectangle(cornerRadius: radius)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewScaleEffect")
public func SUIViewScaleEffect(_ viewRef: UnsafeMutableRawPointer, _ scale: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.scaleEffect(scale))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewRotationEffect")
public func SUIViewRotationEffect(_ viewRef: UnsafeMutableRawPointer, _ degrees: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.rotationEffect(.degrees(degrees)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOffset")
public func SUIViewOffset(_ viewRef: UnsafeMutableRawPointer, _ x: Double, _ y: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.offset(x: x, y: y))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewAllowsHitTesting")
public func SUIViewAllowsHitTesting(_ viewRef: UnsafeMutableRawPointer, _ enabled: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.allowsHitTesting(enabled != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOnTapGesture")
public func SUIViewOnTapGesture(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onTapGesture {
        _SUIButtonCallback?(id)
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFocusable")
public func SUIViewFocusable(_ viewRef: UnsafeMutableRawPointer, _ focusable: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.focusable(focusable != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
private struct BridgedFocusedView: View {
    let base: AnyView
    let state: BridgedBoolState
    @FocusState private var focused: Bool

    var body: some View {
        base
            .focused($focused)
            .onAppear {
                focused = state.value
            }
            .onChange(of: focused) { _, newValue in
                if state.value != newValue {
                    state.setAndBump(newValue)
                }
            }
            .onChange(of: state.value) { _, newValue in
                if focused != newValue {
                    focused = newValue
                }
            }
    }
}

@_cdecl("SUIViewFocused")
@MainActor
public func SUIViewFocused(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedBoolState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedFocusedView(base: base, state: state))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFocusSection")
@MainActor
public func SUIViewFocusSection(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.focusSection())
    return retainDerivedView(from: viewRef, view)
}

@_cdecl("SUIViewFocusScopeID")
@MainActor
public func SUIViewFocusScopeID(
    _ viewRef: UnsafeMutableRawPointer,
    _ namespaceRef: UnsafeMutableRawPointer
) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let namespace = Unmanaged<Box<Namespace.ID>>.fromOpaque(namespaceRef).takeUnretainedValue().value
    let view = AnyView(base.focusScope(namespace))
    return retainDerivedView(from: viewRef, view)
}

@_cdecl("SUIViewPrefersDefaultFocus")
@MainActor
public func SUIViewPrefersDefaultFocus(
    _ viewRef: UnsafeMutableRawPointer,
    _ preferred: Int32,
    _ namespaceRef: UnsafeMutableRawPointer
) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let namespace = Unmanaged<Box<Namespace.ID>>.fromOpaque(namespaceRef).takeUnretainedValue().value
    let view = AnyView(base.prefersDefaultFocus(preferred != 0, in: namespace))
    return retainDerivedView(from: viewRef, view)
}

@_cdecl("SUIViewNavigationTitle")
public func SUIViewNavigationTitle(_ viewRef: UnsafeMutableRawPointer, _ titlePtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let title = String(cString: titlePtr)
    let view = AnyView(base.navigationTitle(title))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewNavigationSplitViewStyle")
@MainActor
public func SUIViewNavigationSplitViewStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 1:
        view = AnyView(base.navigationSplitViewStyle(.balanced))
    case 2:
        view = AnyView(base.navigationSplitViewStyle(.prominentDetail))
    default:
        view = AnyView(base.navigationSplitViewStyle(.automatic))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewMenuButtonStyle")
@MainActor
public func SUIViewMenuButtonStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 1:
        view = AnyView(base.menuButtonStyle(PullDownMenuButtonStyle()))
    case 2:
        view = AnyView(base.menuButtonStyle(BorderlessPullDownMenuButtonStyle()))
    case 3:
        view = AnyView(base.menuButtonStyle(BorderlessButtonMenuButtonStyle()))
    case 4:
        view = AnyView(base.menuButtonStyle(_TexturedPullDownMenuButtonStyle()))
    default:
        view = AnyView(base.menuButtonStyle(DefaultMenuButtonStyle()))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewNavigationViewStyle")
@MainActor
public func SUIViewNavigationViewStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 1:
        view = AnyView(base.navigationViewStyle(.columns))
    case 2:
        view = AnyView(base.navigationViewStyle(.columns))
    case 3:
        view = AnyView(base.navigationViewStyle(.columns))
    default:
        view = AnyView(base.navigationViewStyle(.automatic))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUISectionCollapsible")
@MainActor
public func SUISectionCollapsible(_ viewRef: UnsafeMutableRawPointer, _ collapsible: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.disclosureGroupStyle(.automatic))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUINavigationLinkIsDetailLink")
public func SUINavigationLinkIsDetailLink(_ viewRef: UnsafeMutableRawPointer, _ isDetailLink: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    // isDetailLink was removed in modern SwiftUI; return base view unchanged.
    return Unmanaged.passRetained(Box(base)).toOpaque()
}

@_cdecl("SUIViewTabItem")
public func SUIViewTabItem(_ viewRef: UnsafeMutableRawPointer, _ labelPtr: UnsafePointer<CChar>, _ systemImagePtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let label = String(cString: labelPtr)
    let img = String(cString: systemImagePtr)
    let view = AnyView(base.tabItem { Label(label, systemImage: img) })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewTag")
public func SUIViewTag(_ viewRef: UnsafeMutableRawPointer, _ tag: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.tag(Int(tag)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewID")
public func SUIViewID(_ viewRef: UnsafeMutableRawPointer, _ id: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.id(Int(id)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewDefaultScrollAnchor")
public func SUIViewDefaultScrollAnchor(_ viewRef: UnsafeMutableRawPointer, _ anchor: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.defaultScrollAnchor(suiScrollAnchorUnitPoint(anchor)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewScrollTargetBehavior")
public func SUIViewScrollTargetBehavior(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch behavior {
    case 1:
        view = AnyView(base.scrollTargetBehavior(.viewAligned))
    default:
        view = AnyView(base.scrollTargetBehavior(.paging))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewScrollTargetLayout")
public func SUIViewScrollTargetLayout(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.scrollTargetLayout())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewScrollBounceBehavior")
public func SUIViewScrollBounceBehavior(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32, _ axis: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.scrollBounceBehavior(suiScrollBounceBehavior(behavior), axes: suiAxisSet(axis)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewScrollContentBackgroundHidden")
public func SUIViewScrollContentBackgroundHidden(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.scrollContentBackground(.hidden))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewToolbarRole")
public func SUIViewToolbarRole(_ viewRef: UnsafeMutableRawPointer, _ role: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.toolbarRole(suiToolbarRole(role)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewToolbarItem")
public func SUIViewToolbarItem(_ viewRef: UnsafeMutableRawPointer, _ placement: Int32, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let content = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(base.toolbar {
        ToolbarItem(placement: suiToolbarItemPlacement(placement)) {
            content
        }
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewKeyboardShortcut")
public func SUIViewKeyboardShortcut(_ viewRef: UnsafeMutableRawPointer, _ keyPtr: UnsafePointer<CChar>, _ modifiers: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.keyboardShortcut(suiKeyEquivalent(keyPtr), modifiers: suiEventModifiers(modifiers)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewSearchable")
@MainActor
public func SUIViewSearchable(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ promptPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedStringState>.fromOpaque(stateRef).takeUnretainedValue()
    let prompt = String(cString: promptPtr)
    let view = AnyView(base.searchable(text: suiStringBinding(state), prompt: Text(prompt)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewPointerStyle")
public func SUIViewPointerStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.pointerStyle(suiPointerStyle(style)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewSubmitLabel")
@MainActor
public func SUIViewSubmitLabel(_ viewRef: UnsafeMutableRawPointer, _ label: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch label {
    case 1:
        view = AnyView(base.submitLabel(.done))
    case 2:
        view = AnyView(base.submitLabel(.go))
    case 3:
        view = AnyView(base.submitLabel(.send))
    case 4:
        view = AnyView(base.submitLabel(.join))
    case 5:
        view = AnyView(base.submitLabel(.continue))
    case 6:
        view = AnyView(base.submitLabel(.next))
    case 7:
        view = AnyView(base.submitLabel(.search))
    case 8:
        view = AnyView(base.submitLabel(.route))
    default:
        view = AnyView(base.submitLabel(.return))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFill")
public func SUIViewFill(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    if let shape = shapeForViewRef(viewRef) {
        return retainView(AnyView(shape.fill(color)))
    }
    let view = AnyView(color.mask(base))
    return retainView(view)
}

@_cdecl("SUIViewStroke")
public func SUIViewStroke(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double, _ lineWidth: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    if let shape = shapeForViewRef(viewRef) {
        return retainView(AnyView(shape.stroke(color, lineWidth: lineWidth)))
    }
    let view = AnyView(base.overlay(
        RoundedRectangle(cornerRadius: 0).stroke(color, lineWidth: lineWidth)
    ))
    return retainView(view)
}

// SUIViewShapeStrokeStyle extends SUIViewStroke with a StrokeStyle so the
// caller can supply a dash pattern. The dash operand is a length-prefixed
// f64 array packed into a little-endian byte blob (one byte for count,
// followed by count * 8 bytes of IEEE-754 f64). This matches the dash
// encoding used by the Canvas opcode stream so Go can reuse one writer.
@_cdecl("SUIViewShapeStrokeStyle")
public func SUIViewShapeStrokeStyle(
    _ viewRef: UnsafeMutableRawPointer,
    _ r: Double, _ g: Double, _ b: Double, _ a: Double,
    _ lineWidth: Double,
    _ dashPtr: UnsafePointer<UInt8>?,
    _ dashLen: Int32
) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    var dashes: [CGFloat] = []
    if let dashPtr, dashLen > 0 {
        var reader = SUIModifierReader(dashPtr, Int(dashLen))
        if let n = reader.readU8() {
            dashes.reserveCapacity(Int(n))
            for _ in 0..<Int(n) {
                guard let d = reader.readF64() else { break }
                dashes.append(CGFloat(d))
            }
        }
    }
    let style = StrokeStyle(lineWidth: lineWidth, dash: dashes)
    if let shape = shapeForViewRef(viewRef) {
        return retainView(AnyView(shape.stroke(color, style: style)))
    }
    let view = AnyView(base.overlay(
        RoundedRectangle(cornerRadius: 0).stroke(color, style: style)
    ))
    return retainView(view)
}

// MARK: - Lifecycle and interaction modifiers

@_cdecl("SUIViewOnAppear")
public func SUIViewOnAppear(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onAppear { _SUIButtonCallback?(id) })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOnDisappear")
public func SUIViewOnDisappear(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onDisappear { _SUIButtonCallback?(id) })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewRefreshable")
@MainActor
public func SUIViewRefreshable(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.refreshable {
        _SUIButtonCallback?(id)
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewDraggableText")
public func SUIViewDraggableText(_ viewRef: UnsafeMutableRawPointer, _ textPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let text = String(cString: textPtr)
    let view = AnyView(base.draggable(text))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewDraggableURL")
public func SUIViewDraggableURL(_ viewRef: UnsafeMutableRawPointer, _ urlPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let urlString = String(cString: urlPtr)
    let payload = URL(string: urlString) ?? URL(fileURLWithPath: urlString)
    let view = AnyView(base.draggable(payload))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewDraggableFileURL")
public func SUIViewDraggableFileURL(_ viewRef: UnsafeMutableRawPointer, _ pathPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let path = String(cString: pathPtr)
    let view = AnyView(base.draggable(URL(fileURLWithPath: path)))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewDropDestinationText")
@MainActor
public func SUIViewDropDestinationText(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.dropDestination(for: String.self) { values, _ in
        guard let value = values.first else {
            return false
        }
        return value.withCString { ptr in
            _SUIStringCallback?(id, ptr) != 0
        }
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewDropDestinationURL")
@MainActor
public func SUIViewDropDestinationURL(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.dropDestination(for: URL.self) { values, _ in
        guard let value = values.first else {
            return false
        }
        return value.absoluteString.withCString { ptr in
            _SUIStringCallback?(id, ptr) != 0
        }
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewDropDestinationFileURL")
@MainActor
public func SUIViewDropDestinationFileURL(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.dropDestination(for: URL.self) { values, _ in
        guard let value = values.first, value.isFileURL else {
            return false
        }
        return value.path.withCString { ptr in
            _SUIStringCallback?(id, ptr) != 0
        }
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOnHover")
public func SUIViewOnHover(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onHover { _ in _SUIButtonCallback?(id) })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOnHoverPhase")
public func SUIViewOnHoverPhase(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onHover { inside in
        _SUIBoolCallback?(id, inside ? 1 : 0)
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewOnHoverLocation")
public func SUIViewOnHoverLocation(_ viewRef: UnsafeMutableRawPointer, _ callbackID: UInt) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let id = callbackID
    let view = AnyView(base.onContinuousHover(coordinateSpace: .local) { phase in
        switch phase {
        case .active(let location):
            _SUIHoverCallback?(id, 1, location.x, location.y)
        case .ended:
            _SUIHoverCallback?(id, 0, 0, 0)
        }
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewTint")
public func SUIViewTint(_ viewRef: UnsafeMutableRawPointer, _ r: Double, _ g: Double, _ b: Double, _ a: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let color = Color(red: r, green: g, blue: b, opacity: a)
    let view = AnyView(base.tint(color))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFixedSize")
public func SUIViewFixedSize(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.fixedSize())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewFixedSizeAxis")
public func SUIViewFixedSizeAxis(_ viewRef: UnsafeMutableRawPointer, _ horizontal: Int32, _ vertical: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.fixedSize(horizontal: horizontal != 0, vertical: vertical != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewAspectRatio")
public func SUIViewAspectRatio(_ viewRef: UnsafeMutableRawPointer, _ ratio: Double, _ contentMode: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let mode: ContentMode = contentMode == 1 ? .fill : .fit
    let view = AnyView(base.aspectRatio(ratio, contentMode: mode))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewSafeAreaInset")
@MainActor
public func SUIViewSafeAreaInset(_ viewRef: UnsafeMutableRawPointer, _ edge: Int32, _ spacing: Double, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let inset = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let edgeSet = Edge.Set(rawValue: Int8(edge))
    let resolvedEdge: VerticalEdge
    if edgeSet.contains(.top) {
        resolvedEdge = .top
    } else {
        resolvedEdge = .bottom
    }
    let view = AnyView(base.safeAreaInset(edge: resolvedEdge, spacing: spacing) {
        inset
    })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewSheet")
@MainActor
public func SUIViewSheet(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let sheetContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(BridgedSheetView(base: base, state: state, sheetContent: sheetContent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedSheetView: View {
    let base: AnyView
    var state: BridgedIntState
    let sheetContent: AnyView

    var body: some View {
        base.sheet(isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.setAndBump(0) } }
        )) {
            sheetContent
        }
    }
}

@_cdecl("SUIViewAlert")
@MainActor
public func SUIViewAlert(_ viewRef: UnsafeMutableRawPointer, _ titlePtr: UnsafePointer<CChar>, _ messagePtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let title = String(cString: titlePtr)
    let message = String(cString: messagePtr)
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedAlertView(base: base, title: title, message: message, state: state))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedAlertView: View {
    let base: AnyView
    let title: String
    let message: String
    var state: BridgedIntState

    var body: some View {
        base.alert(title, isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.setAndBump(0) } }
        )) {
            Button("OK") {}
        } message: {
            Text(message)
        }
    }
}

@_cdecl("SUIViewConfirmationDialog")
@MainActor
public func SUIViewConfirmationDialog(_ viewRef: UnsafeMutableRawPointer, _ titlePtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ actionsRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let title = String(cString: titlePtr)
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let actions = Unmanaged<Box<AnyView>>.fromOpaque(actionsRef).takeUnretainedValue().value
    let view = AnyView(BridgedConfirmationDialogView(base: base, title: title, state: state, actions: actions))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedConfirmationDialogView: View {
    let base: AnyView
    let title: String
    var state: BridgedIntState
    let actions: AnyView

    var body: some View {
        base.confirmationDialog(title, isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.setAndBump(0) } }
        )) {
            actions
        }
    }
}

@_cdecl("SUIViewContextMenu")
public func SUIViewContextMenu(_ viewRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let menuContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(base.contextMenu { menuContent })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Text appearance modifiers

@_cdecl("SUIViewBold")
public func SUIViewBold(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.bold())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewItalic")
public func SUIViewItalic(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.italic())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewUnderline")
public func SUIViewUnderline(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.underline())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewStrikethrough")
public func SUIViewStrikethrough(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.strikethrough())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewTruncationMode")
public func SUIViewTruncationMode(_ viewRef: UnsafeMutableRawPointer, _ mode: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let m: Text.TruncationMode
    switch mode {
    case 0: m = .head
    case 1: m = .middle
    case 2: m = .tail
    default: m = .tail
    }
    let view = AnyView(base.truncationMode(m))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewSymbolRenderingMode")
public func SUIViewSymbolRenderingMode(_ viewRef: UnsafeMutableRawPointer, _ mode: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let m: SymbolRenderingMode
    switch mode {
    case 0: m = .monochrome
    case 1: m = .hierarchical
    case 2: m = .palette
    case 3: m = .multicolor
    default: m = .monochrome
    }
    let view = AnyView(base.symbolRenderingMode(m))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Layout modifiers

@_cdecl("SUIViewZIndex")
public func SUIViewZIndex(_ viewRef: UnsafeMutableRawPointer, _ index: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.zIndex(index))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewLayoutPriority")
public func SUIViewLayoutPriority(_ viewRef: UnsafeMutableRawPointer, _ priority: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.layoutPriority(priority))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewBlur")
public func SUIViewBlur(_ viewRef: UnsafeMutableRawPointer, _ radius: Double) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.blur(radius: radius))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewClipped")
public func SUIViewClipped(_ viewRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.clipped())
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewMask")
public func SUIViewMask(_ viewRef: UnsafeMutableRawPointer, _ maskRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let maskView = Unmanaged<Box<AnyView>>.fromOpaque(maskRef).takeUnretainedValue().value
    let view = AnyView(base.mask { maskView })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Accessibility modifiers

@_cdecl("SUIViewAccessibilityLabel")
public func SUIViewAccessibilityLabel(_ viewRef: UnsafeMutableRawPointer, _ labelPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let label = String(cString: labelPtr)
    let view = AnyView(base.accessibilityLabel(label))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewAccessibilityHint")
public func SUIViewAccessibilityHint(_ viewRef: UnsafeMutableRawPointer, _ hintPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let hint = String(cString: hintPtr)
    let view = AnyView(base.accessibilityHint(hint))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewAccessibilityValue")
public func SUIViewAccessibilityValue(_ viewRef: UnsafeMutableRawPointer, _ valuePtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let value = String(cString: valuePtr)
    let view = AnyView(base.accessibilityValue(value))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewAccessibilityHidden")
public func SUIViewAccessibilityHidden(_ viewRef: UnsafeMutableRawPointer, _ hidden: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view = AnyView(base.accessibilityHidden(hidden != 0))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

private struct SUIAccessibilityRotorPayload: Decodable {
    struct Entry: Decodable, Hashable {
        let id: String
        let label: String
    }

    let name: String
    let entries: [Entry]
}

@_cdecl("SUIViewAccessibilityRotor")
public func SUIViewAccessibilityRotor(_ viewRef: UnsafeMutableRawPointer, _ modelPtr: UnsafePointer<CChar>) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let payload = String(cString: modelPtr)
    guard let data = payload.data(using: .utf8),
          let model = try? JSONDecoder().decode(SUIAccessibilityRotorPayload.self, from: data),
          !model.name.isEmpty,
          !model.entries.isEmpty else {
        return Unmanaged.passRetained(Box(base)).toOpaque()
    }
    let view = AnyView(base.accessibilityRotor(LocalizedStringKey(model.name), entries: model.entries, entryID: \.id, entryLabel: \.label))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - List modifiers

@_cdecl("SUIViewListStyle")
public func SUIViewListStyle(_ viewRef: UnsafeMutableRawPointer, _ style: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let view: AnyView
    switch style {
    case 0: view = AnyView(base.listStyle(.automatic))
    case 1: view = AnyView(base.listStyle(.sidebar))
    case 2: view = AnyView(base.listStyle(.inset))
    case 3: view = AnyView(base.listStyle(.plain))
    default: view = AnyView(base.listStyle(.automatic))
    }
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewListRowBackground")
public func SUIViewListRowBackground(_ viewRef: UnsafeMutableRawPointer, _ bgRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let bg = Unmanaged<Box<AnyView>>.fromOpaque(bgRef).takeUnretainedValue().value
    let view = AnyView(base.listRowBackground(bg))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewBackForwardNavigationGestures")
@MainActor
public func SUIViewWebViewBackForwardNavigationGestures(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let mode: WebView.BackForwardNavigationGesturesBehavior
    switch behavior {
    case 1: mode = .enabled
    case 2: mode = .disabled
    default: mode = .automatic
    }
    let view = AnyView(base.webViewBackForwardNavigationGestures(mode))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewContentBackground")
@MainActor
public func SUIViewWebViewContentBackground(_ viewRef: UnsafeMutableRawPointer, _ visibility: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let mode: Visibility
    switch visibility {
    case 1: mode = .visible
    case 2: mode = .hidden
    default: mode = .automatic
    }
    let view = AnyView(base.webViewContentBackground(mode))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewElementFullscreenBehavior")
@MainActor
public func SUIViewWebViewElementFullscreenBehavior(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let mode: WebView.ElementFullscreenBehavior
    switch behavior {
    case 1: mode = .enabled
    case 2: mode = .disabled
    default: mode = .automatic
    }
    let view = AnyView(base.webViewElementFullscreenBehavior(mode))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewLinkPreviews")
@MainActor
public func SUIViewWebViewLinkPreviews(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let mode: WebView.LinkPreviewBehavior
    switch behavior {
    case 1: mode = .enabled
    case 2: mode = .disabled
    default: mode = .automatic
    }
    let view = AnyView(base.webViewLinkPreviews(mode))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewMagnificationGestures")
@MainActor
public func SUIViewWebViewMagnificationGestures(_ viewRef: UnsafeMutableRawPointer, _ behavior: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let mode: WebView.MagnificationGesturesBehavior
    switch behavior {
    case 1: mode = .enabled
    case 2: mode = .disabled
    default: mode = .automatic
    }
    let view = AnyView(base.webViewMagnificationGestures(mode))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@_cdecl("SUIViewWebViewTextSelection")
@MainActor
public func SUIViewWebViewTextSelection(_ viewRef: UnsafeMutableRawPointer, _ enabled: Int32) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let mode: TextSelectability = enabled != 0 ? .enabled : .disabled
    let view = AnyView(base.webViewTextSelection(mode))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - Presentation modifiers

@_cdecl("SUIViewPopover")
@MainActor
public func SUIViewPopover(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let popoverContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(BridgedPopoverView(base: base, state: state, popoverContent: popoverContent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedPopoverView: View {
    let base: AnyView
    var state: BridgedIntState
    let popoverContent: AnyView

    var body: some View {
        base.popover(isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.setAndBump(0) } }
        )) {
            popoverContent
        }
    }
}

@_cdecl("SUIViewFullScreenCover")
@MainActor
public func SUIViewFullScreenCover(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedIntState>.fromOpaque(stateRef).takeUnretainedValue()
    let coverContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(BridgedFullScreenCoverView(base: base, state: state, coverContent: coverContent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedFullScreenCoverView: View {
    let base: AnyView
    var state: BridgedIntState
    let coverContent: AnyView

    var body: some View {
        // fullScreenCover is iOS-only; use sheet on macOS.
        #if os(iOS)
        base.fullScreenCover(isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.setAndBump(0) } }
        )) {
            coverContent
        }
        #else
        base.sheet(isPresented: Binding(
            get: { state.value != 0 },
            set: { if !$0 { state.setAndBump(0) } }
        )) {
            coverContent
        }
        #endif
    }
}

@_cdecl("SUIViewSheetBool")
@MainActor
public func SUIViewSheetBool(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedBoolState>.fromOpaque(stateRef).takeUnretainedValue()
    let sheetContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(BridgedSheetBoolView(base: base, state: state, sheetContent: sheetContent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedSheetBoolView: View {
    let base: AnyView
    var state: BridgedBoolState
    let sheetContent: AnyView

    var body: some View {
        base.sheet(isPresented: suiBoolBinding(state)) {
            sheetContent
        }
    }
}

@_cdecl("SUIViewAlertBool")
@MainActor
public func SUIViewAlertBool(_ viewRef: UnsafeMutableRawPointer, _ titlePtr: UnsafePointer<CChar>, _ messagePtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let title = String(cString: titlePtr)
    let message = String(cString: messagePtr)
    let state = Unmanaged<BridgedBoolState>.fromOpaque(stateRef).takeUnretainedValue()
    let view = AnyView(BridgedAlertBoolView(base: base, title: title, message: message, state: state))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedAlertBoolView: View {
    let base: AnyView
    let title: String
    let message: String
    var state: BridgedBoolState

    var body: some View {
        base.alert(title, isPresented: suiBoolBinding(state)) {
            Button("OK") {}
        } message: {
            Text(message)
        }
    }
}

@_cdecl("SUIViewConfirmationDialogBool")
@MainActor
public func SUIViewConfirmationDialogBool(_ viewRef: UnsafeMutableRawPointer, _ titlePtr: UnsafePointer<CChar>, _ stateRef: UnsafeMutableRawPointer, _ actionsRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let title = String(cString: titlePtr)
    let state = Unmanaged<BridgedBoolState>.fromOpaque(stateRef).takeUnretainedValue()
    let actions = Unmanaged<Box<AnyView>>.fromOpaque(actionsRef).takeUnretainedValue().value
    let view = AnyView(BridgedConfirmationDialogBoolView(base: base, title: title, state: state, actions: actions))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedConfirmationDialogBoolView: View {
    let base: AnyView
    let title: String
    var state: BridgedBoolState
    let actions: AnyView

    var body: some View {
        base.confirmationDialog(title, isPresented: suiBoolBinding(state)) {
            actions
        }
    }
}

@_cdecl("SUIViewPopoverBool")
@MainActor
public func SUIViewPopoverBool(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedBoolState>.fromOpaque(stateRef).takeUnretainedValue()
    let popoverContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(BridgedPopoverBoolView(base: base, state: state, popoverContent: popoverContent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedPopoverBoolView: View {
    let base: AnyView
    var state: BridgedBoolState
    let popoverContent: AnyView

    var body: some View {
        base.popover(isPresented: suiBoolBinding(state)) {
            popoverContent
        }
    }
}

@_cdecl("SUIViewFullScreenCoverBool")
@MainActor
public func SUIViewFullScreenCoverBool(_ viewRef: UnsafeMutableRawPointer, _ stateRef: UnsafeMutableRawPointer, _ contentRef: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let base = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    let state = Unmanaged<BridgedBoolState>.fromOpaque(stateRef).takeUnretainedValue()
    let coverContent = Unmanaged<Box<AnyView>>.fromOpaque(contentRef).takeUnretainedValue().value
    let view = AnyView(BridgedFullScreenCoverBoolView(base: base, state: state, coverContent: coverContent))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

@MainActor
struct BridgedFullScreenCoverBoolView: View {
    let base: AnyView
    var state: BridgedBoolState
    let coverContent: AnyView

    var body: some View {
        #if os(iOS)
        base.fullScreenCover(isPresented: suiBoolBinding(state)) {
            coverContent
        }
        #else
        base.sheet(isPresented: suiBoolBinding(state)) {
            coverContent
        }
        #endif
    }
}

// MARK: - Packed modifier chain (SUIApplyModifiers)
//
// Wire format (little-endian):
//   [count: UInt32]
//   [ [kind: UInt32] [payload_len: UInt32] [payload: payload_len bytes] ]*count
//
// Kind payloads:
//   1 padding              : Double amount
//   2 paddingEdge          : Int32 edges, Double amount
//   3 opacity              : Double
//   4 foregroundRGBA       : 4 Doubles r,g,b,a
//   5 backgroundRGBA       : 4 Doubles r,g,b,a
//   6 tintRGBA             : 4 Doubles r,g,b,a
//   7 disabled             : UInt8 (0/1)
//   8 bold                 : empty
//   9 italic               : empty
//  10 underline            : empty
//  11 strikethrough        : empty
//  12 clipped              : empty
//  13 monospacedDigit      : empty
//  14 labelsHidden         : empty
//  15 blur                 : Double radius
//  16 cornerRadius         : Double radius
//  17 scaleEffect          : Double scale
//  18 rotationEffect       : Double degrees
//  19 zIndex               : Double
//  20 layoutPriority       : Double
//  21 frame                : 2 Doubles w,h
//  22 maxFrame             : 2 Doubles maxW, maxH
//  23 fontWeight           : Int32
//  24 fontDesign           : Int32
//  25 imageScale           : Int32
//  26 controlSize          : Int32
//  27 buttonStyle          : Int32
//  28 toggleStyle          : Int32
//  29 multilineTextAlignment: Int32
//  30 truncationMode       : Int32
//  31 fixedSize            : empty
//
// Unknown kinds are rejected (the call becomes a no-op and the original view
// ref is returned with its retain unchanged). This matches the P4 discipline
// of failing loudly rather than silently dropping modifiers. Per-modifier
// @_cdecl entries remain available for backward compatibility.
private let suiModifierWireKindPadding: UInt32 = 1
private let suiModifierWireKindPaddingEdge: UInt32 = 2
private let suiModifierWireKindOpacity: UInt32 = 3
private let suiModifierWireKindForegroundRGBA: UInt32 = 4
private let suiModifierWireKindBackgroundRGBA: UInt32 = 5
private let suiModifierWireKindTintRGBA: UInt32 = 6
private let suiModifierWireKindDisabled: UInt32 = 7
private let suiModifierWireKindBold: UInt32 = 8
private let suiModifierWireKindItalic: UInt32 = 9
private let suiModifierWireKindUnderline: UInt32 = 10
private let suiModifierWireKindStrikethrough: UInt32 = 11
private let suiModifierWireKindClipped: UInt32 = 12
private let suiModifierWireKindMonospacedDigit: UInt32 = 13
private let suiModifierWireKindLabelsHidden: UInt32 = 14
private let suiModifierWireKindBlur: UInt32 = 15
private let suiModifierWireKindCornerRadius: UInt32 = 16
private let suiModifierWireKindScaleEffect: UInt32 = 17
private let suiModifierWireKindRotationEffect: UInt32 = 18
private let suiModifierWireKindZIndex: UInt32 = 19
private let suiModifierWireKindLayoutPriority: UInt32 = 20
private let suiModifierWireKindFrame: UInt32 = 21
private let suiModifierWireKindMaxFrame: UInt32 = 22
private let suiModifierWireKindFontWeight: UInt32 = 23
private let suiModifierWireKindFontDesign: UInt32 = 24
private let suiModifierWireKindImageScale: UInt32 = 25
private let suiModifierWireKindControlSize: UInt32 = 26
private let suiModifierWireKindButtonStyle: UInt32 = 27
private let suiModifierWireKindToggleStyle: UInt32 = 28
private let suiModifierWireKindTextAlignment: UInt32 = 29
private let suiModifierWireKindTruncationMode: UInt32 = 30
private let suiModifierWireKindFixedSize: UInt32 = 31

// Shared across bridge_modifiers.gen.swift (packed modifier chains) and
// bridge_views.gen.swift (Path/Canvas opcode decoder). Access level is
// module-internal so both files can decode little-endian wire payloads.
struct SUIModifierReader {
    let buffer: UnsafeBufferPointer<UInt8>
    var offset: Int = 0

    init(_ ptr: UnsafePointer<UInt8>?, _ length: Int) {
        if let ptr, length > 0 {
            self.buffer = UnsafeBufferPointer(start: ptr, count: length)
        } else {
            self.buffer = UnsafeBufferPointer(start: nil, count: 0)
        }
    }

    var remaining: Int { buffer.count - offset }

    mutating func readU32() -> UInt32? {
        guard remaining >= 4 else { return nil }
        let b0 = UInt32(buffer[offset])
        let b1 = UInt32(buffer[offset + 1])
        let b2 = UInt32(buffer[offset + 2])
        let b3 = UInt32(buffer[offset + 3])
        offset += 4
        return (b3 << 24) | (b2 << 16) | (b1 << 8) | b0
    }

    mutating func readU8() -> UInt8? {
        guard remaining >= 1 else { return nil }
        let v = buffer[offset]
        offset += 1
        return v
    }

    mutating func readI32() -> Int32? {
        guard let u = readU32() else { return nil }
        return Int32(bitPattern: u)
    }

    mutating func readF64() -> Double? {
        guard remaining >= 8 else { return nil }
        var bits: UInt64 = 0
        for i in 0..<8 {
            bits |= UInt64(buffer[offset + i]) << (UInt64(i) * 8)
        }
        offset += 8
        return Double(bitPattern: bits)
    }
}

enum SUIModifierDecodeError: Error {
    case truncated
    case unknownKind(UInt32)
}

private func suiApplyPackedModifier(_ base: AnyView, kind: UInt32, payload: UnsafePointer<UInt8>?, payloadLen: Int) throws -> AnyView {
    var reader = SUIModifierReader(payload, payloadLen)
    switch kind {
    case suiModifierWireKindPadding:
        guard let amount = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.padding(amount))
    case suiModifierWireKindPaddingEdge:
        guard let edges = reader.readI32(), let amount = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        let edgeSet = Edge.Set(rawValue: Int8(edges))
        return AnyView(base.padding(edgeSet, amount))
    case suiModifierWireKindOpacity:
        guard let opacity = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.opacity(opacity))
    case suiModifierWireKindForegroundRGBA:
        guard let r = reader.readF64(), let g = reader.readF64(), let b = reader.readF64(), let a = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.foregroundStyle(Color(red: r, green: g, blue: b, opacity: a)))
    case suiModifierWireKindBackgroundRGBA:
        guard let r = reader.readF64(), let g = reader.readF64(), let b = reader.readF64(), let a = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.background(Color(red: r, green: g, blue: b, opacity: a)))
    case suiModifierWireKindTintRGBA:
        guard let r = reader.readF64(), let g = reader.readF64(), let b = reader.readF64(), let a = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.tint(Color(red: r, green: g, blue: b, opacity: a)))
    case suiModifierWireKindDisabled:
        guard let v = reader.readU8() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.disabled(v != 0))
    case suiModifierWireKindBold:
        return AnyView(base.bold())
    case suiModifierWireKindItalic:
        return AnyView(base.italic())
    case suiModifierWireKindUnderline:
        return AnyView(base.underline())
    case suiModifierWireKindStrikethrough:
        return AnyView(base.strikethrough())
    case suiModifierWireKindClipped:
        return AnyView(base.clipped())
    case suiModifierWireKindMonospacedDigit:
        return AnyView(base.monospacedDigit())
    case suiModifierWireKindLabelsHidden:
        return AnyView(base.labelsHidden())
    case suiModifierWireKindBlur:
        guard let r = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.blur(radius: r))
    case suiModifierWireKindCornerRadius:
        guard let r = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.cornerRadius(r))
    case suiModifierWireKindScaleEffect:
        guard let s = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.scaleEffect(s))
    case suiModifierWireKindRotationEffect:
        guard let d = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.rotationEffect(.degrees(d)))
    case suiModifierWireKindZIndex:
        guard let z = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.zIndex(z))
    case suiModifierWireKindLayoutPriority:
        guard let p = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.layoutPriority(p))
    case suiModifierWireKindFrame:
        guard let w = reader.readF64(), let h = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        return AnyView(base.frame(width: w, height: h))
    case suiModifierWireKindMaxFrame:
        guard let mw = reader.readF64(), let mh = reader.readF64() else { throw SUIModifierDecodeError.truncated }
        var w: CGFloat? = nil
        if mw < 0 { w = .infinity } else if mw > 0 { w = CGFloat(mw) }
        var h: CGFloat? = nil
        if mh < 0 { h = .infinity } else if mh > 0 { h = CGFloat(mh) }
        return AnyView(base.frame(maxWidth: w, maxHeight: h))
    case suiModifierWireKindFontWeight:
        guard let raw = reader.readI32() else { throw SUIModifierDecodeError.truncated }
        let w: Font.Weight
        switch raw {
        case 0: w = .ultraLight
        case 1: w = .thin
        case 2: w = .light
        case 3: w = .regular
        case 4: w = .medium
        case 5: w = .semibold
        case 6: w = .bold
        case 7: w = .heavy
        case 8: w = .black
        default: w = .regular
        }
        return AnyView(base.fontWeight(w))
    case suiModifierWireKindFontDesign:
        guard let raw = reader.readI32() else { throw SUIModifierDecodeError.truncated }
        let d: Font.Design
        switch raw {
        case 0: d = .default
        case 1: d = .rounded
        case 2: d = .monospaced
        case 3: d = .serif
        default: d = .default
        }
        return AnyView(base.fontDesign(d))
    case suiModifierWireKindImageScale:
        guard let raw = reader.readI32() else { throw SUIModifierDecodeError.truncated }
        let s: Image.Scale
        switch raw {
        case 0: s = .small
        case 1: s = .medium
        case 2: s = .large
        default: s = .medium
        }
        return AnyView(base.imageScale(s))
    case suiModifierWireKindControlSize:
        guard let raw = reader.readI32() else { throw SUIModifierDecodeError.truncated }
        let cs: ControlSize
        switch raw {
        case 0: cs = .mini
        case 1: cs = .small
        case 2: cs = .regular
        case 3: cs = .large
        case 4: cs = .extraLarge
        default: cs = .regular
        }
        return AnyView(base.controlSize(cs))
    case suiModifierWireKindButtonStyle:
        guard let raw = reader.readI32() else { throw SUIModifierDecodeError.truncated }
        switch raw {
        case 0: return AnyView(base.buttonStyle(.automatic))
        case 1: return AnyView(base.buttonStyle(.bordered))
        case 2: return AnyView(base.buttonStyle(.borderedProminent))
        case 3: return AnyView(base.buttonStyle(.borderless))
        case 4: return AnyView(base.buttonStyle(.plain))
        default: return AnyView(base.buttonStyle(.automatic))
        }
    case suiModifierWireKindToggleStyle:
        guard let raw = reader.readI32() else { throw SUIModifierDecodeError.truncated }
        switch raw {
        case 0: return AnyView(base.toggleStyle(.automatic))
        case 1: return AnyView(base.toggleStyle(.button))
        case 2: return AnyView(base.toggleStyle(.checkbox))
        case 3: return AnyView(base.toggleStyle(.switch))
        default: return AnyView(base.toggleStyle(.automatic))
        }
    case suiModifierWireKindTextAlignment:
        guard let raw = reader.readI32() else { throw SUIModifierDecodeError.truncated }
        let a: TextAlignment
        switch raw {
        case 0: a = .leading
        case 1: a = .center
        case 2: a = .trailing
        default: a = .center
        }
        return AnyView(base.multilineTextAlignment(a))
    case suiModifierWireKindTruncationMode:
        guard let raw = reader.readI32() else { throw SUIModifierDecodeError.truncated }
        let m: Text.TruncationMode
        switch raw {
        case 0: m = .head
        case 1: m = .middle
        case 2: m = .tail
        default: m = .tail
        }
        return AnyView(base.truncationMode(m))
    case suiModifierWireKindFixedSize:
        return AnyView(base.fixedSize())
    default:
        throw SUIModifierDecodeError.unknownKind(kind)
    }
}

/// Apply a packed chain of modifiers in order. Returns a new retained view ref
/// on success. On decode failure (truncation or unknown kind) returns the
/// input ref with its retain count unchanged (i.e., NULL is never returned).
/// This lets the Go side distinguish "no change" from "changed".
@_cdecl("SUIApplyModifiers")
public func SUIApplyModifiers(_ viewRef: UnsafeMutableRawPointer, _ bufPtr: UnsafePointer<UInt8>?, _ bufLen: Int32) -> UnsafeMutableRawPointer {
    var reader = SUIModifierReader(bufPtr, Int(bufLen))
    guard let count = reader.readU32() else {
        return viewRef
    }
    if count == 0 {
        return viewRef
    }
    var current = Unmanaged<Box<AnyView>>.fromOpaque(viewRef).takeUnretainedValue().value
    for _ in 0..<count {
        guard let kind = reader.readU32(), let payloadLen = reader.readU32() else {
            return viewRef
        }
        let plen = Int(payloadLen)
        guard reader.remaining >= plen else {
            return viewRef
        }
        let payloadPtr: UnsafePointer<UInt8>?
        if plen > 0 {
            payloadPtr = reader.buffer.baseAddress?.advanced(by: reader.offset)
        } else {
            payloadPtr = nil
        }
        do {
            current = try suiApplyPackedModifier(current, kind: kind, payload: payloadPtr, payloadLen: plen)
        } catch {
            // Unknown kind or truncated payload: abort and return original.
            return viewRef
        }
        reader.offset += plen
    }
    return retainDerivedView(from: viewRef, current)
}
