// Code generated by applegen; DO NOT EDIT.

//go:build spritekit_embed

package embeddedbridge

import _ "embed"

//go:embed libSpriteKitSwiftUIBridge.dylib
var bridge []byte

// Payload returns the embedded SpriteKitSwiftUIBridge bridge dylib payload.
func Payload() ([]byte, string) {
	return bridge, "libSpriteKitSwiftUIBridge.dylib"
}
