// Code generated by applegen; DO NOT EDIT.

package swiftui

// AppConfig configures the application window.
type AppConfig struct {
	Title  string
	Width  float64
	Height float64
}

// MenuBarConfig configures a menu bar status item.
type MenuBarConfig struct {
	Label        string  // Text shown next to the icon
	SystemImage  string  // SF Symbol name for the icon
	Width        float64 // Popover width
	Height       float64 // Popover height
	OpenOnLaunch bool    // Show the popover immediately after app launch.
}

// MenuBarLabelStyle controls visual behavior when updating the status label.
type MenuBarLabelStyle struct {
	MonospacedDigits bool
	Animate          bool
}

// Run starts the application event loop with the given root view.
// This blocks until the application exits.
func Run(config AppConfig, root View) {
	withCString(config.Title, func(title *byte) {
		_SUIRun(root.ptr, title, config.Width, config.Height)
	})
}

// RunMenuBar starts a menu-bar-only app with no dock icon.
// The content View is shown in a popover when the status item is clicked.
// This blocks until the application exits.
func RunMenuBar(config MenuBarConfig, content View) {
	var openOnLaunch int32
	if config.OpenOnLaunch {
		openOnLaunch = 1
	}
	withCString(config.Label, func(label *byte) {
		withCString(config.SystemImage, func(img *byte) {
			if _SUIRunMenuBarEx != nil {
				_SUIRunMenuBarEx(label, img, content.ptr, config.Width, config.Height, openOnLaunch)
				return
			}
			_SUIRunMenuBar(label, img, content.ptr, config.Width, config.Height)
		})
	})
}

// RunWithMenuBar starts a windowed app that also has a menu bar item.
// The menuContent View is shown in a popover when the status item is clicked.
// This blocks until the application exits.
func RunWithMenuBar(appConfig AppConfig, content View, menuConfig MenuBarConfig, menuContent View) {
	withCString(appConfig.Title, func(title *byte) {
		withCString(menuConfig.Label, func(menuLabel *byte) {
			withCString(menuConfig.SystemImage, func(menuImg *byte) {
				_SUIRunWithMenuBar(content.ptr, title, appConfig.Width, appConfig.Height,
					menuLabel, menuImg, menuContent.ptr, menuConfig.Width, menuConfig.Height)
			})
		})
	})
}

func runScenePlan(planJSON string, views []uintptr) {
	var head *uintptr
	if len(views) > 0 {
		head = &views[0]
	}
	withCString(planJSON, func(plan *byte) {
		_SUIRunScenePlan(plan, head, int32(len(views)))
	})
}

func openSceneWindow(id string) bool {
	var ok int32
	withCString(id, func(sceneID *byte) {
		ok = _SUIOpenSceneWindow(sceneID)
	})
	return ok != 0
}

// UpdateMenuBarLabel changes the status item text at runtime.
func UpdateMenuBarLabel(label string) {
	withCString(label, func(l *byte) {
		_SUIUpdateMenuBarLabel(l)
	})
}

// UpdateMenuBarLabelStyled updates the status item text with optional styling.
// If the styled bridge symbol is unavailable, this falls back to UpdateMenuBarLabel.
func UpdateMenuBarLabelStyled(label string, style MenuBarLabelStyle) {
	if _SUIUpdateMenuBarLabelStyled == nil {
		UpdateMenuBarLabel(label)
		return
	}
	var monospacedDigits int32
	var animate int32
	if style.MonospacedDigits {
		monospacedDigits = 1
	}
	if style.Animate {
		animate = 1
	}
	withCString(label, func(l *byte) {
		_SUIUpdateMenuBarLabelStyled(l, monospacedDigits, animate)
	})
}

// PlaySystemSound plays a macOS system sound by name.
// Common names: "Basso", "Blow", "Bottle", "Frog", "Funk",
// "Glass", "Hero", "Morse", "Ping", "Pop", "Purr", "Sosumi",
// "Submarine", "Tink".
func PlaySystemSound(name string) {
	withCString(name, func(n *byte) {
		_SUIPlaySystemSound(n)
	})
}
