// Code generated by applegen; DO NOT EDIT.

package swiftui

import (
	"encoding/binary"
	"math"
	"runtime"
	"sync"
	"unsafe"

	"github.com/ebitengine/purego"
)

// Canvas opcode wire format. Shared with bridge_views.gen.swift
// (see suiDecodePath / BridgedCanvasView.render). Two opcode namespaces:
//
//	Path ops (nested inside Canvas Stroke/Fill/Clip payloads)
//	0x01 Move      : f64 x, f64 y
//	0x02 Line      : f64 x, f64 y
//	0x03 Quad      : f64 cx, f64 cy, f64 x, f64 y
//	0x04 Cubic     : f64 c1x, f64 c1y, f64 c2x, f64 c2y, f64 x, f64 y
//	0x05 Arc       : f64 cx, f64 cy, f64 r, f64 a0, f64 a1, u8 clockwise
//	0x06 Rect      : f64 x, f64 y, f64 w, f64 h
//	0x07 Ellipse   : f64 x, f64 y, f64 w, f64 h
//	0x08 Close     : (no operands)
//
//	Canvas ops (top-level in a Canvas blob)
//	0x10 Stroke    : u32 pathLen, f64 r,g,b,a, f64 lineWidth, u8 dashN, f64[dashN] dashes, <pathLen bytes of Path ops>
//	0x11 Fill      : u32 pathLen, f64 r,g,b,a, <pathLen bytes of Path ops>
//	0x12 Clip      : u32 pathLen, <pathLen bytes of Path ops>
//	0x13 Translate : f64 dx, f64 dy
//	0x14 Scale     : f64 sx, f64 sy
//	0x15 Rotate    : f64 radians
//	0x16 Save      : reserved (v1 decoder no-op)
//	0x17 Restore   : reserved (v1 decoder no-op)
//	0x18 Opacity   : f64 a
//
// All integers are little-endian; f64 is IEEE-754.

const (
	pathOpMove    byte = 0x01
	pathOpLine    byte = 0x02
	pathOpQuad    byte = 0x03
	pathOpCubic   byte = 0x04
	pathOpArc     byte = 0x05
	pathOpRect    byte = 0x06
	pathOpEllipse byte = 0x07
	pathOpClose   byte = 0x08

	canvasOpStroke    byte = 0x10
	canvasOpFill      byte = 0x11
	canvasOpClip      byte = 0x12
	canvasOpTranslate byte = 0x13
	canvasOpScale     byte = 0x14
	canvasOpRotate    byte = 0x15
	canvasOpSave      byte = 0x16
	canvasOpRestore   byte = 0x17
	canvasOpOpacity   byte = 0x18
)

// Path is a mutable opcode builder for SwiftUI Path shapes. A Path is
// cheap to construct and its underlying buffer is reusable. Methods return
// the receiver for fluent chaining.
//
// To get a SwiftUI View from a Path, call View. The resulting View is
// shape-backed, so .Fill, .Stroke, and .StrokeStyle work on it the same as
// on Circle, Rectangle, etc.
type Path struct {
	buf []byte
}

// NewPath creates a fresh Path with an empty opcode buffer.
func NewPath() *Path { return &Path{} }

// Bytes returns a reference to the underlying opcode buffer. The slice is
// valid until the next mutation on p; callers that need to retain the
// bytes beyond that should copy.
func (p *Path) Bytes() []byte { return p.buf }

// Reset clears the opcode buffer without releasing backing storage.
func (p *Path) Reset() *Path {
	p.buf = p.buf[:0]
	return p
}

func (p *Path) writeF64(v float64) {
	var b [8]byte
	binary.LittleEndian.PutUint64(b[:], math.Float64bits(v))
	p.buf = append(p.buf, b[:]...)
}

// Move starts a new subpath at (x, y).
func (p *Path) Move(x, y float64) *Path {
	p.buf = append(p.buf, pathOpMove)
	p.writeF64(x)
	p.writeF64(y)
	return p
}

// Line appends a straight segment from the current point to (x, y).
func (p *Path) Line(x, y float64) *Path {
	p.buf = append(p.buf, pathOpLine)
	p.writeF64(x)
	p.writeF64(y)
	return p
}

// Quad appends a quadratic bezier segment with a single control point.
func (p *Path) Quad(cx, cy, x, y float64) *Path {
	p.buf = append(p.buf, pathOpQuad)
	p.writeF64(cx)
	p.writeF64(cy)
	p.writeF64(x)
	p.writeF64(y)
	return p
}

// Cubic appends a cubic bezier segment with two control points. This is
// the primary building block for Sankey ribbons and curved network edges.
func (p *Path) Cubic(c1x, c1y, c2x, c2y, x, y float64) *Path {
	p.buf = append(p.buf, pathOpCubic)
	p.writeF64(c1x)
	p.writeF64(c1y)
	p.writeF64(c2x)
	p.writeF64(c2y)
	p.writeF64(x)
	p.writeF64(y)
	return p
}

// Arc appends a circular arc centered at (cx, cy) with radius r, sweeping
// from startRadians to endRadians. If clockwise, the sweep direction is
// flipped.
func (p *Path) Arc(cx, cy, r, startRadians, endRadians float64, clockwise bool) *Path {
	p.buf = append(p.buf, pathOpArc)
	p.writeF64(cx)
	p.writeF64(cy)
	p.writeF64(r)
	p.writeF64(startRadians)
	p.writeF64(endRadians)
	var cw byte
	if clockwise {
		cw = 1
	}
	p.buf = append(p.buf, cw)
	return p
}

// Rect appends an axis-aligned rectangle subpath.
func (p *Path) Rect(x, y, w, h float64) *Path {
	p.buf = append(p.buf, pathOpRect)
	p.writeF64(x)
	p.writeF64(y)
	p.writeF64(w)
	p.writeF64(h)
	return p
}

// Ellipse appends an ellipse subpath inscribed in the given rectangle.
func (p *Path) Ellipse(x, y, w, h float64) *Path {
	p.buf = append(p.buf, pathOpEllipse)
	p.writeF64(x)
	p.writeF64(y)
	p.writeF64(w)
	p.writeF64(h)
	return p
}

// Close closes the current subpath by appending a straight segment back
// to its starting point.
func (p *Path) Close() *Path {
	p.buf = append(p.buf, pathOpClose)
	return p
}

// View returns a SwiftUI View that renders this Path as a shape. The
// returned View carries an AnyShape sidecar, so the standard shape
// modifiers (.Fill, .Stroke, .StrokeStyle) work on it.
func (p *Path) View() View {
	ensureCanvasFuncs()
	if _suiPathFn == 0 {
		return EmptyView()
	}
	var bufArg uintptr
	if len(p.buf) > 0 {
		bufArg = uintptr(unsafe.Pointer(&p.buf[0]))
	}
	ret, _, _ := purego.SyscallN(_suiPathFn, bufArg, uintptr(uint32(len(p.buf))))
	runtime.KeepAlive(p.buf)
	if ret == 0 {
		return EmptyView()
	}
	return View{ptr: ret, retained: newRetainedOwned(ret)}
}

// CanvasOps is a mutable opcode buffer for a Canvas render pass. Build one
// by calling NewCanvasOps and appending stroke/fill/transform/opacity
// opcodes; the whole buffer is submitted to Swift as a single blob via
// CanvasState.Set.
//
// CanvasOps does not validate that Paths referenced by Stroke/Fill/Clip
// outlive the render pass — the opcode stream copies path bytes inline, so
// the caller's Path can be reused or discarded after the Stroke/Fill/Clip
// call returns.
type CanvasOps struct {
	buf []byte
}

// NewCanvasOps creates an empty CanvasOps buffer.
func NewCanvasOps() *CanvasOps { return &CanvasOps{} }

// Bytes returns a reference to the opcode buffer. The slice is valid until
// the next mutation on c.
func (c *CanvasOps) Bytes() []byte { return c.buf }

// Reset clears the opcode buffer without releasing backing storage. Useful
// for per-frame rebuilds.
func (c *CanvasOps) Reset() *CanvasOps {
	c.buf = c.buf[:0]
	return c
}

func (c *CanvasOps) writeU32(v uint32) {
	var b [4]byte
	binary.LittleEndian.PutUint32(b[:], v)
	c.buf = append(c.buf, b[:]...)
}

func (c *CanvasOps) writeF64(v float64) {
	var b [8]byte
	binary.LittleEndian.PutUint64(b[:], math.Float64bits(v))
	c.buf = append(c.buf, b[:]...)
}

// Stroke outlines the given Path with the given color and line width. If
// dash is non-empty, the outline uses the provided dash pattern (in points,
// alternating on/off); pass nil for a solid stroke.
func (c *CanvasOps) Stroke(p *Path, col Color, lineWidth float64, dash []float64) *CanvasOps {
	c.buf = append(c.buf, canvasOpStroke)
	c.writeU32(uint32(len(p.buf)))
	c.writeF64(col.R)
	c.writeF64(col.G)
	c.writeF64(col.B)
	c.writeF64(col.A)
	c.writeF64(lineWidth)
	if len(dash) > 255 {
		dash = dash[:255] // v1 caps dash-pattern length at 255 segments
	}
	c.buf = append(c.buf, byte(len(dash)))
	for _, d := range dash {
		c.writeF64(d)
	}
	c.buf = append(c.buf, p.buf...)
	return c
}

// Fill fills the given Path with the given color.
func (c *CanvasOps) Fill(p *Path, col Color) *CanvasOps {
	c.buf = append(c.buf, canvasOpFill)
	c.writeU32(uint32(len(p.buf)))
	c.writeF64(col.R)
	c.writeF64(col.G)
	c.writeF64(col.B)
	c.writeF64(col.A)
	c.buf = append(c.buf, p.buf...)
	return c
}

// Clip restricts subsequent drawing to the interior of the given Path.
func (c *CanvasOps) Clip(p *Path) *CanvasOps {
	c.buf = append(c.buf, canvasOpClip)
	c.writeU32(uint32(len(p.buf)))
	c.buf = append(c.buf, p.buf...)
	return c
}

// Translate shifts the coordinate system by (dx, dy).
func (c *CanvasOps) Translate(dx, dy float64) *CanvasOps {
	c.buf = append(c.buf, canvasOpTranslate)
	c.writeF64(dx)
	c.writeF64(dy)
	return c
}

// Scale multiplies the coordinate system by (sx, sy).
func (c *CanvasOps) Scale(sx, sy float64) *CanvasOps {
	c.buf = append(c.buf, canvasOpScale)
	c.writeF64(sx)
	c.writeF64(sy)
	return c
}

// Rotate rotates the coordinate system by the given angle in radians.
func (c *CanvasOps) Rotate(radians float64) *CanvasOps {
	c.buf = append(c.buf, canvasOpRotate)
	c.writeF64(radians)
	return c
}

// Opacity sets the global opacity multiplier for subsequent drawing.
func (c *CanvasOps) Opacity(a float64) *CanvasOps {
	c.buf = append(c.buf, canvasOpOpacity)
	c.writeF64(a)
	return c
}

// CanvasState holds an opcode blob on the Swift side; the Canvas view
// observes it and re-renders whenever Set publishes a new blob. The
// lifecycle mirrors NumberState / FloatState.
type CanvasState struct {
	ptr      uintptr
	retained *retainedOwned
}

// NewCanvasState creates a new CanvasState initialized to the given opcode
// blob. Pass nil for an empty Canvas.
func NewCanvasState(initial *CanvasOps) *CanvasState {
	ensureCanvasFuncs()
	if _suiCanvasStateNewFn == 0 {
		return &CanvasState{}
	}
	var bufArg uintptr
	var bufLen uint32
	if initial != nil && len(initial.buf) > 0 {
		bufArg = uintptr(unsafe.Pointer(&initial.buf[0]))
		bufLen = uint32(len(initial.buf))
	}
	ret, _, _ := purego.SyscallN(_suiCanvasStateNewFn, bufArg, uintptr(bufLen))
	if initial != nil {
		runtime.KeepAlive(initial.buf)
	}
	if ret == 0 {
		return &CanvasState{}
	}
	return &CanvasState{ptr: ret, retained: newRetainedOwned(ret)}
}

// Set publishes a new opcode blob, triggering Canvas re-render.
func (s *CanvasState) Set(ops *CanvasOps) {
	ensureCanvasFuncs()
	if s == nil || s.ptr == 0 || _suiCanvasStateSetFn == 0 {
		return
	}
	var bufArg uintptr
	var bufLen uint32
	if ops != nil && len(ops.buf) > 0 {
		bufArg = uintptr(unsafe.Pointer(&ops.buf[0]))
		bufLen = uint32(len(ops.buf))
	}
	purego.SyscallN(_suiCanvasStateSetFn, s.ptr, bufArg, uintptr(bufLen))
	if ops != nil {
		runtime.KeepAlive(ops.buf)
	}
	runtime.KeepAlive(s.retained)
}

// Canvas returns a SwiftUI Canvas view bound to the given state with the
// given pixel dimensions. The Canvas re-renders whenever state.Set is
// called with a new opcode blob.
func Canvas(state *CanvasState, width, height float64) View {
	ensureCanvasFuncs()
	if state == nil || state.ptr == 0 || _suiCanvasFn == nil {
		return EmptyView()
	}
	ret := _suiCanvasFn(state.ptr, width, height)
	runtime.KeepAlive(state.retained)
	if ret == 0 {
		return EmptyView()
	}
	return View{ptr: ret, retained: newRetainedOwned(ret)}
}

// StrokeStyle outlines the shape with the given color, line width, and
// dash pattern. dash is a sequence of on/off lengths in points; pass nil
// for a solid outline. Only the first 255 dash segments are honored.
//
// Complements ShapeView.Stroke, which is kept for back-compat; prefer
// StrokeStyle when a dash pattern is needed.
func (v ShapeView) StrokeStyle(col Color, lineWidth float64, dash []float64) ShapeView {
	ensureCanvasFuncs()
	if _suiViewShapeStrokeStyleFn == nil {
		// Fallback: dash is ignored when the bridge predates StrokeStyle.
		return v.Stroke(col.R, col.G, col.B, col.A, lineWidth)
	}
	if len(dash) > 255 {
		dash = dash[:255]
	}
	// [ u8 count, f64*count ] — matches the dash encoding used by
	// CanvasOps.Stroke so the Swift decoder reuses SUIModifierReader.
	dashBuf := make([]byte, 1+8*len(dash))
	dashBuf[0] = byte(len(dash))
	for i, d := range dash {
		binary.LittleEndian.PutUint64(dashBuf[1+8*i:], math.Float64bits(d))
	}
	var dashArg uintptr
	if len(dashBuf) > 0 {
		dashArg = uintptr(unsafe.Pointer(&dashBuf[0]))
	}
	ret := _suiViewShapeStrokeStyleFn(v.View.ptr, col.R, col.G, col.B, col.A, lineWidth, dashArg, int32(len(dashBuf)))
	runtime.KeepAlive(dashBuf)
	runtime.KeepAlive(v.View.retained)
	if ret == 0 {
		return v
	}
	return ShapeView{View: View{ptr: ret, retained: newRetainedOwned(ret)}}
}

// --- Registration / stub ---
//
// SUIPath, SUICanvasStateNew, and SUICanvasStateSet take only uintptr-
// compatible args (pointer + int32 length), so they are resolved via Dlsym
// + SyscallN for low overhead (matches wire_modifiers.go).
//
// SUICanvas takes two float64 args (width, height) that must land in FP
// registers, so it goes through RegisterLibFunc. Same for
// SUIViewShapeStrokeStyle which mixes float64 color/width args with pointer
// args.

var (
	canvasFuncsOnce            sync.Once
	_suiPathFn                 uintptr
	_suiCanvasStateNewFn       uintptr
	_suiCanvasStateSetFn       uintptr
	_suiCanvasFn               func(uintptr, float64, float64) uintptr
	_suiViewShapeStrokeStyleFn func(uintptr, float64, float64, float64, float64, float64, uintptr, int32) uintptr
)

func ensureCanvasFuncs() {
	canvasFuncsOnce.Do(func() {
		if libHandle == 0 {
			return
		}
		if fn, err := purego.Dlsym(libHandle, "SUIPath"); err == nil {
			_suiPathFn = fn
		}
		if fn, err := purego.Dlsym(libHandle, "SUICanvasStateNew"); err == nil {
			_suiCanvasStateNewFn = fn
		}
		if fn, err := purego.Dlsym(libHandle, "SUICanvasStateSet"); err == nil {
			_suiCanvasStateSetFn = fn
		}
		// SUICanvas and SUIViewShapeStrokeStyle may not exist if the bridge
		// dylib predates the feature; guard registration so older dylibs
		// don't panic.
		if _, err := purego.Dlsym(libHandle, "SUICanvas"); err == nil {
			purego.RegisterLibFunc(&_suiCanvasFn, libHandle, "SUICanvas")
		}
		if _, err := purego.Dlsym(libHandle, "SUIViewShapeStrokeStyle"); err == nil {
			purego.RegisterLibFunc(&_suiViewShapeStrokeStyleFn, libHandle, "SUIViewShapeStrokeStyle")
		}
	})
}
