// Code generated by applegen; DO NOT EDIT.

// Package swiftui provides Go bindings for Apple's SwiftUI framework,
// enabling declarative UI construction from pure Go on macOS 26 or later.
//
// SwiftUI is a Swift-only framework. This package includes a vendored
// Swift bridge (under internal/swift/) that is automatically built on first use.
// No external dependencies or manual setup required — just go run.
//
// # View types
//
// Three concrete view types model SwiftUI's view hierarchy:
//
//   - [View] is the universal opaque handle. Every constructor and universal
//     modifier returns a View.
//   - [ShapeView] is returned by shape constructors (Circle, Rectangle, ...).
//     It adds shape-specific modifiers such as Fill and Stroke and keeps the
//     ShapeView type through universal modifier chains.
//   - [TextView] is returned by text constructors (Text, Label, ...). It adds
//     text-specific modifiers such as Bold, Italic, and Font and likewise keeps
//     the TextView type through universal modifier chains.
//
// ShapeView and TextView embed View, so a shape or text view is usable anywhere
// a View is. Call AsView to drop the specialized type explicitly. The
// [Viewable] interface is satisfied by all three; functions and modifiers that
// take a child view accept Viewable, so any view type can be passed directly
// without conversion.
//
// # Function families
//
// The exported surface groups into three families:
//
//   - Building views: the View/ShapeView/TextView constructors and modifiers
//     described above.
//   - Reactive state: the *State types ([IntState], [StringState],
//     [FloatState], [BoolState], [ColorState], [DateState],
//     [TextSelectionState]). Construct one with NewXState, bind it into a view,
//     and call Set (or SetAnimated) to drive automatic SwiftUI updates.
//   - Dynamic content: helpers that rebuild views from state, such as
//     DynamicView and ForEach-style builders, plus the callback-driven controls
//     (Button, Stepper, ...) that invoke Go closures from SwiftUI.
//
// # Threading
//
// All View construction and modifier calls must happen on the main thread.
// Call runtime.LockOSThread() in init() or TestMain to pin the main
// goroutine. The *State Set methods (for example [IntState.Set] and
// [IntState.SetAnimated]) are safe to call from any goroutine — the Swift
// bridge dispatches the update to the MainActor automatically. To change what
// a running UI displays from a background goroutine, mutate the reactive state
// it is bound to rather than building views off the main thread.
//
// # Environment
//
// By default, the package loads the embedded bridge from a per-user cache
// under $HOME/Library/Caches/swiftui/bridge-cache.
//
// To override the dylib path, set $LIBSWIFTUI_BRIDGE_PATH.
//
// # Scenes
//
// Run is the single entry point for window, multi-window, menu-bar, and Settings
// apps. It lowers the App's Windows, MenuBar, Settings, and Commands into the
// current AppKit-owned scene runner, and OpenWindow focuses or opens a
// configured window by its WindowConfig.ID at runtime. Document scenes remain a
// runner capability not surfaced as Go API.
//
// The runner owns NSWindow, main-menu, NSPopover, and document-session
// lifecycle directly. It persists per-instance window frames and visibility,
// and supports multi-instance WindowGroup families with explicit restoration
// IDs and WindowInstanceCount tracking, while singleton Window scenes remain
// explicit. It exposes a concrete Settings window through the app menu, and
// installs standard system-backed File/Edit/Window commands for both windowed
// and menu-bar-only scene plans. It presents document open/save panels and
// open/save/save-as/export/import/revert flows with dirty-close confirmation,
// approved close callbacks, recent-document registration, persistent
// recent-document restoration, last-path restoration, and explicit
// recent-document command menus. Scene availability is injected into borrowed
// SceneActions through the bridge callback channel.
//
// App.Commands installs native application-menu commands as CommandGroup
// values holding CommandItem entries. An item carries a Title and an Action,
// an optional Enabled func consulted for menu validation, a ShortcutKey with
// ShortcutModifiers, or a SystemAction naming a standard selector; Children
// makes it a submenu and Kind "separator" makes it a separator. Set
// CommandGroup.AppMenu to put a group in the application menu above Settings
// and Quit, rather than in a top-level menu of its own. Commands are served by
// the scene runner, so an App that sets them takes the scene path even with a
// single window, as does a window that sets any WindowConfig presentation
// option below.
//
// WindowConfig controls how each window is presented. Resizable pins the
// window to its Width and Height when false, HiddenTitleBar lets the root view
// draw through the title bar, Utility makes a floating panel that hides while
// the application is not frontmost, Centered centers on every open instead of
// restoring the last position, and OpenOnLaunch decides whether the window is
// shown at startup.
//
// The package also includes additive Go-native helpers such as
// ClipboardWriteString, OpenPanel, SavePanel, PlacementHint/TaggedWithPlacement,
// TableColumnLayoutSnapshot, which drives capture/restore of NativeTable column
// widths, and PhotosPickerLazyFileHandle, which hands sample selection state a
// deterministic lazy file-backed asset. Those are explicit curated utilities
// rather than claims of one-for-one SwiftUI API parity.
//
// This is intentionally narrower than SwiftUI's full App/Scene environment
// model. OpenWindowAction, app command menus, and document-session file
// workflows are runner-backed today, while refresh actions remain borrowed
// runtime capabilities rather than direct SwiftUI environment parity or a
// native Scene graph.
//
// # Current Parity Boundaries
//
// The current bridge is intentionally explicit about four remaining parity
// boundaries:
//
//   - scene/app structure: scene descriptors, multi-instance WindowGroup
//     restoration, singleton Window scenes, WindowInstanceCount tracking, and
//     borrowed SceneActions are supported, but the runtime is still
//     AppKit-owned rather than a direct SwiftUI App/Scene graph
//   - table/outline data surfaces: the public API combines curated Go models
//     with native-backed NativeTable plus curated Go layout helpers. NativeTable
//     covers string data, row selection, sortable headers, and column resizing;
//     the older Table helper remains an equal-width layout convenience.
//     OutlineGroup parity is still incomplete.
//   - custom layout: the supported surface is the constrained Go-side layout
//     model with PlacementHint/TaggedWithPlacement fixed-key placement metadata
//     and placement presets rather than SwiftUI's protocol-heavy Layout and
//     LayoutValueKey
//   - curated additive helpers: the Go-native utilities above are explicit
//     conveniences rather than direct SwiftUI equivalents
//
// Plain ScrollView offset observation is exposed through
// View.OnScrollGeometryChange on macOS 15 or later.
package swiftui
