// Code generated by applegen; DO NOT EDIT.

package swiftui_test

import (
	"fmt"

	"github.com/tmc/swiftui"
)

// Example wires a reactive state value to a Button and a DynamicView: tapping
// the button mutates the state, and the DynamicView rebuilds from the new value
// automatically.
func Example() {
	count := swiftui.NewIntState(0)

	view := swiftui.VStack(
		swiftui.DynamicView(count, func(n int) swiftui.View {
			return swiftui.Text(fmt.Sprintf("Count: %d", n)).AsView()
		}),
		swiftui.Button("Increment", func() {
			count.Set(count.Get() + 1)
		}),
	)

	_ = view
}

func ExampleClipboardWriteString() {
	_ = swiftui.ClipboardWriteString("token")
}

func ExampleOpenPanel() {
	paths, ok := swiftui.OpenPanel(swiftui.OpenPanelOptions{
		Title:          "Open Data",
		AllowsMultiple: true,
	})
	_, _ = paths, ok
}

func ExampleSavePanel() {
	path, ok := swiftui.SavePanel(swiftui.SavePanelOptions{
		Title: "Export Data",
		Name:  "data.json",
	})
	_, _ = path, ok
}
