// Code generated by applegen; DO NOT EDIT.

package swiftui_test

import (
	"fmt"

	"github.com/tmc/swiftui"
)

// Example wires a reactive state value to a Button and a DynamicView: tapping
// the button mutates the state, and the DynamicView rebuilds from the new value
// automatically.
func Example() {
	count := swiftui.NewIntState(0)

	view := swiftui.VStack(
		swiftui.DynamicView(count, func(n int) swiftui.View {
			return swiftui.Text(fmt.Sprintf("Count: %d", n)).AsView()
		}),
		swiftui.Button("Increment", func() {
			count.Set(count.Get() + 1)
		}),
	)

	_ = view
}
