// Code generated by applegen; DO NOT EDIT.

package swiftui

func compileGlassAPI(v View, content View, ns *Namespace) {
	glass := GlassClear().Tint(RGBA(1, 0.5, 0, 1)).Interactive(true)

	_ = GlassRegular()
	_ = GlassIdentity()
	_ = GlassEffectContainer(content)
	_ = GlassEffectContainerSpaced(24, content)
	_ = v.GlassEffect()
	_ = v.GlassEffectWith(glass)
	_ = v.GlassEffectShape(GlassShapeRoundedRectangle, 16)
	_ = v.GlassEffectIn(glass, GlassShapeCircle, 0)
	_ = v.GlassEffectID("badge", ns)
	_ = v.GlassEffectUnion("group", ns)
	_ = v.GlassEffectTransition(GlassEffectTransitionMatchedGeometry)
	_ = v.GlassButtonStyle(glass)
	_ = v.GlassProminentButtonStyle()
}
