// Code generated by applegen; DO NOT EDIT.

package swiftui

// IntState is a reactive integer state that bridges Go and SwiftUI.
// When the value changes via Set, any SwiftUI views observing this
// state update automatically.
type IntState struct {
	ptr      uintptr
	retained *retained
}

// NewIntState creates a new reactive integer state with the given initial value.
func NewIntState(initial int) *IntState {
	ptr := _SUIStateCreateInt(int32(initial))
	return &IntState{ptr: ptr, retained: newRetained(ptr)}
}

// Get returns the current value.
func (s *IntState) Get() int {
	return int(_SUIStateGetInt(s.ptr))
}

// Set updates the value, triggering SwiftUI view updates.
func (s *IntState) Set(v int) {
	_SUIStateSetInt(s.ptr, int32(v))
}

// SetAnimated updates the value inside withAnimation, triggering animated SwiftUI transitions.
func (s *IntState) SetAnimated(v int) {
	s.SetAnimatedWith(v, AnimationEaseInOut)
}

// SetAnimatedWith updates the value using the provided animation curve.
func (s *IntState) SetAnimatedWith(v int, kind AnimationKind) {
	_SUIStateSetIntAnimatedWith(s.ptr, int32(v), int32(kind))
}

// StringState is a reactive string state that bridges Go and SwiftUI.
type StringState struct {
	ptr      uintptr
	retained *retained
}

// NewStringState creates a new reactive string state with the given initial value.
func NewStringState(initial string) *StringState {
	var ptr uintptr
	withCString(initial, func(cs *byte) {
		ptr = _SUIStateCreateString(cs)
	})
	return &StringState{ptr: ptr, retained: newRetained(ptr)}
}

// Get returns the current string value.
func (s *StringState) Get() string {
	// cStringToGoString is the shared NUL-terminated C string decoder defined
	// in callback.go (N9).
	return cStringToGoString(_SUIStateGetString(s.ptr))
}

// Set updates the string value, triggering SwiftUI view updates.
func (s *StringState) Set(v string) {
	withCString(v, func(cs *byte) {
		_SUIStateSetString(s.ptr, cs)
	})
}

// TextSelectionState is a reactive UTF-16 text selection range.
type TextSelectionState struct {
	ptr      uintptr
	retained *retained
}

// NewTextSelectionState creates a new reactive UTF-16 text selection range.
func NewTextSelectionState(start, end int) *TextSelectionState {
	ptr := _SUIStateCreateTextSelection(int32(start), int32(end))
	return &TextSelectionState{ptr: ptr, retained: newRetained(ptr)}
}

// Start returns the current UTF-16 selection start offset.
func (s *TextSelectionState) Start() int {
	return int(_SUIStateGetTextSelectionStart(s.ptr))
}

// End returns the current UTF-16 selection end offset.
func (s *TextSelectionState) End() int {
	return int(_SUIStateGetTextSelectionEnd(s.ptr))
}

// Set updates the UTF-16 selection range.
func (s *TextSelectionState) Set(start, end int) {
	_SUIStateSetTextSelection(s.ptr, int32(start), int32(end))
}

// ColorState is a reactive RGBA color state that bridges Go and SwiftUI.
type ColorState struct {
	ptr      uintptr
	retained *retained
}

// NewColorState creates a new reactive color state from RGBA values (0.0-1.0).
func NewColorState(r, g, b, a float64) *ColorState {
	ptr := _SUIStateCreateColor(r, g, b, a)
	return &ColorState{ptr: ptr, retained: newRetained(ptr)}
}

// R returns the red component (0.0-1.0).
func (s *ColorState) R() float64 { return _SUIStateGetColorR(s.ptr) }

// G returns the green component (0.0-1.0).
func (s *ColorState) G() float64 { return _SUIStateGetColorG(s.ptr) }

// B returns the blue component (0.0-1.0).
func (s *ColorState) B() float64 { return _SUIStateGetColorB(s.ptr) }

// A returns the alpha component (0.0-1.0).
func (s *ColorState) A() float64 { return _SUIStateGetColorA(s.ptr) }

// Set updates the RGBA color values.
func (s *ColorState) Set(r, g, b, a float64) {
	_SUIStateSetColor(s.ptr, r, g, b, a)
}

// DateState is a reactive date state that bridges Go and SwiftUI.
// Dates are represented as Unix epoch seconds (float64).
type DateState struct {
	ptr      uintptr
	retained *retained
}

// NewDateState creates a new reactive date state from Unix epoch seconds.
func NewDateState(epochSeconds float64) *DateState {
	ptr := _SUIStateCreateDate(epochSeconds)
	return &DateState{ptr: ptr, retained: newRetained(ptr)}
}

// Get returns the current date as Unix epoch seconds.
func (s *DateState) Get() float64 {
	return _SUIStateGetDate(s.ptr)
}

// Set updates the date from Unix epoch seconds.
func (s *DateState) Set(epochSeconds float64) {
	_SUIStateSetDate(s.ptr, epochSeconds)
}

// FloatState is a reactive float64 state that bridges Go and SwiftUI.
type FloatState struct {
	ptr      uintptr
	retained *retained
}

// NewFloatState creates a new reactive float64 state with the given initial value.
func NewFloatState(initial float64) *FloatState {
	ptr := _SUIStateCreateFloat(initial)
	return &FloatState{ptr: ptr, retained: newRetained(ptr)}
}

// Get returns the current float64 value.
func (s *FloatState) Get() float64 {
	return _SUIStateGetFloat(s.ptr)
}

// Set updates the float64 value, triggering SwiftUI view updates.
func (s *FloatState) Set(v float64) {
	_SUIStateSetFloat(s.ptr, v)
}

// SetAnimated updates the float64 value inside withAnimation.
func (s *FloatState) SetAnimated(v float64) {
	s.SetAnimatedWith(v, AnimationEaseInOut)
}

// SetAnimatedWith updates the float64 value using the provided animation curve.
func (s *FloatState) SetAnimatedWith(v float64, kind AnimationKind) {
	_SUIStateSetFloatAnimatedWith(s.ptr, v, int32(kind))
}

// BoolState is an observable boolean state value.
type BoolState struct {
	ptr      uintptr
	retained *retained
}

// NewBoolState creates a new observable boolean state.
func NewBoolState(initial bool) *BoolState {
	var v int32
	if initial {
		v = 1
	}
	ptr := _SUIStateCreateBool(v)
	return &BoolState{ptr: ptr, retained: newRetained(ptr)}
}

// Get returns the current boolean value.
func (s *BoolState) Get() bool {
	return _SUIStateGetBool(s.ptr) != 0
}

// Set updates the boolean value.
func (s *BoolState) Set(v bool) {
	var vv int32
	if v {
		vv = 1
	}
	_SUIStateSetBool(s.ptr, vv)
}

// SetAnimated updates the boolean value with the default ease-in-out animation.
func (s *BoolState) SetAnimated(v bool) {
	s.SetAnimatedWith(v, AnimationEaseInOut)
}

// SetAnimatedWith updates the boolean value using the provided animation curve.
func (s *BoolState) SetAnimatedWith(v bool, kind AnimationKind) {
	var vv int32
	if v {
		vv = 1
	}
	_SUIStateSetBoolAnimatedWith(s.ptr, vv, int32(kind))
}

// releaseState decrements the Swift retain count behind a reactive state value
// and clears the handle. It is the shared body of every *State.Release method
// (N4). retained and ptr are the addresses of the state's two fields so the
// caller is reset in place.
func releaseState(retained **retained, ptr *uintptr) {
	if retained == nil || *retained == nil {
		return
	}
	(*retained).release()
	*retained = nil
	*ptr = 0
}

// Release decrements the underlying Swift retain count.
//
// After Release the state must not be used or passed to a view again, and a
// state that is currently bound into a live view must not be released; doing
// either leaves the view referencing a freed handle.
func (s *IntState) Release() {
	if s == nil {
		return
	}
	releaseState(&s.retained, &s.ptr)
}

// Release decrements the underlying Swift retain count.
//
// After Release the state must not be used or passed to a view again, and a
// state that is currently bound into a live view must not be released; doing
// either leaves the view referencing a freed handle.
func (s *StringState) Release() {
	if s == nil {
		return
	}
	releaseState(&s.retained, &s.ptr)
}

// Release decrements the underlying Swift retain count.
//
// After Release the state must not be used or passed to a view again, and a
// state that is currently bound into a live view must not be released; doing
// either leaves the view referencing a freed handle.
func (s *TextSelectionState) Release() {
	if s == nil {
		return
	}
	releaseState(&s.retained, &s.ptr)
}

// Release decrements the underlying Swift retain count.
//
// After Release the state must not be used or passed to a view again, and a
// state that is currently bound into a live view must not be released; doing
// either leaves the view referencing a freed handle.
func (s *ColorState) Release() {
	if s == nil {
		return
	}
	releaseState(&s.retained, &s.ptr)
}

// Release decrements the underlying Swift retain count.
//
// After Release the state must not be used or passed to a view again, and a
// state that is currently bound into a live view must not be released; doing
// either leaves the view referencing a freed handle.
func (s *DateState) Release() {
	if s == nil {
		return
	}
	releaseState(&s.retained, &s.ptr)
}

// Release decrements the underlying Swift retain count.
//
// After Release the state must not be used or passed to a view again, and a
// state that is currently bound into a live view must not be released; doing
// either leaves the view referencing a freed handle.
func (s *FloatState) Release() {
	if s == nil {
		return
	}
	releaseState(&s.retained, &s.ptr)
}

// Release decrements the underlying Swift retain count.
//
// After Release the state must not be used or passed to a view again, and a
// state that is currently bound into a live view must not be released; doing
// either leaves the view referencing a freed handle.
func (s *BoolState) Release() {
	if s == nil {
		return
	}
	releaseState(&s.retained, &s.ptr)
}
