// Code generated by applegen; DO NOT EDIT.

package bridgeutil

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// EnsurePrivateDir makes sure path exists as a non-symlink directory with 0700 permissions.
func EnsurePrivateDir(path string) error {
	if err := os.MkdirAll(path, 0o700); err != nil {
		return fmt.Errorf("create directory %s: %w", path, err)
	}
	info, err := os.Lstat(path)
	if err != nil {
		return fmt.Errorf("stat directory %s: %w", path, err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("directory %s must not be a symlink", path)
	}
	if !info.IsDir() {
		return fmt.Errorf("%s is not a directory", path)
	}
	if info.Mode().Perm() == 0o700 {
		return nil
	}
	if err := os.Chmod(path, 0o700); err != nil {
		return fmt.Errorf("chmod directory %s: %w", path, err)
	}
	return nil
}

// SwiftUICacheDir returns a secured cache directory under the user's cache root.
func SwiftUICacheDir(parts ...string) (string, error) {
	base, err := os.UserCacheDir()
	if err != nil {
		return "", fmt.Errorf("locate user cache dir: %w", err)
	}
	root := filepath.Join(base, "swiftui")
	if err := EnsurePrivateDir(root); err != nil {
		return "", err
	}
	dir := filepath.Join(append([]string{root}, parts...)...)
	if err := EnsurePrivateDir(dir); err != nil {
		return "", err
	}
	return dir, nil
}

// DiscoverBuiltDylib locates a built dylib from common SwiftPM output layouts.
func DiscoverBuiltDylib(baseDir, dylibName string) (string, error) {
	if baseDir == "" {
		return "", fmt.Errorf("empty base dir")
	}
	if dylibName == "" {
		return "", fmt.Errorf("empty dylib name")
	}

	roots := []string{
		filepath.Join(baseDir, ".build"),
		baseDir,
	}
	rels := []string{
		filepath.Join("release", dylibName),
		filepath.Join("arm64-apple-macosx", "release", dylibName),
		filepath.Join("x86_64-apple-macosx", "release", dylibName),
		filepath.Join("universal", "release", dylibName),
	}

	seen := make(map[string]bool)
	var candidates []string
	for _, root := range roots {
		for _, rel := range rels {
			path := filepath.Join(root, rel)
			if seen[path] {
				continue
			}
			seen[path] = true
			candidates = append(candidates, path)
		}
	}

	for _, root := range roots {
		glob, _ := filepath.Glob(filepath.Join(root, "*", "release", dylibName))
		sort.Strings(glob)
		for _, path := range glob {
			if seen[path] {
				continue
			}
			seen[path] = true
			candidates = append(candidates, path)
		}
	}

	for _, path := range candidates {
		info, err := os.Stat(path)
		if err != nil {
			continue
		}
		if info.Mode().IsRegular() {
			return path, nil
		}
	}
	return "", fmt.Errorf("built dylib %s not found", dylibName)
}

func versionedScratchCacheKey(swiftDir, dylibName string) (string, error) {
	hash := sha256.New()
	if err := hashSwiftBridgeTree(hash, swiftDir); err != nil {
		return "", err
	}
	if _, err := io.WriteString(hash, "\n--swift-version--\n"); err != nil {
		return "", err
	}
	if _, err := io.WriteString(hash, swiftVersionOutput()); err != nil {
		return "", err
	}
	if _, err := io.WriteString(hash, "\n--goarch--\n"); err != nil {
		return "", err
	}
	if _, err := io.WriteString(hash, runtime.GOARCH); err != nil {
		return "", err
	}
	return cacheDirLabel(dylibName) + "-" + hex.EncodeToString(hash.Sum(nil))[:16], nil
}

func hashSwiftBridgeTree(dst io.Writer, swiftDir string) error {
	return filepath.WalkDir(swiftDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && d.Name() == ".build" {
			return filepath.SkipDir
		}
		if d.IsDir() {
			return nil
		}
		if !d.Type().IsRegular() {
			return nil
		}

		rel, err := filepath.Rel(swiftDir, path)
		if err != nil {
			return fmt.Errorf("rel %s: %w", path, err)
		}
		if _, err := io.WriteString(dst, filepath.ToSlash(rel)); err != nil {
			return err
		}
		if _, err := io.WriteString(dst, "\n"); err != nil {
			return err
		}

		f, err := os.Open(path)
		if err != nil {
			return fmt.Errorf("open %s: %w", path, err)
		}
		if _, err := io.Copy(dst, f); err != nil {
			f.Close()
			return fmt.Errorf("hash %s: %w", path, err)
		}
		if err := f.Close(); err != nil {
			return fmt.Errorf("close %s: %w", path, err)
		}
		_, err = io.WriteString(dst, "\n")
		return err
	})
}

func swiftVersionOutput() string {
	out, err := exec.Command("swift", "--version").CombinedOutput()
	if err != nil {
		return "error: " + strings.TrimSpace(string(out)) + " (" + err.Error() + ")"
	}
	return strings.TrimSpace(string(out))
}

func cacheDirLabel(dylibName string) string {
	name := strings.TrimPrefix(strings.TrimSuffix(dylibName, filepath.Ext(dylibName)), "lib")
	name = strings.ToLower(name)
	var b strings.Builder
	lastDash := false
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
			lastDash = false
		case r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		case b.Len() == 0 || lastDash:
			continue
		default:
			b.WriteByte('-')
			lastDash = true
		}
	}
	label := strings.Trim(b.String(), "-")
	if label == "" {
		return "bridge"
	}
	return label
}

// BuildSwiftBridge builds a Swift bridge dylib to a writable secure scratch directory.
func BuildSwiftBridge(swiftDir, dylibName, errPrefix string) (string, error) {
	if path, err := DiscoverBuiltDylib(swiftDir, dylibName); err == nil {
		return path, nil
	}

	if _, err := os.Stat(filepath.Join(swiftDir, "Package.swift")); err != nil {
		return "", fmt.Errorf("%s: swift bridge source not found at %s", errPrefix, swiftDir)
	}

	cacheKey, err := versionedScratchCacheKey(swiftDir, dylibName)
	if err != nil {
		return "", fmt.Errorf("%s: compute swift build cache key: %w", errPrefix, err)
	}
	scratchDir, err := SwiftUICacheDir("swift-build", cacheKey)
	if err != nil {
		return "", fmt.Errorf("%s: prepare swift build cache: %w", errPrefix, err)
	}
	if path, err := DiscoverBuiltDylib(scratchDir, dylibName); err == nil {
		return path, nil
	}

	cmd := exec.Command("swift", "build", "-c", "release", "--quiet", "--scratch-path", scratchDir)
	cmd.Dir = swiftDir
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("%s: swift build failed: %w", errPrefix, err)
	}

	path, err := DiscoverBuiltDylib(scratchDir, dylibName)
	if err != nil {
		return "", fmt.Errorf("%s: %w", errPrefix, err)
	}
	return path, nil
}
