// Code generated by applegen; DO NOT EDIT.

//go:build workoutkit_embed

package embeddedbridge

import _ "embed"

//go:embed libWorkoutKitSwiftUIBridge.dylib
var bridge []byte

// Payload returns the embedded WorkoutKitSwiftUIBridge bridge dylib payload.
func Payload() ([]byte, string) {
	return bridge, "libWorkoutKitSwiftUIBridge.dylib"
}
