// Code generated by applegen; DO NOT EDIT.

package charts

// Regenerate the root swiftui package from the local appledocs checkout after package-wide go:generate.
// Canonical sequence:
//   1. (cd /Users/tmc/go/src/github.com/tmc/swiftui; go generate ./...)
//   2. (cd /Volumes/tmc/go/src/github.com/tmc/appledocs; go run ./cmd/applegen swift-bridge SwiftUI --output /Users/tmc/go/src/github.com/tmc/swiftui --module github.com/tmc/swiftui --profile swiftui)

//go:generate applegen swift-bridge Charts --output . --module github.com/tmc/swiftui/charts --profile swiftui
//go:generate bash -lc "set -euo pipefail; cd internal/swift; swift build -c release --quiet --product ChartsBridge"
//go:generate bash -lc "cp internal/swift/.build/release/libChartsBridge.dylib internal/embeddedbridge/libChartsBridge.dylib"
