// Code generated by applegen; DO NOT EDIT.

package charts

// Set SWIFTUI_GENERATE_DYLIBS=1 to build a local Swift bridge dylib during generation.

//go:generate applegen swift-bridge Charts --output . --module github.com/tmc/swiftui/charts --profile swiftui
//go:generate bash -lc "set -euo pipefail; if [ \"${SWIFTUI_GENERATE_DYLIBS:-}\" = 1 ]; then cd internal/swift; swift build -c release --quiet --product ChartsBridge; fi"
