// Code generated by applegen; DO NOT EDIT.

package charts

import (
	"math"
	"strconv"
	"time"
)

// TimeUnit controls date-based chart values and axis strides.
type TimeUnit int32

const (
	TimeUnitDay TimeUnit = iota
	TimeUnitWeek
	TimeUnitMonth
	TimeUnitYear
	TimeUnitHour
	TimeUnitMinute
)

type valueKind int32

const (
	valueCategory valueKind = iota
	valueInteger
	valueNumber
	valueTime
)

// Value is a labeled plottable value used by mark dimensions.
type Value struct {
	kind valueKind

	label     string
	category  string
	integer   int
	number    float64
	timestamp time.Time
	timeUnit  TimeUnit
}

// CategoryValue creates a categorical plottable value.
func CategoryValue(label, value string) Value {
	return Value{kind: valueCategory, label: label, category: value}
}

// IntegerValue creates an integer plottable value.
func IntegerValue(label string, value int) Value {
	return Value{kind: valueInteger, label: label, integer: value}
}

// NumberValue creates a floating-point plottable value.
func NumberValue(label string, value float64) Value {
	return Value{kind: valueNumber, label: label, number: value}
}

// TimeValue creates a time-based plottable value.
func TimeValue(label string, value time.Time, unit TimeUnit) Value {
	return Value{kind: valueTime, label: label, timestamp: value, timeUnit: unit}
}

type dimRole int32

const (
	dimX dimRole = iota
	dimY
	dimXRange
	dimYRange
	dimAngle
	dimWidthRatio
	dimHeightFixed
	dimInnerRadiusRatio
	dimAngularInset
	dimMinimum
	dimLowerQuartile
	dimMedian
	dimUpperQuartile
	dimMaximum
)

// Dim is a mark dimension or dimension-like argument.
type Dim struct {
	role dimRole

	value     Value
	secondary Value
	floatV    float64
}

// X places a value on the chart's x axis.
func X(v Value) Dim { return Dim{role: dimX, value: v} }

// Y places a value on the chart's y axis.
func Y(v Value) Dim { return Dim{role: dimY, value: v} }

// XRange creates an x interval, used by marks such as RectangleMark.
func XRange(start, end Value) Dim { return Dim{role: dimXRange, value: start, secondary: end} }

// YRange creates a y interval, used by marks such as AreaMark, BarMark, and RectangleMark.
func YRange(start, end Value) Dim { return Dim{role: dimYRange, value: start, secondary: end} }

// Angle places a value on a sector mark's angle dimension.
func Angle(v Value) Dim { return Dim{role: dimAngle, value: v} }

// WidthRatio sets a rectangle or ranged bar width as a ratio of the slot width.
func WidthRatio(ratio float64) Dim { return Dim{role: dimWidthRatio, floatV: ratio} }

// HeightFixed sets a rectangle mark's height in points.
func HeightFixed(points float64) Dim { return Dim{role: dimHeightFixed, floatV: points} }

// InnerRadiusRatio sets a sector mark inner radius ratio.
func InnerRadiusRatio(ratio float64) Dim { return Dim{role: dimInnerRadiusRatio, floatV: ratio} }

// AngularInset sets a sector mark angular inset in points.
func AngularInset(points float64) Dim { return Dim{role: dimAngularInset, floatV: points} }

// Minimum sets the minimum value used by helpers such as BoxPlotMark.
func Minimum(v Value) Dim { return Dim{role: dimMinimum, value: v} }

// LowerQuartile sets the first quartile value used by helpers such as BoxPlotMark.
func LowerQuartile(v Value) Dim { return Dim{role: dimLowerQuartile, value: v} }

// Median sets the median value used by helpers such as BoxPlotMark.
func Median(v Value) Dim { return Dim{role: dimMedian, value: v} }

// UpperQuartile sets the third quartile value used by helpers such as BoxPlotMark.
func UpperQuartile(v Value) Dim { return Dim{role: dimUpperQuartile, value: v} }

// Maximum sets the maximum value used by helpers such as BoxPlotMark.
func Maximum(v Value) Dim { return Dim{role: dimMaximum, value: v} }

// Q1 is shorthand for LowerQuartile.
func Q1(v Value) Dim { return LowerQuartile(v) }

// Q3 is shorthand for UpperQuartile.
func Q3(v Value) Dim { return UpperQuartile(v) }

// Convenience x-axis helpers.

func XString(label, value string) Dim                        { return X(CategoryValue(label, value)) }
func XInt(label string, value int) Dim                       { return X(IntegerValue(label, value)) }
func XFloat(label string, value float64) Dim                 { return X(NumberValue(label, value)) }
func XDate(label string, value time.Time, unit TimeUnit) Dim { return X(TimeValue(label, value, unit)) }

// Convenience y-axis helpers.

func YString(label, value string) Dim                        { return Y(CategoryValue(label, value)) }
func YInt(label string, value int) Dim                       { return Y(IntegerValue(label, value)) }
func YFloat(label string, value float64) Dim                 { return Y(NumberValue(label, value)) }
func YDate(label string, value time.Time, unit TimeUnit) Dim { return Y(TimeValue(label, value, unit)) }

// Convenience range helpers.

func XFloatRange(label string, start, end float64) Dim {
	return XRange(NumberValue(label, start), NumberValue(label, end))
}

func XDateRange(label string, start, end time.Time, unit TimeUnit) Dim {
	return XRange(TimeValue(label, start, unit), TimeValue(label, end, unit))
}

func YFloatRange(label string, start, end float64) Dim {
	return YRange(NumberValue(label, start), NumberValue(label, end))
}

func YIntRange(label string, start, end int) Dim {
	return YRange(IntegerValue(label, start), IntegerValue(label, end))
}

type domainKind int32

const (
	domainInteger domainKind = iota
	domainNumber
	domainTime
	domainCategory
)

// Domain is a chart scale domain.
type Domain struct {
	kind domainKind

	minInt, maxInt       int
	minNumber, maxNumber float64
	startTime, endTime   time.Time
	categories           []string
}

// IntegerDomain creates an integer domain.
func IntegerDomain(min, max int) Domain {
	return Domain{kind: domainInteger, minInt: min, maxInt: max}
}

// NumberDomain creates a floating-point domain.
func NumberDomain(min, max float64) Domain {
	return Domain{kind: domainNumber, minNumber: min, maxNumber: max}
}

// TimeDomain creates a time domain.
func TimeDomain(start, end time.Time) Domain {
	return Domain{kind: domainTime, startTime: start, endTime: end}
}

// CategoryDomain creates an ordered categorical domain.
func CategoryDomain(values ...string) Domain {
	return Domain{kind: domainCategory, categories: append([]string(nil), values...)}
}

type valueFormatKind int32

const (
	valueFormatAutomatic valueFormatKind = iota
	valueFormatFixed
	valueFormatPercent
	valueFormatCompact
	valueFormatDuration
	valueFormatSuffix
)

// DurationUnit controls duration-oriented numeric formatting.
type DurationUnit int32

const (
	DurationUnitSecond DurationUnit = iota
	DurationUnitMillisecond
	DurationUnitMicrosecond
	DurationUnitNanosecond
	DurationUnitMinute
)

// ValueFormat controls numeric formatting for axis labels and exact-value annotations.
type ValueFormat struct {
	kind      valueFormatKind
	precision int
	unit      DurationUnit
	suffix    string
}

// ValueFormatAutomatic uses the framework default label formatting.
var ValueFormatAutomatic = ValueFormat{kind: valueFormatAutomatic}

// FixedFormat formats a value with fixed fractional precision.
func FixedFormat(precision int) ValueFormat {
	return ValueFormat{kind: valueFormatFixed, precision: precision}
}

// PercentFormat formats a fractional value as a percentage.
func PercentFormat(precision int) ValueFormat {
	return ValueFormat{kind: valueFormatPercent, precision: precision}
}

// CompactFormat formats a value using compact notation such as 1.2K or 4.6M.
func CompactFormat(precision int) ValueFormat {
	return ValueFormat{kind: valueFormatCompact, precision: precision}
}

// DurationFormat formats a numeric value as a duration-like label in a fixed unit.
func DurationFormat(unit DurationUnit, precision int) ValueFormat {
	return ValueFormat{kind: valueFormatDuration, unit: unit, precision: precision}
}

// SuffixFormat formats a value with fixed precision and a literal suffix.
func SuffixFormat(suffix string, precision int) ValueFormat {
	return ValueFormat{kind: valueFormatSuffix, suffix: suffix, precision: precision}
}

// Format formats a numeric value using the configured rules.
func (f ValueFormat) Format(value float64) string {
	switch f.kind {
	case valueFormatPercent:
		return formatFixedValue(value*100, f.precision) + "%"
	case valueFormatCompact:
		return formatCompactValue(value, f.precision)
	case valueFormatDuration:
		return formatDurationValue(value, f.unit, f.precision)
	case valueFormatSuffix:
		return formatFixedValue(value, f.precision) + f.suffix
	case valueFormatFixed:
		fallthrough
	default:
		return formatFixedValue(value, f.precision)
	}
}

func formatFixedValue(value float64, precision int) string {
	if math.IsNaN(value) || math.IsInf(value, 0) {
		return strconv.FormatFloat(value, 'g', -1, 64)
	}
	if precision < 0 {
		precision = 0
	}
	return strconv.FormatFloat(value, 'f', precision, 64)
}

func formatCompactValue(value float64, precision int) string {
	if math.IsNaN(value) || math.IsInf(value, 0) {
		return strconv.FormatFloat(value, 'g', -1, 64)
	}
	abs := math.Abs(value)
	scale := 1.0
	suffix := ""
	switch {
	case abs >= 1e12:
		scale, suffix = 1e12, "T"
	case abs >= 1e9:
		scale, suffix = 1e9, "B"
	case abs >= 1e6:
		scale, suffix = 1e6, "M"
	case abs >= 1e3:
		scale, suffix = 1e3, "K"
	}
	return formatFixedValue(value/scale, precision) + suffix
}

func formatDurationValue(value float64, unit DurationUnit, precision int) string {
	scale, suffix := durationUnitSpec(unit)
	return formatFixedValue(value*scale, precision) + suffix
}

func durationUnitSpec(unit DurationUnit) (float64, string) {
	switch unit {
	case DurationUnitMinute:
		return 1.0 / 60.0, " min"
	case DurationUnitMillisecond:
		return 1e3, " ms"
	case DurationUnitMicrosecond:
		return 1e6, " µs"
	case DurationUnitNanosecond:
		return 1e9, " ns"
	default:
		return 1.0, " s"
	}
}
