// Code generated by applegen; DO NOT EDIT.

package charts

import (
	"encoding/json"
	"strconv"
	"sync"
	"time"

	"github.com/tmc/swiftui"
)

type scaleTypeKind int32

const (
	scaleTypeAutomatic scaleTypeKind = iota
	scaleTypeLinear
	scaleTypeLog
	scaleTypeDate
	scaleTypeCategory
	scaleTypePower
	scaleTypeSquareRoot
	scaleTypeSymmetricLog
)

// ScaleType controls a chart axis scale type.
type ScaleType struct {
	kind  scaleTypeKind
	value float64
}

var (
	ScaleTypeAutomatic  = ScaleType{kind: scaleTypeAutomatic}
	ScaleTypeLinear     = ScaleType{kind: scaleTypeLinear}
	ScaleTypeLog        = ScaleType{kind: scaleTypeLog}
	ScaleTypeDate       = ScaleType{kind: scaleTypeDate}
	ScaleTypeCategory   = ScaleType{kind: scaleTypeCategory}
	ScaleTypeSquareRoot = ScaleType{kind: scaleTypeSquareRoot}
)

// ScaleTypePower returns a power scale with the provided exponent.
func ScaleTypePower(exponent float64) ScaleType {
	return ScaleType{kind: scaleTypePower, value: exponent}
}

// ScaleTypeSymmetricLog returns a symmetric-log scale with the provided slope near zero.
func ScaleTypeSymmetricLog(slopeAtZero float64) ScaleType {
	return ScaleType{kind: scaleTypeSymmetricLog, value: slopeAtZero}
}

// AxisPreset controls the preset used for axis marks.
type AxisPreset int32

const (
	AxisPresetAutomatic AxisPreset = iota
	AxisPresetAligned
	AxisPresetExtended
	AxisPresetInset
)

// AxisPosition controls where an axis is drawn.
type AxisPosition int32

const (
	AxisPositionAutomatic AxisPosition = iota
	AxisPositionBottom
	AxisPositionTop
	AxisPositionLeading
	AxisPositionTrailing
)

// LabelAlignment controls label alignment for axis labels.
type LabelAlignment int32

const (
	LabelAlignmentCenter LabelAlignment = iota
	LabelAlignmentLeading
	LabelAlignmentTrailing
	LabelAlignmentTop
	LabelAlignmentBottom
	LabelAlignmentTopLeading
	LabelAlignmentTopTrailing
	LabelAlignmentBottomLeading
	LabelAlignmentBottomTrailing
)

type axisValuesKind int32

const (
	axisValuesAutomatic axisValuesKind = iota
	axisValuesAutomaticCount
	axisValuesAutomaticMinimumStride
	axisValuesNumericStride
	axisValuesTimeStride
	axisValuesExplicit
)

// AxisValues controls which ticks are emitted.
type AxisValues struct {
	kind axisValuesKind

	step            float64
	unit            TimeUnit
	count           int
	desiredCount    int
	roundLowerBound bool
	roundUpperBound bool
	values          []Value
}

// AutomaticAxisValues uses the framework default tick placement.
func AutomaticAxisValues() AxisValues { return AxisValues{kind: axisValuesAutomatic} }

// AutomaticAxisValuesCount uses automatic placement with a desired tick count.
func AutomaticAxisValuesCount(desiredCount int) AxisValues {
	return AxisValues{kind: axisValuesAutomaticCount, desiredCount: desiredCount}
}

// AutomaticAxisValuesMinimumStride uses automatic placement with a minimum stride.
func AutomaticAxisValuesMinimumStride(minimumStride float64, desiredCount int) AxisValues {
	return AxisValues{
		kind:         axisValuesAutomaticMinimumStride,
		step:         minimumStride,
		desiredCount: desiredCount,
	}
}

// NumericStride uses a numeric stride.
func NumericStride(step float64) AxisValues {
	return AxisValues{kind: axisValuesNumericStride, step: step}
}

// NumericStrideRounded uses a numeric stride with explicit rounding.
func NumericStrideRounded(step float64, roundLowerBound, roundUpperBound bool) AxisValues {
	return AxisValues{
		kind:            axisValuesNumericStride,
		step:            step,
		roundLowerBound: roundLowerBound,
		roundUpperBound: roundUpperBound,
	}
}

// TimeStride uses a calendar-based stride.
func TimeStride(unit TimeUnit) AxisValues { return AxisValues{kind: axisValuesTimeStride, unit: unit} }

// TimeStrideCount uses a calendar-based stride with an explicit count.
func TimeStrideCount(unit TimeUnit, count int) AxisValues {
	return AxisValues{kind: axisValuesTimeStride, unit: unit, count: count}
}

// TimeStrideRounded uses a calendar-based stride with an explicit count and rounding.
func TimeStrideRounded(unit TimeUnit, count int, roundLowerBound, roundUpperBound bool) AxisValues {
	return AxisValues{
		kind:            axisValuesTimeStride,
		unit:            unit,
		count:           count,
		roundLowerBound: roundLowerBound,
		roundUpperBound: roundUpperBound,
	}
}

// AxisValueList uses an explicit ordered list of tick values.
func AxisValueList(values ...Value) AxisValues {
	return AxisValues{kind: axisValuesExplicit, values: append([]Value(nil), values...)}
}

type axisTickLengthKind int32

const (
	axisTickLengthAutomatic axisTickLengthKind = iota
	axisTickLengthLabel
	axisTickLengthLongestLabel
)

// AxisTickLength controls native tick length behavior.
type AxisTickLength struct {
	kind  axisTickLengthKind
	value float64
}

var AxisTickLengthAutomatic = AxisTickLength{kind: axisTickLengthAutomatic}

// AxisTickLengthLabel matches the current label length.
func AxisTickLengthLabel(extendPastBy float64) AxisTickLength {
	return AxisTickLength{kind: axisTickLengthLabel, value: extendPastBy}
}

// AxisTickLengthLongestLabel matches the longest visible label length.
func AxisTickLengthLongestLabel(extendPastBy float64) AxisTickLength {
	return AxisTickLength{kind: axisTickLengthLongestLabel, value: extendPastBy}
}

type axisOptionKind int32

const (
	axisOptionPreset axisOptionKind = iota
	axisOptionPosition
	axisOptionValues
	axisOptionGrid
	axisOptionGridStyled
	axisOptionTicks
	axisOptionTicksStyled
	axisOptionLabels
	axisOptionDateLabels
	axisOptionValueFormat
)

// AxisOption configures an axis.
type AxisOption struct {
	kind axisOptionKind

	preset   AxisPreset
	position AxisPosition
	values   AxisValues
	centered bool
	pattern  string
	style    LineStyle
	length   AxisTickLength
	format   ValueFormat
}

// AxisPresetOption sets the axis preset.
func AxisPresetOption(preset AxisPreset) AxisOption {
	return AxisOption{kind: axisOptionPreset, preset: preset}
}

// AxisPositionOption sets the axis position.
func AxisPositionOption(position AxisPosition) AxisOption {
	return AxisOption{kind: axisOptionPosition, position: position}
}

// AxisValuesOption sets the axis values configuration.
func AxisValuesOption(values AxisValues) AxisOption {
	return AxisOption{kind: axisOptionValues, values: values}
}

// AxisGridLines enables grid lines.
func AxisGridLines() AxisOption { return AxisOption{kind: axisOptionGrid} }

// AxisGridLinesStyled enables grid lines with styling.
func AxisGridLinesStyled(style LineStyle, centered bool) AxisOption {
	return AxisOption{
		kind:     axisOptionGridStyled,
		style:    style,
		centered: centered,
	}
}

// AxisTicks enables ticks.
func AxisTicks() AxisOption { return AxisOption{kind: axisOptionTicks} }

// AxisTicksStyled enables ticks with styling.
func AxisTicksStyled(length AxisTickLength, style LineStyle, centered bool) AxisOption {
	return AxisOption{
		kind:     axisOptionTicksStyled,
		length:   length,
		style:    style,
		centered: centered,
	}
}

// AxisLabels enables default labels.
func AxisLabels() AxisOption { return AxisOption{kind: axisOptionLabels} }

// AxisDateLabels enables date labels using a limited format pattern such as "MMM", "MM/dd", or "HH:mm".
func AxisDateLabels(pattern string, centered bool) AxisOption {
	return AxisOption{kind: axisOptionDateLabels, pattern: pattern, centered: centered}
}

// AxisValueLabels enables numeric labels with an explicit formatter.
func AxisValueLabels(format ValueFormat) AxisOption {
	return AxisOption{kind: axisOptionValueFormat, format: format}
}

// AxisTickCount targets an approximate tick count using the framework's automatic placement.
func AxisTickCount(desiredCount int) AxisOption {
	return AxisValuesOption(AutomaticAxisValuesCount(desiredCount))
}

// AxisTickMinimumStride targets automatic placement with a minimum stride.
func AxisTickMinimumStride(minimumStride float64, desiredCount int) AxisOption {
	return AxisValuesOption(AutomaticAxisValuesMinimumStride(minimumStride, desiredCount))
}

// AxisTickStride uses a fixed numeric stride.
func AxisTickStride(step float64) AxisOption {
	return AxisValuesOption(NumericStride(step))
}

// AxisTickStrideRounded uses a fixed numeric stride with explicit bound rounding.
func AxisTickStrideRounded(step float64, roundLowerBound, roundUpperBound bool) AxisOption {
	return AxisValuesOption(NumericStrideRounded(step, roundLowerBound, roundUpperBound))
}

// AxisTickValues uses an explicit ordered list of tick values.
func AxisTickValues(values ...Value) AxisOption {
	return AxisValuesOption(AxisValueList(values...))
}

// AxisConfig configures chart axes.
type AxisConfig struct {
	hidden bool

	preset        AxisPreset
	position      AxisPosition
	values        AxisValues
	showGrid      bool
	gridStyle     LineStyle
	gridCentered  bool
	showTicks     bool
	tickStyle     LineStyle
	tickCentered  bool
	tickLength    AxisTickLength
	showLabels    bool
	datePattern   string
	labelCentered bool
	valueFormat   ValueFormat
}

// AxisHidden hides an axis.
var AxisHidden = AxisConfig{hidden: true}

// AxisMarks configures a visible axis.
func AxisMarks(opts ...AxisOption) AxisConfig {
	cfg := AxisConfig{
		preset:     AxisPresetAutomatic,
		position:   AxisPositionAutomatic,
		values:     AutomaticAxisValues(),
		tickLength: AxisTickLengthAutomatic,
	}
	for _, opt := range opts {
		switch opt.kind {
		case axisOptionPreset:
			cfg.preset = opt.preset
		case axisOptionPosition:
			cfg.position = opt.position
		case axisOptionValues:
			cfg.values = opt.values
		case axisOptionGrid:
			cfg.showGrid = true
		case axisOptionGridStyled:
			cfg.showGrid = true
			cfg.gridStyle = opt.style
			cfg.gridCentered = opt.centered
		case axisOptionTicks:
			cfg.showTicks = true
		case axisOptionTicksStyled:
			cfg.showTicks = true
			cfg.tickStyle = opt.style
			cfg.tickCentered = opt.centered
			cfg.tickLength = opt.length
		case axisOptionLabels:
			cfg.showLabels = true
		case axisOptionDateLabels:
			cfg.showLabels = true
			cfg.datePattern = opt.pattern
			cfg.labelCentered = opt.centered
		case axisOptionValueFormat:
			cfg.showLabels = true
			cfg.valueFormat = opt.format
		}
	}
	return cfg
}

type axisLabel struct {
	text         string
	position     AnnotationPosition
	alignment    LabelAlignment
	hasPosition  bool
	hasAlignment bool
	hasSpacing   bool
	spacing      float64
}

// AxisLabelOption configures chart axis labels.
type AxisLabelOption struct {
	kind axisLabelOptionKind

	position  AnnotationPosition
	alignment LabelAlignment
	spacing   float64
}

type axisLabelOptionKind int32

const (
	axisLabelOptionPosition axisLabelOptionKind = iota
	axisLabelOptionAlignment
	axisLabelOptionSpacing
)

// AxisLabelPosition sets the axis label position.
func AxisLabelPosition(position AnnotationPosition) AxisLabelOption {
	return AxisLabelOption{kind: axisLabelOptionPosition, position: position}
}

// AxisLabelAlignmentOption sets the axis label alignment.
func AxisLabelAlignmentOption(alignment LabelAlignment) AxisLabelOption {
	return AxisLabelOption{kind: axisLabelOptionAlignment, alignment: alignment}
}

// AxisLabelSpacing sets the axis label spacing.
func AxisLabelSpacing(spacing float64) AxisLabelOption {
	return AxisLabelOption{kind: axisLabelOptionSpacing, spacing: spacing}
}

type axisStyleKind int32

const (
	axisStyleForegroundColor axisStyleKind = iota
	axisStyleOpacity
	axisStyleBackgroundColor
	axisStyleBackgroundView
	axisStyleOverlayView
)

// AxisStyleOption configures axis-content styling for chartXAxisStyle/chartYAxisStyle.
type AxisStyleOption struct {
	kind axisStyleKind

	color   swiftui.Color
	opacity float64
	view    swiftui.View
}

// AxisStyleForeground applies a foreground style to axis content.
func AxisStyleForeground(color swiftui.Color) AxisStyleOption {
	return AxisStyleOption{kind: axisStyleForegroundColor, color: color}
}

// AxisStyleOpacity applies opacity to axis content.
func AxisStyleOpacity(opacity float64) AxisStyleOption {
	return AxisStyleOption{kind: axisStyleOpacity, opacity: opacity}
}

// AxisStyleBackgroundColor applies a background color behind axis content.
func AxisStyleBackgroundColor(color swiftui.Color) AxisStyleOption {
	return AxisStyleOption{kind: axisStyleBackgroundColor, color: color}
}

// AxisStyleBackgroundView places a SwiftUI view behind axis content.
func AxisStyleBackgroundView(view swiftui.View) AxisStyleOption {
	return AxisStyleOption{kind: axisStyleBackgroundView, view: view}
}

// AxisStyleOverlayView places a SwiftUI view over axis content.
func AxisStyleOverlayView(view swiftui.View) AxisStyleOption {
	return AxisStyleOption{kind: axisStyleOverlayView, view: view}
}

// StyleScaleEntry maps a series key to a color.
type StyleScaleEntry struct {
	Key   string
	Color swiftui.Color
}

// StyleScale creates a categorical foreground-style scale entry.
func StyleScale(key string, color swiftui.Color) StyleScaleEntry {
	return StyleScaleEntry{Key: key, Color: color}
}

// SymbolScaleEntry maps a series key to a symbol shape.
type SymbolScaleEntry struct {
	Key    string
	Symbol SymbolKind
}

// SymbolScale creates a categorical symbol-scale entry.
func SymbolScale(key string, symbol SymbolKind) SymbolScaleEntry {
	return SymbolScaleEntry{Key: key, Symbol: symbol}
}

// LineStyleScaleEntry maps a series key to a line style.
type LineStyleScaleEntry struct {
	Key   string
	Style LineStyle
}

// LineStyleScale creates a categorical line-style scale entry.
func LineStyleScale(key string, style LineStyle) LineStyleScaleEntry {
	return LineStyleScaleEntry{Key: key, Style: style}
}

// SymbolSizeScaleEntry maps a series key to a symbol size.
type SymbolSizeScaleEntry struct {
	Key  string
	Size float64
}

// SymbolSizeScale creates a categorical symbol-size scale entry.
func SymbolSizeScale(key string, size float64) SymbolSizeScaleEntry {
	return SymbolSizeScaleEntry{Key: key, Size: size}
}

// LegendVisibility controls legend visibility.
type LegendVisibility int32

const (
	LegendVisibilityAutomatic LegendVisibility = iota
	LegendVisibilityVisible
	LegendVisibilityHidden
)

// LegendPosition controls legend placement.
type LegendPosition int32

const (
	LegendPositionAutomatic LegendPosition = iota
	LegendPositionTop
	LegendPositionBottom
	LegendPositionLeading
	LegendPositionTrailing
	LegendPositionOverlay
)

// LegendAlignment controls legend alignment.
type LegendAlignment int32

const (
	LegendAlignmentCenter LegendAlignment = iota
	LegendAlignmentLeading
	LegendAlignmentTrailing
	LegendAlignmentTop
	LegendAlignmentBottom
)

// LegendConfig configures the chart legend.
type LegendConfig struct {
	Visibility LegendVisibility
	Position   LegendPosition
	Alignment  LegendAlignment
	Spacing    float64
}

// LegendHidden hides the legend.
var LegendHidden = LegendConfig{Visibility: LegendVisibilityHidden}

// LegendVisible returns a visible legend configuration.
func LegendVisible(position LegendPosition, alignment LegendAlignment, spacing float64) LegendConfig {
	return LegendConfig{
		Visibility: LegendVisibilityVisible,
		Position:   position,
		Alignment:  alignment,
		Spacing:    spacing,
	}
}

// LegendCompact returns a visible legend tuned for dense short series labels.
func LegendCompact(position LegendPosition, alignment LegendAlignment) LegendConfig {
	return LegendVisible(position, alignment, 4)
}

// PlotStyleOption configures the chart plot area.
type PlotStyleOption struct {
	kind plotStyleKind

	color  swiftui.Color
	width  float64
	view   swiftui.View
	top    float64
	right  float64
	bottom float64
	left   float64
}

type plotStyleKind int32

const (
	plotStyleBackgroundColor plotStyleKind = iota
	plotStyleBorder
	plotStyleBackgroundView
	plotStyleOverlayView
	plotStyleInset
)

// PlotBackgroundColor sets a solid plot-area background color.
func PlotBackgroundColor(color swiftui.Color) PlotStyleOption {
	return PlotStyleOption{kind: plotStyleBackgroundColor, color: color}
}

// PlotBorder draws a border around the plot area.
func PlotBorder(color swiftui.Color, width float64) PlotStyleOption {
	return PlotStyleOption{kind: plotStyleBorder, color: color, width: width}
}

// PlotBackgroundView places a SwiftUI view behind the plot area.
func PlotBackgroundView(view swiftui.View) PlotStyleOption {
	return PlotStyleOption{kind: plotStyleBackgroundView, view: view}
}

// PlotOverlayView places a SwiftUI view over the plot area.
func PlotOverlayView(view swiftui.View) PlotStyleOption {
	return PlotStyleOption{kind: plotStyleOverlayView, view: view}
}

// PlotInset adds plot-area padding in points.
func PlotInset(top, right, bottom, left float64) PlotStyleOption {
	return PlotStyleOption{
		kind:   plotStyleInset,
		top:    top,
		right:  right,
		bottom: bottom,
		left:   left,
	}
}

// PlotInsetAll adds equal plot-area padding on every edge in points.
func PlotInsetAll(padding float64) PlotStyleOption {
	return PlotInset(padding, padding, padding, padding)
}

type positionScaleRangeKind int32

const (
	positionScaleRangePlotDimension positionScaleRangeKind = iota
)

// PositionScaleRange controls a native positional scale range.
type PositionScaleRange struct {
	kind         positionScaleRangeKind
	startPadding float64
	endPadding   float64
}

// PlotDimensionRange uses the plot dimension with optional start and end padding.
func PlotDimensionRange(startPadding, endPadding float64) PositionScaleRange {
	return PositionScaleRange{
		kind:         positionScaleRangePlotDimension,
		startPadding: startPadding,
		endPadding:   endPadding,
	}
}

// ScrollAxis controls chart scrolling.
type ScrollAxis int32

const (
	ScrollAxisNone ScrollAxis = iota
	ScrollAxisHorizontal
	ScrollAxisVertical
	ScrollAxisBoth
)

type scrollPositionKind int32

const (
	scrollPositionNumber scrollPositionKind = iota
	scrollPositionTime
)

type scrollPositionAxis int32

const (
	scrollPositionAxisX scrollPositionAxis = iota
	scrollPositionAxisY
)

type scrollPosition struct {
	kind scrollPositionKind

	axis   scrollPositionAxis
	number float64
	time   int64
}

type foregroundStyleScaleConfig struct {
	entries   []StyleScaleEntry
	scaleType *ScaleType
}

type symbolScaleConfig struct {
	entries []SymbolScaleEntry
}

type lineStyleScaleConfig struct {
	entries []LineStyleScaleEntry
}

type symbolSizeScaleConfig struct {
	entries   []SymbolSizeScaleEntry
	scaleType *ScaleType
}

// ChartView is a lazily-built Charts view.
type ChartView struct {
	builder *chartBuilder
}

type chartBuilder struct {
	marks []Mark

	xDomain    *Domain
	yDomain    *Domain
	xRange     *PositionScaleRange
	yRange     *PositionScaleRange
	xScaleType ScaleType
	yScaleType ScaleType

	xAxis      *AxisConfig
	yAxis      *AxisConfig
	xAxisLabel *axisLabel
	yAxisLabel *axisLabel
	xAxisStyle []AxisStyleOption
	yAxisStyle []AxisStyleOption

	styleScale      foregroundStyleScaleConfig
	symbolScale     symbolScaleConfig
	lineStyleScale  lineStyleScaleConfig
	symbolSizeScale symbolSizeScaleConfig
	legend          *LegendConfig
	plot            []PlotStyleOption

	scrollAxes     ScrollAxis
	scrollPosition *scrollPosition
	visibleLength  *float64

	xSelection      SelectionValueBinding
	xSelectionRange SelectionRangeBinding
	ySelection      SelectionValueBinding
	ySelectionRange SelectionRangeBinding
	angleSelection  SelectionValueBinding
	scrollTarget    *ScrollTargetBehavior
	xScrollBinding  ScrollPositionBinding
	yScrollBinding  ScrollPositionBinding
	xVisibleLength  *visibleDomainLength
	yVisibleLength  *visibleDomainLength
	overlays        []proxyLayer
	backgrounds     []proxyLayer
	gesture         *ProxyGesture

	once sync.Once
	view swiftui.View
}

// Chart creates a chart from marks.
func Chart(marks ...Mark) ChartView {
	return ChartView{
		builder: &chartBuilder{
			marks:      append([]Mark(nil), marks...),
			xScaleType: ScaleTypeAutomatic,
			yScaleType: ScaleTypeAutomatic,
			scrollAxes: ScrollAxisNone,
		},
	}
}

func (c ChartView) cloneBuilder() *chartBuilder {
	if c.builder == nil {
		return &chartBuilder{
			xScaleType: ScaleTypeAutomatic,
			yScaleType: ScaleTypeAutomatic,
		}
	}
	out := &chartBuilder{
		marks:           append([]Mark(nil), c.builder.marks...),
		xScaleType:      c.builder.xScaleType,
		yScaleType:      c.builder.yScaleType,
		xRange:          c.builder.xRange,
		yRange:          c.builder.yRange,
		xAxis:           c.builder.xAxis,
		yAxis:           c.builder.yAxis,
		xAxisLabel:      c.builder.xAxisLabel,
		yAxisLabel:      c.builder.yAxisLabel,
		xSelection:      c.builder.xSelection,
		xSelectionRange: c.builder.xSelectionRange,
		ySelection:      c.builder.ySelection,
		ySelectionRange: c.builder.ySelectionRange,
		angleSelection:  c.builder.angleSelection,
		scrollAxes:      c.builder.scrollAxes,
		scrollPosition:  c.builder.scrollPosition,
		visibleLength:   c.builder.visibleLength,
		scrollTarget:    c.builder.scrollTarget,
		xScrollBinding:  c.builder.xScrollBinding,
		yScrollBinding:  c.builder.yScrollBinding,
		xVisibleLength:  c.builder.xVisibleLength,
		yVisibleLength:  c.builder.yVisibleLength,
		gesture:         c.builder.gesture,
		legend:          c.builder.legend,
		plot:            append([]PlotStyleOption(nil), c.builder.plot...),
		styleScale: foregroundStyleScaleConfig{
			scaleType: c.builder.styleScale.scaleType,
		},
	}
	if c.builder.xDomain != nil {
		d := *c.builder.xDomain
		d.categories = append([]string(nil), d.categories...)
		out.xDomain = &d
	}
	if c.builder.yDomain != nil {
		d := *c.builder.yDomain
		d.categories = append([]string(nil), d.categories...)
		out.yDomain = &d
	}
	if c.builder.xRange != nil {
		r := *c.builder.xRange
		out.xRange = &r
	}
	if c.builder.yRange != nil {
		r := *c.builder.yRange
		out.yRange = &r
	}
	if c.builder.xAxis != nil {
		cfg := *c.builder.xAxis
		out.xAxis = &cfg
	}
	if c.builder.yAxis != nil {
		cfg := *c.builder.yAxis
		out.yAxis = &cfg
	}
	if c.builder.xAxisLabel != nil {
		label := *c.builder.xAxisLabel
		out.xAxisLabel = &label
	}
	if c.builder.yAxisLabel != nil {
		label := *c.builder.yAxisLabel
		out.yAxisLabel = &label
	}
	out.xAxisStyle = append([]AxisStyleOption(nil), c.builder.xAxisStyle...)
	out.yAxisStyle = append([]AxisStyleOption(nil), c.builder.yAxisStyle...)
	if c.builder.legend != nil {
		cfg := *c.builder.legend
		out.legend = &cfg
	}
	out.styleScale.entries = append([]StyleScaleEntry(nil), c.builder.styleScale.entries...)
	out.symbolScale.entries = append([]SymbolScaleEntry(nil), c.builder.symbolScale.entries...)
	out.lineStyleScale.entries = append([]LineStyleScaleEntry(nil), c.builder.lineStyleScale.entries...)
	out.symbolSizeScale.entries = append([]SymbolSizeScaleEntry(nil), c.builder.symbolSizeScale.entries...)
	if c.builder.styleScale.scaleType != nil {
		scaleType := *c.builder.styleScale.scaleType
		out.styleScale.scaleType = &scaleType
	}
	if c.builder.symbolSizeScale.scaleType != nil {
		scaleType := *c.builder.symbolSizeScale.scaleType
		out.symbolSizeScale.scaleType = &scaleType
	}
	if c.builder.visibleLength != nil {
		v := *c.builder.visibleLength
		out.visibleLength = &v
	}
	if c.builder.scrollPosition != nil {
		pos := *c.builder.scrollPosition
		out.scrollPosition = &pos
	}
	if c.builder.scrollTarget != nil {
		target := *c.builder.scrollTarget
		out.scrollTarget = &target
	}
	if c.builder.xVisibleLength != nil {
		value := *c.builder.xVisibleLength
		out.xVisibleLength = &value
	}
	if c.builder.yVisibleLength != nil {
		value := *c.builder.yVisibleLength
		out.yVisibleLength = &value
	}
	out.overlays = append([]proxyLayer(nil), c.builder.overlays...)
	out.backgrounds = append([]proxyLayer(nil), c.builder.backgrounds...)
	if c.builder.gesture != nil {
		gesture := *c.builder.gesture
		out.gesture = &gesture
	}
	out.view = swiftui.View{}
	return out
}

func (c ChartView) with(mut func(*chartBuilder)) ChartView {
	builder := c.cloneBuilder()
	mut(builder)
	return ChartView{builder: builder}
}

// ChartXScaleDomain sets the x-axis scale domain.
func (c ChartView) ChartXScaleDomain(domain Domain) ChartView {
	return c.with(func(b *chartBuilder) { d := domain; b.xDomain = &d })
}

// ChartYScaleDomain sets the y-axis scale domain.
func (c ChartView) ChartYScaleDomain(domain Domain) ChartView {
	return c.with(func(b *chartBuilder) { d := domain; b.yDomain = &d })
}

// ChartXScaleRange sets the x-axis scale range.
func (c ChartView) ChartXScaleRange(rng PositionScaleRange) ChartView {
	return c.with(func(b *chartBuilder) { r := rng; b.xRange = &r })
}

// ChartYScaleRange sets the y-axis scale range.
func (c ChartView) ChartYScaleRange(rng PositionScaleRange) ChartView {
	return c.with(func(b *chartBuilder) { r := rng; b.yRange = &r })
}

// ChartXScaleType sets the x-axis scale type.
func (c ChartView) ChartXScaleType(scaleType ScaleType) ChartView {
	return c.with(func(b *chartBuilder) { b.xScaleType = scaleType })
}

// ChartYScaleType sets the y-axis scale type.
func (c ChartView) ChartYScaleType(scaleType ScaleType) ChartView {
	return c.with(func(b *chartBuilder) { b.yScaleType = scaleType })
}

// ChartXAxis configures the x axis.
func (c ChartView) ChartXAxis(config AxisConfig) ChartView {
	return c.with(func(b *chartBuilder) { cfg := config; b.xAxis = &cfg })
}

// ChartYAxis configures the y axis.
func (c ChartView) ChartYAxis(config AxisConfig) ChartView {
	return c.with(func(b *chartBuilder) { cfg := config; b.yAxis = &cfg })
}

// ChartXAxisLabel sets the x-axis label.
func (c ChartView) ChartXAxisLabel(text string, opts ...AxisLabelOption) ChartView {
	return c.with(func(b *chartBuilder) {
		label := axisLabel{text: text}
		for _, opt := range opts {
			switch opt.kind {
			case axisLabelOptionPosition:
				label.position = opt.position
				label.hasPosition = true
			case axisLabelOptionAlignment:
				label.alignment = opt.alignment
				label.hasAlignment = true
			case axisLabelOptionSpacing:
				label.spacing = opt.spacing
				label.hasSpacing = true
			}
		}
		b.xAxisLabel = &label
	})
}

// ChartYAxisLabel sets the y-axis label.
func (c ChartView) ChartYAxisLabel(text string, opts ...AxisLabelOption) ChartView {
	return c.with(func(b *chartBuilder) {
		label := axisLabel{text: text}
		for _, opt := range opts {
			switch opt.kind {
			case axisLabelOptionPosition:
				label.position = opt.position
				label.hasPosition = true
			case axisLabelOptionAlignment:
				label.alignment = opt.alignment
				label.hasAlignment = true
			case axisLabelOptionSpacing:
				label.spacing = opt.spacing
				label.hasSpacing = true
			}
		}
		b.yAxisLabel = &label
	})
}

// ChartXAxisStyle styles x-axis content using a practical subset of chartXAxisStyle.
func (c ChartView) ChartXAxisStyle(opts ...AxisStyleOption) ChartView {
	return c.with(func(b *chartBuilder) {
		b.xAxisStyle = append(append([]AxisStyleOption(nil), b.xAxisStyle...), opts...)
	})
}

// ChartYAxisStyle styles y-axis content using a practical subset of chartYAxisStyle.
func (c ChartView) ChartYAxisStyle(opts ...AxisStyleOption) ChartView {
	return c.with(func(b *chartBuilder) {
		b.yAxisStyle = append(append([]AxisStyleOption(nil), b.yAxisStyle...), opts...)
	})
}

// ChartForegroundStyleScale configures a categorical foreground-style scale.
func (c ChartView) ChartForegroundStyleScale(entries ...StyleScaleEntry) ChartView {
	return c.with(func(b *chartBuilder) {
		b.styleScale.entries = append(append([]StyleScaleEntry(nil), b.styleScale.entries...), entries...)
	})
}

// ChartForegroundStyleScaleType sets the foreground-style scale type.
func (c ChartView) ChartForegroundStyleScaleType(scaleType ScaleType) ChartView {
	return c.with(func(b *chartBuilder) {
		value := scaleType
		b.styleScale.scaleType = &value
	})
}

// ChartSymbolScale configures a categorical symbol scale.
func (c ChartView) ChartSymbolScale(entries ...SymbolScaleEntry) ChartView {
	return c.with(func(b *chartBuilder) {
		b.symbolScale.entries = append(append([]SymbolScaleEntry(nil), b.symbolScale.entries...), entries...)
	})
}

// ChartLineStyleScale configures a categorical line-style scale.
func (c ChartView) ChartLineStyleScale(entries ...LineStyleScaleEntry) ChartView {
	return c.with(func(b *chartBuilder) {
		b.lineStyleScale.entries = append(append([]LineStyleScaleEntry(nil), b.lineStyleScale.entries...), entries...)
	})
}

// ChartSymbolSizeScale configures a categorical symbol-size scale.
func (c ChartView) ChartSymbolSizeScale(entries ...SymbolSizeScaleEntry) ChartView {
	return c.with(func(b *chartBuilder) {
		b.symbolSizeScale.entries = append(append([]SymbolSizeScaleEntry(nil), b.symbolSizeScale.entries...), entries...)
	})
}

// ChartSymbolSizeScaleType sets the symbol-size scale type.
func (c ChartView) ChartSymbolSizeScaleType(scaleType ScaleType) ChartView {
	return c.with(func(b *chartBuilder) {
		value := scaleType
		b.symbolSizeScale.scaleType = &value
	})
}

// ChartLegend configures legend visibility and placement.
func (c ChartView) ChartLegend(config LegendConfig) ChartView {
	return c.with(func(b *chartBuilder) { cfg := config; b.legend = &cfg })
}

// ChartPlotStyle configures the plot area.
func (c ChartView) ChartPlotStyle(opts ...PlotStyleOption) ChartView {
	return c.with(func(b *chartBuilder) {
		b.plot = append(append([]PlotStyleOption(nil), b.plot...), opts...)
	})
}

// ChartScrollableAxes enables scrolling along the selected axes.
func (c ChartView) ChartScrollableAxes(axis ScrollAxis) ChartView {
	return c.with(func(b *chartBuilder) { b.scrollAxes = axis })
}

// ChartScrollPositionInitialXNumber sets the initial numeric scroll position.
func (c ChartView) ChartScrollPositionInitialXNumber(value float64) ChartView {
	return c.with(func(b *chartBuilder) {
		b.scrollPosition = &scrollPosition{kind: scrollPositionNumber, axis: scrollPositionAxisX, number: value}
	})
}

// ChartScrollPositionInitialXDate sets the initial time-based scroll position.
func (c ChartView) ChartScrollPositionInitialXDate(value time.Time) ChartView {
	return c.with(func(b *chartBuilder) {
		b.scrollPosition = &scrollPosition{kind: scrollPositionTime, axis: scrollPositionAxisX, time: value.UnixMilli()}
	})
}

// ChartScrollPositionInitialYNumber sets the initial numeric y scroll position.
func (c ChartView) ChartScrollPositionInitialYNumber(value float64) ChartView {
	return c.with(func(b *chartBuilder) {
		b.scrollPosition = &scrollPosition{kind: scrollPositionNumber, axis: scrollPositionAxisY, number: value}
	})
}

// ChartScrollPositionInitialYDate sets the initial time-based y scroll position.
func (c ChartView) ChartScrollPositionInitialYDate(value time.Time) ChartView {
	return c.with(func(b *chartBuilder) {
		b.scrollPosition = &scrollPosition{kind: scrollPositionTime, axis: scrollPositionAxisY, time: value.UnixMilli()}
	})
}

// ChartXVisibleDomainLength sets the visible x-domain length for scrollable charts.
//
// For time-based charts, length is interpreted as seconds.
func (c ChartView) ChartXVisibleDomainLength(length float64) ChartView {
	return c.with(func(b *chartBuilder) {
		v := length
		b.visibleLength = &v
	})
}

// ChartYVisibleDomainLength sets the visible y-domain length for scrollable charts.
//
// For time-based charts, length is interpreted as seconds.
func (c ChartView) ChartYVisibleDomainLength(length float64) ChartView {
	return c.with(func(b *chartBuilder) {
		value := VisibleDomainNumeric(length)
		b.yVisibleLength = &value
	})
}

func (c ChartView) build() swiftui.View {
	if c.builder == nil {
		return swiftui.ViewFromPointer(0)
	}
	c.builder.once.Do(func() {
		data, err := json.Marshal(c.builder.toSpec())
		if err != nil || len(data) == 0 {
			return
		}
		ptr := _CHBuildChart((*byte)(&data[0]), int32(len(data)))
		c.builder.view = swiftui.ViewFromPointer(ptr)
	})
	return c.builder.view
}

func (c ChartView) viewPtr() uintptr { return c.build().Pointer() }

// Pointer returns the underlying Swift pointer.
func (c ChartView) Pointer() uintptr { return c.build().Pointer() }

// View returns the underlying SwiftUI view.
func (c ChartView) View() swiftui.View { return c.build() }

// AsView returns the underlying SwiftUI view.
func (c ChartView) AsView() swiftui.View { return c.build() }

// Frame applies a SwiftUI frame to the built chart view.
func (c ChartView) Frame(width, height float64) swiftui.View {
	return c.build().Frame(width, height)
}

type chartSpec struct {
	Marks           []markSpec                `json:"marks"`
	XDomain         *domainSpec               `json:"xDomain,omitempty"`
	YDomain         *domainSpec               `json:"yDomain,omitempty"`
	XRange          *positionScaleRangeSpec   `json:"xRange,omitempty"`
	YRange          *positionScaleRangeSpec   `json:"yRange,omitempty"`
	XScaleType      scaleTypeSpec             `json:"xScaleType"`
	YScaleType      scaleTypeSpec             `json:"yScaleType"`
	XAxis           *axisConfigSpec           `json:"xAxis,omitempty"`
	YAxis           *axisConfigSpec           `json:"yAxis,omitempty"`
	XAxisLabel      *axisLabelSpec            `json:"xAxisLabel,omitempty"`
	YAxisLabel      *axisLabelSpec            `json:"yAxisLabel,omitempty"`
	XAxisStyle      *axisStyleSpec            `json:"xAxisStyle,omitempty"`
	YAxisStyle      *axisStyleSpec            `json:"yAxisStyle,omitempty"`
	StyleScale      *foregroundStyleScaleSpec `json:"styleScale,omitempty"`
	SymbolScale     *symbolScaleSpec          `json:"symbolScale,omitempty"`
	LineStyleScale  *lineStyleScaleSpec       `json:"lineStyleScale,omitempty"`
	SymbolSizeScale *symbolSizeScaleSpec      `json:"symbolSizeScale,omitempty"`
	Legend          *legendConfigSpec         `json:"legend,omitempty"`
	Plot            []plotStyleSpec           `json:"plot,omitempty"`
	ScrollAxes      int32                     `json:"scrollAxes"`
	ScrollPosition  *scrollPositionSpec       `json:"scrollPosition,omitempty"`
	VisibleLength   *float64                  `json:"visibleLength,omitempty"`
	XSelection      *stateRefSpec             `json:"xSelection,omitempty"`
	XSelectionRange *stateRefSpec             `json:"xSelectionRange,omitempty"`
	YSelection      *stateRefSpec             `json:"ySelection,omitempty"`
	YSelectionRange *stateRefSpec             `json:"ySelectionRange,omitempty"`
	AngleSelection  *stateRefSpec             `json:"angleSelection,omitempty"`
	ScrollTarget    *scrollTargetBehaviorSpec `json:"scrollTarget,omitempty"`
	XScrollBinding  *stateRefSpec             `json:"xScrollBinding,omitempty"`
	YScrollBinding  *stateRefSpec             `json:"yScrollBinding,omitempty"`
	XVisibleLength  *visibleDomainLengthSpec  `json:"xVisibleLength,omitempty"`
	YVisibleLength  *visibleDomainLengthSpec  `json:"yVisibleLength,omitempty"`
	Overlays        []proxyLayerSpec          `json:"overlays,omitempty"`
	Backgrounds     []proxyLayerSpec          `json:"backgrounds,omitempty"`
	Gesture         *proxyGestureSpec         `json:"gesture,omitempty"`
}

type valueSpec struct {
	Kind       int32   `json:"kind"`
	Label      string  `json:"label"`
	Category   string  `json:"category"`
	Integer    int     `json:"integer"`
	Number     float64 `json:"number"`
	TimeUnixMS int64   `json:"timeUnixMS"`
	TimeUnit   int32   `json:"timeUnit"`
}

type dimSpec struct {
	Role      int32     `json:"role"`
	Value     valueSpec `json:"value"`
	Secondary valueSpec `json:"secondary"`
	FloatV    float64   `json:"floatV"`
}

type markSpec struct {
	Kind          int32                    `json:"kind"`
	Dims          []dimSpec                `json:"dims"`
	Mods          []markModSpec            `json:"mods"`
	Children      []markSpec               `json:"children,omitempty"`
	PointData     []pointPlotDatumSpec     `json:"pointData,omitempty"`
	RectangleData []rectanglePlotDatumSpec `json:"rectangleData,omitempty"`
	RuleData      []rulePlotDatumSpec      `json:"ruleData,omitempty"`
}

type markDimensionSpec struct {
	Kind  int32   `json:"kind"`
	Value float64 `json:"value"`
}

type pointPlotDatumSpec struct {
	X valueSpec `json:"x"`
	Y valueSpec `json:"y"`
}

type rectanglePlotDatumSpec struct {
	X      *valueSpec        `json:"x,omitempty"`
	Y      *valueSpec        `json:"y,omitempty"`
	XStart *valueSpec        `json:"xStart,omitempty"`
	XEnd   *valueSpec        `json:"xEnd,omitempty"`
	YStart *valueSpec        `json:"yStart,omitempty"`
	YEnd   *valueSpec        `json:"yEnd,omitempty"`
	Width  markDimensionSpec `json:"width"`
	Height markDimensionSpec `json:"height"`
}

type rulePlotDatumSpec struct {
	X      *valueSpec `json:"x,omitempty"`
	Y      *valueSpec `json:"y,omitempty"`
	XStart *valueSpec `json:"xStart,omitempty"`
	XEnd   *valueSpec `json:"xEnd,omitempty"`
	YStart *valueSpec `json:"yStart,omitempty"`
	YEnd   *valueSpec `json:"yEnd,omitempty"`
}

type markModSpec struct {
	Kind    int32     `json:"kind"`
	ColorR  float64   `json:"colorR"`
	ColorG  float64   `json:"colorG"`
	ColorB  float64   `json:"colorB"`
	ColorA  float64   `json:"colorA"`
	Label   string    `json:"label"`
	Value   string    `json:"value"`
	FloatV  float64   `json:"floatV"`
	FloatW  float64   `json:"floatW"`
	FloatX  float64   `json:"floatX"`
	FloatY  float64   `json:"floatY"`
	IntV    int32     `json:"intV"`
	Dash    []float64 `json:"dash,omitempty"`
	ViewPtr string    `json:"viewPtr"`
}

type scaleTypeSpec struct {
	Kind  int32   `json:"kind"`
	Value float64 `json:"value"`
}

type domainSpec struct {
	Kind        int32    `json:"kind"`
	MinInt      int      `json:"minInt"`
	MaxInt      int      `json:"maxInt"`
	MinNumber   float64  `json:"minNumber"`
	MaxNumber   float64  `json:"maxNumber"`
	StartUnixMS int64    `json:"startUnixMS"`
	EndUnixMS   int64    `json:"endUnixMS"`
	Categories  []string `json:"categories,omitempty"`
}

type axisValuesSpec struct {
	Kind            int32       `json:"kind"`
	Step            float64     `json:"step"`
	Unit            int32       `json:"unit"`
	Count           int         `json:"count"`
	DesiredCount    int         `json:"desiredCount"`
	RoundLowerBound bool        `json:"roundLowerBound"`
	RoundUpperBound bool        `json:"roundUpperBound"`
	Values          []valueSpec `json:"values,omitempty"`
}

type axisTickLengthSpec struct {
	Kind  int32   `json:"kind"`
	Value float64 `json:"value"`
}

type lineStyleSpec struct {
	Width float64   `json:"width"`
	Dash  []float64 `json:"dash,omitempty"`
}

type valueFormatSpec struct {
	Kind      int32  `json:"kind"`
	Precision int    `json:"precision"`
	Unit      int32  `json:"unit"`
	Suffix    string `json:"suffix"`
}

type axisConfigSpec struct {
	Hidden        bool               `json:"hidden"`
	Preset        int32              `json:"preset"`
	Position      int32              `json:"position"`
	Values        axisValuesSpec     `json:"values"`
	ShowGrid      bool               `json:"showGrid"`
	GridStyle     lineStyleSpec      `json:"gridStyle"`
	GridCentered  bool               `json:"gridCentered"`
	ShowTicks     bool               `json:"showTicks"`
	TickStyle     lineStyleSpec      `json:"tickStyle"`
	TickCentered  bool               `json:"tickCentered"`
	TickLength    axisTickLengthSpec `json:"tickLength"`
	ShowLabels    bool               `json:"showLabels"`
	DatePattern   string             `json:"datePattern"`
	LabelCentered bool               `json:"labelCentered"`
	ValueFormat   valueFormatSpec    `json:"valueFormat"`
}

type axisLabelSpec struct {
	Text         string  `json:"text"`
	Position     int32   `json:"position"`
	Alignment    int32   `json:"alignment"`
	HasPosition  bool    `json:"hasPosition"`
	HasAlignment bool    `json:"hasAlignment"`
	HasSpacing   bool    `json:"hasSpacing"`
	Spacing      float64 `json:"spacing"`
}

type axisStyleEntrySpec struct {
	Kind    int32   `json:"kind"`
	ColorR  float64 `json:"colorR"`
	ColorG  float64 `json:"colorG"`
	ColorB  float64 `json:"colorB"`
	ColorA  float64 `json:"colorA"`
	Opacity float64 `json:"opacity"`
	ViewPtr string  `json:"viewPtr"`
}

type axisStyleSpec struct {
	Entries []axisStyleEntrySpec `json:"entries,omitempty"`
}

type positionScaleRangeSpec struct {
	Kind         int32   `json:"kind"`
	StartPadding float64 `json:"startPadding"`
	EndPadding   float64 `json:"endPadding"`
}

type styleScaleSpec struct {
	Key    string  `json:"key"`
	ColorR float64 `json:"colorR"`
	ColorG float64 `json:"colorG"`
	ColorB float64 `json:"colorB"`
	ColorA float64 `json:"colorA"`
}

type foregroundStyleScaleSpec struct {
	Entries   []styleScaleSpec `json:"entries,omitempty"`
	ScaleType *scaleTypeSpec   `json:"scaleType,omitempty"`
}

type symbolScaleEntrySpec struct {
	Key    string `json:"key"`
	Symbol int32  `json:"symbol"`
}

type symbolScaleSpec struct {
	Entries []symbolScaleEntrySpec `json:"entries,omitempty"`
}

type lineStyleScaleEntrySpec struct {
	Key   string        `json:"key"`
	Style lineStyleSpec `json:"style"`
}

type lineStyleScaleSpec struct {
	Entries []lineStyleScaleEntrySpec `json:"entries,omitempty"`
}

type symbolSizeScaleEntrySpec struct {
	Key  string  `json:"key"`
	Size float64 `json:"size"`
}

type symbolSizeScaleSpec struct {
	Entries   []symbolSizeScaleEntrySpec `json:"entries,omitempty"`
	ScaleType *scaleTypeSpec             `json:"scaleType,omitempty"`
}

type legendConfigSpec struct {
	Visibility int32   `json:"visibility"`
	Position   int32   `json:"position"`
	Alignment  int32   `json:"alignment"`
	Spacing    float64 `json:"spacing"`
}

type plotStyleSpec struct {
	Kind    int32   `json:"kind"`
	ColorR  float64 `json:"colorR"`
	ColorG  float64 `json:"colorG"`
	ColorB  float64 `json:"colorB"`
	ColorA  float64 `json:"colorA"`
	Width   float64 `json:"width"`
	ViewPtr string  `json:"viewPtr"`
	Top     float64 `json:"top"`
	Right   float64 `json:"right"`
	Bottom  float64 `json:"bottom"`
	Left    float64 `json:"left"`
}

type scrollPositionSpec struct {
	Kind   int32   `json:"kind"`
	Axis   int32   `json:"axis"`
	Number float64 `json:"number"`
	Time   int64   `json:"time"`
}

func pointerString(ptr uintptr) string {
	if ptr == 0 {
		return ""
	}
	return strconv.FormatUint(uint64(ptr), 10)
}

func colorParts(color swiftui.Color) (float64, float64, float64, float64) {
	return color.R, color.G, color.B, color.A
}

func (v Value) toSpec() valueSpec {
	return valueSpec{
		Kind:       int32(v.kind),
		Label:      v.label,
		Category:   v.category,
		Integer:    v.integer,
		Number:     v.number,
		TimeUnixMS: v.timestamp.UnixMilli(),
		TimeUnit:   int32(v.timeUnit),
	}
}

func (d Dim) toSpec() dimSpec {
	return dimSpec{
		Role:      int32(d.role),
		Value:     d.value.toSpec(),
		Secondary: d.secondary.toSpec(),
		FloatV:    d.floatV,
	}
}

func (m markMod) toSpec() markModSpec {
	r, g, b, a := colorParts(m.color)
	return markModSpec{
		Kind:    int32(m.kind),
		ColorR:  r,
		ColorG:  g,
		ColorB:  b,
		ColorA:  a,
		Label:   m.label,
		Value:   m.value,
		FloatV:  m.floatV,
		FloatW:  m.floatW,
		FloatX:  m.floatX,
		FloatY:  m.floatY,
		IntV:    m.intV,
		Dash:    append([]float64(nil), m.dash...),
		ViewPtr: pointerString(m.view.Pointer()),
	}
}

func (m Mark) toSpec() markSpec {
	spec := markSpec{
		Kind: int32(m.kind),
	}
	if len(m.dims) > 0 {
		spec.Dims = make([]dimSpec, len(m.dims))
		for i, dim := range m.dims {
			spec.Dims[i] = dim.toSpec()
		}
	}
	if len(m.mods) > 0 {
		spec.Mods = make([]markModSpec, len(m.mods))
		for i, mod := range m.mods {
			spec.Mods[i] = mod.toSpec()
		}
	}
	if len(m.children) > 0 {
		spec.Children = make([]markSpec, len(m.children))
		for i, child := range m.children {
			spec.Children[i] = child.toSpec()
		}
	}
	if len(m.pointData) > 0 {
		spec.PointData = make([]pointPlotDatumSpec, len(m.pointData))
		for i, datum := range m.pointData {
			spec.PointData[i] = datum.toSpec()
		}
	}
	if len(m.rectangleData) > 0 {
		spec.RectangleData = make([]rectanglePlotDatumSpec, len(m.rectangleData))
		for i, datum := range m.rectangleData {
			spec.RectangleData[i] = datum.toSpec()
		}
	}
	if len(m.ruleData) > 0 {
		spec.RuleData = make([]rulePlotDatumSpec, len(m.ruleData))
		for i, datum := range m.ruleData {
			spec.RuleData[i] = datum.toSpec()
		}
	}
	return spec
}

func (d MarkDimension) toSpec() markDimensionSpec {
	return markDimensionSpec{
		Kind:  int32(d.kind),
		Value: d.value,
	}
}

func (d PointPlotDatum) toSpec() pointPlotDatumSpec {
	return pointPlotDatumSpec{
		X: d.X.toSpec(),
		Y: d.Y.toSpec(),
	}
}

func valueSpecPtr(v *Value) *valueSpec {
	if v == nil {
		return nil
	}
	spec := v.toSpec()
	return &spec
}

func (d RectanglePlotDatum) toSpec() rectanglePlotDatumSpec {
	return rectanglePlotDatumSpec{
		X:      valueSpecPtr(d.X),
		Y:      valueSpecPtr(d.Y),
		XStart: valueSpecPtr(d.XStart),
		XEnd:   valueSpecPtr(d.XEnd),
		YStart: valueSpecPtr(d.YStart),
		YEnd:   valueSpecPtr(d.YEnd),
		Width:  d.Width.toSpec(),
		Height: d.Height.toSpec(),
	}
}

func (d RulePlotDatum) toSpec() rulePlotDatumSpec {
	return rulePlotDatumSpec{
		X:      valueSpecPtr(d.X),
		Y:      valueSpecPtr(d.Y),
		XStart: valueSpecPtr(d.XStart),
		XEnd:   valueSpecPtr(d.XEnd),
		YStart: valueSpecPtr(d.YStart),
		YEnd:   valueSpecPtr(d.YEnd),
	}
}

func (d Domain) toSpec() domainSpec {
	return domainSpec{
		Kind:        int32(d.kind),
		MinInt:      d.minInt,
		MaxInt:      d.maxInt,
		MinNumber:   d.minNumber,
		MaxNumber:   d.maxNumber,
		StartUnixMS: d.startTime.UnixMilli(),
		EndUnixMS:   d.endTime.UnixMilli(),
		Categories:  append([]string(nil), d.categories...),
	}
}

func (t ScaleType) toSpec() scaleTypeSpec {
	return scaleTypeSpec{
		Kind:  int32(t.kind),
		Value: t.value,
	}
}

func (v AxisValues) toSpec() axisValuesSpec {
	spec := axisValuesSpec{
		Kind:            int32(v.kind),
		Step:            v.step,
		Unit:            int32(v.unit),
		Count:           v.count,
		DesiredCount:    v.desiredCount,
		RoundLowerBound: v.roundLowerBound,
		RoundUpperBound: v.roundUpperBound,
	}
	if len(v.values) > 0 {
		spec.Values = make([]valueSpec, len(v.values))
		for i, value := range v.values {
			spec.Values[i] = value.toSpec()
		}
	}
	return spec
}

func (t AxisTickLength) toSpec() axisTickLengthSpec {
	return axisTickLengthSpec{
		Kind:  int32(t.kind),
		Value: t.value,
	}
}

func (s LineStyle) toSpec() lineStyleSpec {
	return lineStyleSpec{
		Width: s.Width,
		Dash:  append([]float64(nil), s.Dash...),
	}
}

func (f ValueFormat) toSpec() valueFormatSpec {
	return valueFormatSpec{
		Kind:      int32(f.kind),
		Precision: f.precision,
		Unit:      int32(f.unit),
		Suffix:    f.suffix,
	}
}

func (cfg AxisConfig) toSpec() axisConfigSpec {
	return axisConfigSpec{
		Hidden:        cfg.hidden,
		Preset:        int32(cfg.preset),
		Position:      int32(cfg.position),
		Values:        cfg.values.toSpec(),
		ShowGrid:      cfg.showGrid,
		GridStyle:     cfg.gridStyle.toSpec(),
		GridCentered:  cfg.gridCentered,
		ShowTicks:     cfg.showTicks,
		TickStyle:     cfg.tickStyle.toSpec(),
		TickCentered:  cfg.tickCentered,
		TickLength:    cfg.tickLength.toSpec(),
		ShowLabels:    cfg.showLabels,
		DatePattern:   cfg.datePattern,
		LabelCentered: cfg.labelCentered,
		ValueFormat:   cfg.valueFormat.toSpec(),
	}
}

func (label axisLabel) toSpec() axisLabelSpec {
	return axisLabelSpec{
		Text:         label.text,
		Position:     int32(label.position),
		Alignment:    int32(label.alignment),
		HasPosition:  label.hasPosition,
		HasAlignment: label.hasAlignment,
		HasSpacing:   label.hasSpacing,
		Spacing:      label.spacing,
	}
}

func (opt AxisStyleOption) toSpec() axisStyleEntrySpec {
	r, g, b, a := colorParts(opt.color)
	return axisStyleEntrySpec{
		Kind:    int32(opt.kind),
		ColorR:  r,
		ColorG:  g,
		ColorB:  b,
		ColorA:  a,
		Opacity: opt.opacity,
		ViewPtr: pointerString(opt.view.Pointer()),
	}
}

func (rng PositionScaleRange) toSpec() positionScaleRangeSpec {
	return positionScaleRangeSpec{
		Kind:         int32(rng.kind),
		StartPadding: rng.startPadding,
		EndPadding:   rng.endPadding,
	}
}

func (entry StyleScaleEntry) toSpec() styleScaleSpec {
	r, g, b, a := colorParts(entry.Color)
	return styleScaleSpec{
		Key:    entry.Key,
		ColorR: r,
		ColorG: g,
		ColorB: b,
		ColorA: a,
	}
}

func (entry SymbolScaleEntry) toSpec() symbolScaleEntrySpec {
	return symbolScaleEntrySpec{
		Key:    entry.Key,
		Symbol: int32(entry.Symbol),
	}
}

func (entry LineStyleScaleEntry) toSpec() lineStyleScaleEntrySpec {
	return lineStyleScaleEntrySpec{
		Key:   entry.Key,
		Style: entry.Style.toSpec(),
	}
}

func (entry SymbolSizeScaleEntry) toSpec() symbolSizeScaleEntrySpec {
	return symbolSizeScaleEntrySpec{
		Key:  entry.Key,
		Size: entry.Size,
	}
}

func (cfg LegendConfig) toSpec() legendConfigSpec {
	return legendConfigSpec{
		Visibility: int32(cfg.Visibility),
		Position:   int32(cfg.Position),
		Alignment:  int32(cfg.Alignment),
		Spacing:    cfg.Spacing,
	}
}

func (opt PlotStyleOption) toSpec() plotStyleSpec {
	r, g, b, a := colorParts(opt.color)
	return plotStyleSpec{
		Kind:    int32(opt.kind),
		ColorR:  r,
		ColorG:  g,
		ColorB:  b,
		ColorA:  a,
		Width:   opt.width,
		ViewPtr: pointerString(opt.view.Pointer()),
		Top:     opt.top,
		Right:   opt.right,
		Bottom:  opt.bottom,
		Left:    opt.left,
	}
}

func (pos scrollPosition) toSpec() scrollPositionSpec {
	return scrollPositionSpec{
		Kind:   int32(pos.kind),
		Axis:   int32(pos.axis),
		Number: pos.number,
		Time:   pos.time,
	}
}

func copyMarkMods(mods []markMod) []markMod {
	return append([]markMod(nil), mods...)
}

func copyMarkChildren(children []Mark) []Mark {
	return append([]Mark(nil), children...)
}

func stripMarkMods(m Mark, kinds ...markModKind) Mark {
	if len(m.mods) == 0 {
		return m
	}
	drop := map[markModKind]bool{}
	for _, kind := range kinds {
		drop[kind] = true
	}
	filtered := make([]markMod, 0, len(m.mods))
	for _, mod := range m.mods {
		if !drop[mod.kind] {
			filtered = append(filtered, mod)
		}
	}
	m.mods = filtered
	return m
}

func hasMarkMod(m Mark, kind markModKind) bool {
	for _, mod := range m.mods {
		if mod.kind == kind {
			return true
		}
	}
	return false
}

func annotationDeclutterLimit(m Mark) (int, bool) {
	for _, mod := range m.mods {
		if mod.kind == modAnnotationDeclutterLatest {
			if mod.intV < 1 {
				return 1, true
			}
			return int(mod.intV), true
		}
	}
	return 0, false
}

func annotationDeclutterDistance(m Mark) (float64, float64, bool) {
	for _, mod := range m.mods {
		if mod.kind == modAnnotationDeclutterDistance {
			return mod.floatX, mod.floatY, true
		}
	}
	return 0, 0, false
}

func annotationDataOffset(m Mark) (float64, float64, bool) {
	for _, mod := range m.mods {
		if mod.kind == modAnnotationDataOffset {
			return mod.floatX, mod.floatY, true
		}
	}
	return 0, 0, false
}

func annotationCollisionMode(m Mark) AnnotationCollisionMode {
	for _, mod := range m.mods {
		if mod.kind == modAnnotationCollision {
			return AnnotationCollisionMode(mod.intV)
		}
	}
	return AnnotationCollisionAutomatic
}

func annotationPriority(m Mark) int {
	for _, mod := range m.mods {
		if mod.kind == modAnnotationPriority {
			return int(mod.intV)
		}
	}
	return 0
}

type annotationCoordState struct {
	xCategories map[string]float64
	yCategories map[string]float64
}

type annotationPoint struct {
	x float64
	y float64
}

type keptAnnotation struct {
	point    annotationPoint
	index    int
	priority int
}

func numericValue(v Value, cats map[string]float64) (float64, bool) {
	switch v.kind {
	case valueCategory:
		if cats == nil {
			return 0, false
		}
		if value, ok := cats[v.category]; ok {
			return value, true
		}
		value := float64(len(cats))
		cats[v.category] = value
		return value, true
	case valueInteger:
		return float64(v.integer), true
	case valueNumber:
		return v.number, true
	case valueTime:
		return float64(v.timestamp.UnixMilli()) / 1000.0, true
	default:
		return 0, false
	}
}

func annotationPointForMark(m Mark, state *annotationCoordState) (annotationPoint, bool) {
	xDim, okX := findDim(m.dims, dimX)
	yDim, okY := findDim(m.dims, dimY)
	if !okX || !okY {
		return annotationPoint{}, false
	}
	x, okX := numericValue(xDim.value, state.xCategories)
	y, okY := numericValue(yDim.value, state.yCategories)
	if !okX || !okY {
		return annotationPoint{}, false
	}
	if dx, dy, ok := annotationDataOffset(m); ok {
		x += dx
		y += dy
	}
	return annotationPoint{x: x, y: y}, true
}

func annotationOverlapIndices(point annotationPoint, kept []keptAnnotation, minX, minY float64) []int {
	if minX <= 0 && minY <= 0 {
		return nil
	}
	var overlaps []int
	for i, other := range kept {
		dx := point.x - other.point.x
		if dx < 0 {
			dx = -dx
		}
		dy := point.y - other.point.y
		if dy < 0 {
			dy = -dy
		}
		xClose := minX <= 0 || dx < minX
		yClose := minY <= 0 || dy < minY
		if xClose && yClose {
			overlaps = append(overlaps, i)
		}
	}
	return overlaps
}

func (b *chartBuilder) collisionThresholds() (float64, float64) {
	minX, minY := 0.1, 0.1
	if b.xDomain != nil {
		switch b.xDomain.kind {
		case domainInteger:
			if span := float64(b.xDomain.maxInt - b.xDomain.minInt); span > 0 {
				minX = span * 0.015
			}
		case domainNumber:
			if span := b.xDomain.maxNumber - b.xDomain.minNumber; span > 0 {
				minX = span * 0.015
			}
		case domainTime:
			if span := b.xDomain.endTime.Sub(b.xDomain.startTime).Seconds(); span > 0 {
				minX = span * 0.015
			}
		}
	}
	if b.yDomain != nil {
		switch b.yDomain.kind {
		case domainInteger:
			if span := float64(b.yDomain.maxInt - b.yDomain.minInt); span > 0 {
				minY = span * 0.02
			}
		case domainNumber:
			if span := b.yDomain.maxNumber - b.yDomain.minNumber; span > 0 {
				minY = span * 0.02
			}
		case domainTime:
			if span := b.yDomain.endTime.Sub(b.yDomain.startTime).Seconds(); span > 0 {
				minY = span * 0.02
			}
		}
	}
	return minX, minY
}

func addValueOffset(v Value, delta float64) (Value, bool) {
	switch v.kind {
	case valueInteger:
		return NumberValue(v.label, float64(v.integer)+delta), true
	case valueNumber:
		return NumberValue(v.label, v.number+delta), true
	case valueTime:
		return TimeValue(v.label, v.timestamp.Add(time.Duration(delta*float64(time.Second))), v.timeUnit), true
	default:
		return Value{}, false
	}
}

func stripAnnotationControlMods(m Mark) Mark {
	return stripMarkMods(
		m,
		modAnnotationDataOffset,
		modAnnotationCollision,
		modAnnotationPriority,
		modAnnotationDeclutterLatest,
		modAnnotationDeclutterDistance,
	)
}

func stripAnnotationAttachmentMods(m Mark) Mark {
	return stripMarkMods(
		m,
		modAnnotation,
		modAnnotationOverflow,
		modAnnotationOffset,
		modAnnotationDataOffset,
		modAnnotationCollision,
		modAnnotationPriority,
		modAnnotationDeclutterLatest,
		modAnnotationDeclutterDistance,
	)
}

func annotationAnchorMark(m Mark) (Mark, bool) {
	dx, dy, ok := annotationDataOffset(m)
	if !ok {
		return Mark{}, false
	}
	xDim, okX := findDim(m.dims, dimX)
	yDim, okY := findDim(m.dims, dimY)
	if !okX || !okY {
		return Mark{}, false
	}
	xv, okX := addValueOffset(xDim.value, dx)
	yv, okY := addValueOffset(yDim.value, dy)
	if !okX || !okY {
		return Mark{}, false
	}
	anchor := PointMark(X(xv), Y(yv))
	for _, mod := range m.mods {
		switch mod.kind {
		case modAnnotation, modAnnotationOverflow, modAnnotationOffset:
			anchor.mods = append(anchor.mods, mod)
		}
	}
	anchor = anchor.Opacity(0).AccessibilityHidden(true).ExcludeFromLegend()
	return anchor, true
}

func stripAnnotationViewMods(m Mark) Mark {
	return stripMarkMods(m, modAnnotation, modAnnotationOverflow, modAnnotationOffset)
}

func resolvedStyleEntry(entries []StyleScaleEntry, key string) (StyleScaleEntry, bool) {
	for _, entry := range entries {
		if entry.Key == key {
			return entry, true
		}
	}
	return StyleScaleEntry{}, false
}

func resolvedSymbolEntry(entries []SymbolScaleEntry, key string) (SymbolScaleEntry, bool) {
	for _, entry := range entries {
		if entry.Key == key {
			return entry, true
		}
	}
	return SymbolScaleEntry{}, false
}

func resolvedLineStyleEntry(entries []LineStyleScaleEntry, key string) (LineStyleScaleEntry, bool) {
	for _, entry := range entries {
		if entry.Key == key {
			return entry, true
		}
	}
	return LineStyleScaleEntry{}, false
}

func resolvedSymbolSizeEntry(entries []SymbolSizeScaleEntry, key string) (SymbolSizeScaleEntry, bool) {
	for _, entry := range entries {
		if entry.Key == key {
			return entry, true
		}
	}
	return SymbolSizeScaleEntry{}, false
}

func (b *chartBuilder) resolveLegendExcludedMark(m Mark) Mark {
	if len(m.children) > 0 {
		children := make([]Mark, len(m.children))
		for i, child := range m.children {
			children[i] = b.resolveLegendExcludedMark(child)
		}
		m.children = children
	}
	if !hasMarkMod(m, modExcludeFromLegend) {
		return m
	}
	mods := make([]markMod, 0, len(m.mods))
	for _, mod := range m.mods {
		switch mod.kind {
		case modExcludeFromLegend:
			continue
		case modForegroundStyleBy:
			if entry, ok := resolvedStyleEntry(b.styleScale.entries, mod.value); ok {
				mods = append(mods, markMod{kind: modForegroundStyle, color: entry.Color})
			}
		case modSymbolBy:
			if entry, ok := resolvedSymbolEntry(b.symbolScale.entries, mod.value); ok {
				mods = append(mods, markMod{kind: modSymbol, intV: int32(entry.Symbol)})
			}
		case modLineStyleBy:
			if entry, ok := resolvedLineStyleEntry(b.lineStyleScale.entries, mod.value); ok {
				mods = append(mods, markMod{kind: modLineStyle, floatV: entry.Style.Width, dash: append([]float64(nil), entry.Style.Dash...)})
			}
		case modSymbolSizeBy:
			if entry, ok := resolvedSymbolSizeEntry(b.symbolSizeScale.entries, mod.value); ok {
				mods = append(mods, markMod{kind: modSymbolSize, floatV: entry.Size})
			}
		default:
			mods = append(mods, mod)
		}
	}
	m.mods = mods
	return m
}

func (b *chartBuilder) declutterMarks(marks []Mark) []Mark {
	processed := make([]Mark, len(marks))
	for i, m := range marks {
		if len(m.children) > 0 {
			m.children = b.declutterMarks(copyMarkChildren(m.children))
		}
		processed[i] = m
	}
	keepAnnotation := make([]bool, len(processed))
	seen := 0
	state := &annotationCoordState{
		xCategories: map[string]float64{},
		yCategories: map[string]float64{},
	}
	var kept []keptAnnotation
	defaultMinX, defaultMinY := b.collisionThresholds()
	for i := len(processed) - 1; i >= 0; i-- {
		m := processed[i]
		keep := hasMarkMod(m, modAnnotation)
		if !keep {
			continue
		}
		if hasMarkMod(m, modAnnotation) {
			if limit, ok := annotationDeclutterLimit(m); ok {
				seen++
				if seen > limit {
					keep = false
				}
			}
			if keep {
				minX, minY, hasDistance := annotationDeclutterDistance(m)
				collision := annotationCollisionMode(m)
				if collision != AnnotationCollisionAutomatic && !hasDistance {
					minX, minY = defaultMinX, defaultMinY
					hasDistance = true
				}
				if hasDistance {
					if point, ok := annotationPointForMark(m, state); ok {
						overlaps := annotationOverlapIndices(point, kept, minX, minY)
						if len(overlaps) > 0 {
							switch collision {
							case AnnotationCollisionKeepPriority:
								priority := annotationPriority(m)
								replace := true
								for _, idx := range overlaps {
									if priority <= kept[idx].priority {
										replace = false
										break
									}
								}
								if !replace {
									keep = false
									break
								}
								for j := len(overlaps) - 1; j >= 0; j-- {
									idx := overlaps[j]
									keepAnnotation[kept[idx].index] = false
									kept = append(kept[:idx], kept[idx+1:]...)
								}
								kept = append(kept, keptAnnotation{point: point, index: i, priority: priority})
							default:
								keep = false
							}
						} else {
							kept = append(kept, keptAnnotation{point: point, index: i, priority: annotationPriority(m)})
						}
					}
				}
			}
		}
		keepAnnotation[i] = keep
	}
	out := make([]Mark, 0, len(processed)*2)
	for i, m := range processed {
		if hasMarkMod(m, modAnnotation) && !keepAnnotation[i] {
			m = stripAnnotationViewMods(m)
		}
		if keepAnnotation[i] && hasMarkMod(m, modAnnotationDataOffset) {
			if anchor, ok := annotationAnchorMark(m); ok {
				out = append(out, stripAnnotationControlMods(stripAnnotationAttachmentMods(m)))
				out = append(out, stripAnnotationControlMods(anchor))
				continue
			}
		}
		out = append(out, stripAnnotationControlMods(m))
	}
	return out
}

func (b *chartBuilder) preparedMarks() []Mark {
	marks := append([]Mark(nil), b.marks...)
	marks = b.declutterMarks(marks)
	for i, mark := range marks {
		marks[i] = b.resolveLegendExcludedMark(mark)
	}
	return marks
}

func (b *chartBuilder) toSpec() chartSpec {
	spec := chartSpec{
		XScaleType: b.xScaleType.toSpec(),
		YScaleType: b.yScaleType.toSpec(),
		ScrollAxes: int32(b.scrollAxes),
	}
	if len(b.marks) > 0 {
		marks := b.preparedMarks()
		spec.Marks = make([]markSpec, len(marks))
		for i, mark := range marks {
			spec.Marks[i] = mark.toSpec()
		}
	}
	if b.xDomain != nil {
		d := b.xDomain.toSpec()
		spec.XDomain = &d
	}
	if b.yDomain != nil {
		d := b.yDomain.toSpec()
		spec.YDomain = &d
	}
	if b.xRange != nil {
		r := b.xRange.toSpec()
		spec.XRange = &r
	}
	if b.yRange != nil {
		r := b.yRange.toSpec()
		spec.YRange = &r
	}
	if b.xAxis != nil {
		cfg := b.xAxis.toSpec()
		spec.XAxis = &cfg
	}
	if b.yAxis != nil {
		cfg := b.yAxis.toSpec()
		spec.YAxis = &cfg
	}
	if b.xAxisLabel != nil {
		label := b.xAxisLabel.toSpec()
		spec.XAxisLabel = &label
	}
	if b.yAxisLabel != nil {
		label := b.yAxisLabel.toSpec()
		spec.YAxisLabel = &label
	}
	if len(b.xAxisStyle) > 0 {
		style := axisStyleSpec{Entries: make([]axisStyleEntrySpec, len(b.xAxisStyle))}
		for i, entry := range b.xAxisStyle {
			style.Entries[i] = entry.toSpec()
		}
		spec.XAxisStyle = &style
	}
	if len(b.yAxisStyle) > 0 {
		style := axisStyleSpec{Entries: make([]axisStyleEntrySpec, len(b.yAxisStyle))}
		for i, entry := range b.yAxisStyle {
			style.Entries[i] = entry.toSpec()
		}
		spec.YAxisStyle = &style
	}
	if len(b.styleScale.entries) > 0 || b.styleScale.scaleType != nil {
		scale := foregroundStyleScaleSpec{}
		if len(b.styleScale.entries) > 0 {
			scale.Entries = make([]styleScaleSpec, len(b.styleScale.entries))
			for i, entry := range b.styleScale.entries {
				scale.Entries[i] = entry.toSpec()
			}
		}
		if b.styleScale.scaleType != nil {
			value := b.styleScale.scaleType.toSpec()
			scale.ScaleType = &value
		}
		spec.StyleScale = &scale
	}
	if len(b.symbolScale.entries) > 0 {
		scale := symbolScaleSpec{Entries: make([]symbolScaleEntrySpec, len(b.symbolScale.entries))}
		for i, entry := range b.symbolScale.entries {
			scale.Entries[i] = entry.toSpec()
		}
		spec.SymbolScale = &scale
	}
	if len(b.lineStyleScale.entries) > 0 {
		scale := lineStyleScaleSpec{Entries: make([]lineStyleScaleEntrySpec, len(b.lineStyleScale.entries))}
		for i, entry := range b.lineStyleScale.entries {
			scale.Entries[i] = entry.toSpec()
		}
		spec.LineStyleScale = &scale
	}
	if len(b.symbolSizeScale.entries) > 0 || b.symbolSizeScale.scaleType != nil {
		scale := symbolSizeScaleSpec{}
		if len(b.symbolSizeScale.entries) > 0 {
			scale.Entries = make([]symbolSizeScaleEntrySpec, len(b.symbolSizeScale.entries))
			for i, entry := range b.symbolSizeScale.entries {
				scale.Entries[i] = entry.toSpec()
			}
		}
		if b.symbolSizeScale.scaleType != nil {
			value := b.symbolSizeScale.scaleType.toSpec()
			scale.ScaleType = &value
		}
		spec.SymbolSizeScale = &scale
	}
	if b.legend != nil {
		cfg := b.legend.toSpec()
		spec.Legend = &cfg
	}
	if len(b.plot) > 0 {
		spec.Plot = make([]plotStyleSpec, len(b.plot))
		for i, opt := range b.plot {
			spec.Plot[i] = opt.toSpec()
		}
	}
	if b.scrollPosition != nil {
		pos := b.scrollPosition.toSpec()
		spec.ScrollPosition = &pos
	}
	if b.visibleLength != nil {
		v := *b.visibleLength
		spec.VisibleLength = &v
	}
	spec.XSelection = stateSpec(b.xSelection)
	spec.XSelectionRange = stateSpec(b.xSelectionRange)
	spec.YSelection = stateSpec(b.ySelection)
	spec.YSelectionRange = stateSpec(b.ySelectionRange)
	spec.AngleSelection = stateSpec(b.angleSelection)
	if b.scrollTarget != nil {
		target := b.scrollTarget.toSpec()
		spec.ScrollTarget = &target
	}
	spec.XScrollBinding = stateSpec(b.xScrollBinding)
	spec.YScrollBinding = stateSpec(b.yScrollBinding)
	if b.xVisibleLength != nil {
		value := b.xVisibleLength.toSpec()
		spec.XVisibleLength = &value
	} else if b.visibleLength != nil {
		value := VisibleDomainNumeric(*b.visibleLength).toSpec()
		spec.XVisibleLength = &value
	}
	if b.yVisibleLength != nil {
		value := b.yVisibleLength.toSpec()
		spec.YVisibleLength = &value
	}
	if len(b.overlays) > 0 {
		spec.Overlays = make([]proxyLayerSpec, len(b.overlays))
		for i, overlay := range b.overlays {
			spec.Overlays[i] = overlay.toSpec()
		}
	}
	if len(b.backgrounds) > 0 {
		spec.Backgrounds = make([]proxyLayerSpec, len(b.backgrounds))
		for i, background := range b.backgrounds {
			spec.Backgrounds[i] = background.toSpec()
		}
	}
	if b.gesture != nil {
		gesture := b.gesture.toSpec()
		spec.Gesture = &gesture
	}
	return spec
}
