// Code generated by applegen; DO NOT EDIT.

import Foundation
import SpriteKit
import SwiftUI

// Box wraps a value type so it can be stored in Unmanaged.
final class Box<T>: @unchecked Sendable {
    var value: T
    init(_ value: T) { self.value = value }
}

@_cdecl("SPS_Retain")
public func SPS_Retain(_ ptr: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    _ = Unmanaged<AnyObject>.fromOpaque(ptr).retain()
    return ptr
}

@_cdecl("SPS_Release")
public func SPS_Release(_ ptr: UnsafeMutableRawPointer) {
    Unmanaged<AnyObject>.fromOpaque(ptr).release()
}

@_cdecl("SPS_FreeString")
public func SPS_FreeString(_ ptr: UnsafeMutablePointer<CChar>) {
    ptr.deallocate()
}
