// Code generated by applegen; DO NOT EDIT.

import AVKit
import SwiftUI
import AVFoundation


// MARK: - NewVideoPlayer

@_cdecl("AVS_VideoPlayerCreate")
@MainActor
public func AVS_VideoPlayerCreate(_ player: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let p = Unmanaged<AVPlayer>.fromOpaque(player).takeUnretainedValue()
    let view = AnyView(VideoPlayer(player: p))
    return Unmanaged.passRetained(Box(view)).toOpaque()
}

// MARK: - NewVideoPlayerWithOverlay

@_cdecl("AVS_VideoPlayerWithOverlayCreate")
@MainActor
public func AVS_VideoPlayerWithOverlayCreate(_ player: UnsafeMutableRawPointer, _ overlay: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    let p = Unmanaged<AVPlayer>.fromOpaque(player).takeUnretainedValue()
    let ov = Unmanaged<Box<AnyView>>.fromOpaque(overlay).takeUnretainedValue().value
    let view = AnyView(VideoPlayer(player: p) { ov })
    return Unmanaged.passRetained(Box(view)).toOpaque()
}
