// Code generated by applegen; DO NOT EDIT.

//go:build avkit_embed

package embeddedbridge

import _ "embed"

//go:embed libAVKitSwiftUIBridge.dylib
var bridge []byte

// Payload returns the embedded AVKitSwiftUIBridge bridge dylib payload.
func Payload() ([]byte, string) {
	return bridge, "libAVKitSwiftUIBridge.dylib"
}
