// Code generated by applegen; DO NOT EDIT.

package translation

// Set SWIFTUI_GENERATE_DYLIBS=1 to build a local Swift bridge dylib during generation.

//go:generate applegen swift-bridge Translation --output . --module github.com/tmc/swiftui --profile swiftui
//go:generate bash -lc "set -euo pipefail; if [ \"${DOLLAR}{SWIFTUI_GENERATE_DYLIBS:-}\" = 1 ]; then cd internal/swift; archs='--arch arm64 --arch x86_64'; swift build -c release --quiet --product TranslationSwiftUIBridge ${DOLLAR}archs; dylib=\"${DOLLAR}(swift build -c release --product TranslationSwiftUIBridge ${DOLLAR}archs --show-bin-path)/libTranslationSwiftUIBridge.dylib\"; test -f \"${DOLLAR}dylib\"; lipo -info \"${DOLLAR}dylib\" | grep -q arm64; lipo -info \"${DOLLAR}dylib\" | grep -q x86_64; cp \"${DOLLAR}dylib\" ../embeddedbridge/libTranslationSwiftUIBridge.dylib; fi"
