// Code generated by applegen; DO NOT EDIT.

//go:build arkit_embed

package embeddedbridge

import _ "embed"

//go:embed libARKitSwiftUIBridge.dylib
var bridge []byte

// Payload returns the embedded ARKitSwiftUIBridge bridge dylib payload.
func Payload() ([]byte, string) {
	return bridge, "libARKitSwiftUIBridge.dylib"
}
