// Code generated by applegen; DO NOT EDIT.

package spritekit

// Set SWIFTUI_GENERATE_DYLIBS=1 to build a local Swift bridge dylib during generation.

//go:generate applegen swift-bridge SpriteKit --output . --module github.com/tmc/swiftui --profile swiftui
//go:generate bash -lc "set -euo pipefail; if [ \"${DOLLAR}{SWIFTUI_GENERATE_DYLIBS:-}\" = 1 ]; then cd internal/swift; swift build -c release --quiet --product SpriteKitSwiftUIBridge; dylib=${DOLLAR}(find .build -path '*/release/libSpriteKitSwiftUIBridge.dylib' -type f | sort | tail -n 1); test -n \"${DOLLAR}dylib\"; cp \"${DOLLAR}dylib\" ../embeddedbridge/libSpriteKitSwiftUIBridge.dylib; fi"
