// Code generated by applegen; DO NOT EDIT.

package spritekit

import "unsafe"

// withCString calls fn with a null-terminated C string pointer.
func withCString(s string, fn func(*byte)) {
	b := append([]byte(s), 0)
	fn(&b[0])
}

// gostring copies a null-terminated C string to a Go string.
func gostring(p *byte) string {
	if p == nil {
		return ""
	}
	var buf []byte
	for ptr := p; *ptr != 0; ptr = (*byte)(unsafe.Add(unsafe.Pointer(ptr), 1)) {
		buf = append(buf, *ptr)
	}
	return string(buf)
}

// gostringFree copies a C string and frees it.
func gostringFree(p *byte) string {
	if p == nil {
		return ""
	}
	s := gostring(p)
	_SPS_FreeString(p)
	return s
}

// Retain increments the reference count of a bridge object.
func Retain(ptr uintptr) uintptr { return _SPS_Retain(ptr) }

// Release decrements the reference count of a bridge object.
func Release(ptr uintptr) { _SPS_Release(ptr) }

// NewSpriteView creates a SpriteView for an SKScene pointer.
func NewSpriteView(scene uintptr) uintptr {
	return _SPS_SpriteViewCreate(scene)
}

// NewSpriteViewWithTransition creates a SpriteView with a scene transition.
func NewSpriteViewWithTransition(scene uintptr, transition uintptr) uintptr {
	return _SPS_SpriteViewCreateWithTransition(scene, transition)
}

// NewSpriteViewWithOptions creates a SpriteView with paused state and FPS.
func NewSpriteViewWithOptions(scene uintptr, isPaused bool, preferredFramesPerSecond int32) uintptr {
	return _SPS_SpriteViewCreateWithOptions(scene, isPaused, preferredFramesPerSecond)
}
