// Code generated by applegen; DO NOT EDIT.

// Package quicklook provides Go bindings for Apple's QuickLook
// SwiftUI cross-import overlay (_QuickLook_SwiftUI).
//
// This overlay provides SwiftUI views and modifiers that integrate
// QuickLook with SwiftUI. View constructors and modifiers return
// typed swiftui.View values.
//
// Bridge sources under internal/swift/ are generated by go generate.
//
// # Threading
//
// All bridge functions dispatch to the main thread internally.
// The Go API is safe to call from any goroutine.
//
// # Quick start
//
//	import "github.com/tmc/swiftui"
//	import "github.com/tmc/swiftui/quicklook"
//
//	view := quicklook.QuickLookPreview(...)
package quicklook
