// Code generated by applegen; DO NOT EDIT.

package quicklook

import "unsafe"

// TODO(perf P1 subpackage rollout): replace with sync.Pool-backed scratch like the root package's withCStringPooled.
func withCString(s string, fn func(*byte)) {
	b := append([]byte(s), 0)
	fn(&b[0])
}

// gostring copies a null-terminated C string to a Go string.
func gostring(p *byte) string {
	if p == nil {
		return ""
	}
	var buf []byte
	for ptr := p; *ptr != 0; ptr = (*byte)(unsafe.Add(unsafe.Pointer(ptr), 1)) {
		buf = append(buf, *ptr)
	}
	return string(buf)
}

// gostringFree copies a C string and frees it.
func gostringFree(p *byte) string {
	if p == nil {
		return ""
	}
	s := gostring(p)
	_QLS_FreeString(p)
	return s
}

// Retain increments the reference count of a bridge object.
func Retain(ptr uintptr) uintptr { return _QLS_Retain(ptr) }

// Release decrements the reference count of a bridge object.
func Release(ptr uintptr) { _QLS_Release(ptr) }

// QuickLookPreview applies a quickLookPreview modifier for the given file URL.
func QuickLookPreview(view uintptr, urlStr string) uintptr {
	var result uintptr
	withCString(urlStr, func(cUrlStr *byte) {
		result = _QLS_QuickLookPreview(view, cUrlStr)
	})
	return result
}
