// Code generated by applegen; DO NOT EDIT.

package quicklook

import (
	"unsafe"

	"github.com/tmc/swiftui"
)

// withCString calls fn with a null-terminated C string pointer.
func withCString(s string, fn func(*byte)) {
	b := append([]byte(s), 0)
	fn(&b[0])
}

// gostring copies a null-terminated C string to a Go string.
func gostring(p *byte) string {
	if p == nil {
		return ""
	}
	var buf []byte
	for ptr := p; *ptr != 0; ptr = (*byte)(unsafe.Add(unsafe.Pointer(ptr), 1)) {
		buf = append(buf, *ptr)
	}
	return string(buf)
}

// gostringFree copies a C string and frees it.
func gostringFree(p *byte) string {
	if p == nil {
		return ""
	}
	s := gostring(p)
	_QLS_FreeString(p)
	return s
}

// QuickLookPreview applies a quickLookPreview modifier for the given file URL.
func QuickLookPreview(view uintptr, urlStr string) swiftui.View {
	var result swiftui.View
	withCString(urlStr, func(cUrlStr *byte) {
		result = swiftui.ViewFromPointer(_QLS_QuickLookPreview(view, cUrlStr))
	})
	return result
}
