// Code generated by applegen; DO NOT EDIT.

// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "SwiftUIBridge",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "SwiftUIBridge", type: .dynamic, targets: ["SwiftUIBridge"]),
    ],
    targets: [
        .target(
            name: "SwiftUIBridge",
            publicHeadersPath: "include"
        ),
    ]
)
