// Code generated by applegen; DO NOT EDIT.

//go:build scenekit_embed

package embeddedbridge

import _ "embed"

//go:embed libSceneKitSwiftUIBridge.dylib
var bridge []byte

// Payload returns the embedded SceneKitSwiftUIBridge bridge dylib payload.
func Payload() ([]byte, string) {
	return bridge, "libSceneKitSwiftUIBridge.dylib"
}
