// Code generated by applegen; DO NOT EDIT.

package embeddedbridge

import "embed"

const dylibName = "libSceneKitSwiftUIBridge.dylib"

//go:embed *
var payload embed.FS

// Payload returns the embedded bridge dylib payload when one is vendored.
func Payload() ([]byte, string) {
	data, err := payload.ReadFile(dylibName)
	if err != nil {
		// Missing payloads fall back to building the bridge from source.
		return nil, ""
	}
	return data, dylibName
}
