// Code generated by applegen; DO NOT EDIT.

// Package scenekit provides Go bindings for Apple's SceneKit
// SwiftUI cross-import overlay (_SceneKit_SwiftUI).
//
// This overlay provides SwiftUI views and modifiers that integrate
// SceneKit with SwiftUI. All view constructors return uintptr values
// suitable for use with swiftui.ViewFromPointer.
//
// Bridge sources under internal/swift/ are generated by go generate.
//
// # Threading
//
// All bridge functions dispatch to the main thread internally.
// The Go API is safe to call from any goroutine.
//
// # Quick start
//
//	import "github.com/tmc/swiftui"
//	import "github.com/tmc/swiftui/scenekit"
//
//	ptr := scenekit.NewSceneView(...)
//	view := swiftui.ViewFromPointer(ptr)
package scenekit
