// Code generated by applegen; DO NOT EDIT.

package embeddedbridge

import _ "embed"

//go:embed libSwiftUIBridge.dylib
var bridge []byte

// Payload returns the embedded bridge dylib payload.
func Payload() ([]byte, string) {
	return bridge, "libSwiftUIBridge.dylib"
}
