// Code generated by applegen; DO NOT EDIT.

import Charts
import Foundation
import SwiftUI

final class Box<T>: @unchecked Sendable {
    var value: T
    init(_ value: T) { self.value = value }
}

nonisolated(unsafe) var _CHHoverCallback: (@convention(c) (UInt, Int32, Double, Double, Double, Double, Double, Double, Int32, Double, Double, Int32, Double, Double) -> Void)?

func emptyChartContent() -> AnyChartContent {
    AnyChartContent(Plot {})
}

func decodePointer(_ text: String?) -> UnsafeMutableRawPointer? {
    guard let text, !text.isEmpty, let raw = UInt(text) else {
        return nil
    }
    return UnsafeMutableRawPointer(bitPattern: raw)
}

func decodeView(_ text: String?) -> AnyView? {
    guard let ptr = decodePointer(text) else {
        return nil
    }
    return Unmanaged<Box<AnyView>>.fromOpaque(ptr).takeUnretainedValue().value
}

func decodeColor(_ r: Double, _ g: Double, _ b: Double, _ a: Double) -> Color {
    Color(red: r, green: g, blue: b, opacity: a)
}

func calendarUnit(_ unit: Int32) -> Calendar.Component {
    switch unit {
    case 1: return .weekOfYear
    case 2: return .month
    case 3: return .year
    case 4: return .hour
    case 5: return .minute
    default: return .day
    }
}

func dateFormatStyle(_ pattern: String) -> Date.FormatStyle {
    switch pattern {
    case "yyyy":
        return .dateTime.year()
    case "MM/dd":
        return .dateTime.month(.twoDigits).day(.twoDigits)
    case "HH:mm":
        return .dateTime.hour(.twoDigits(amPM: .omitted)).minute(.twoDigits)
    case "MMM":
        return .dateTime.month(.abbreviated)
    case "MMM d":
        return .dateTime.month(.abbreviated).day()
    default:
        return .dateTime.month(.abbreviated).day()
    }
}

@_cdecl("CHRetain")
public func CHRetain(_ ref: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer {
    _ = Unmanaged<AnyObject>.fromOpaque(ref).retain()
    return ref
}

@_cdecl("CHRelease")
public func CHRelease(_ ref: UnsafeMutableRawPointer) {
    if Thread.isMainThread {
        Unmanaged<AnyObject>.fromOpaque(ref).release()
        return
    }
    let address = UInt(bitPattern: ref)
    DispatchQueue.main.async {
        guard let ref = UnsafeMutableRawPointer(bitPattern: address) else {
            return
        }
        Unmanaged<AnyObject>.fromOpaque(ref).release()
    }
}

@_cdecl("CHSetHoverCallback")
public func CHSetHoverCallback(_ fn: @convention(c) (UInt, Int32, Double, Double, Double, Double, Double, Double, Int32, Double, Double, Int32, Double, Double) -> Void) {
    _CHHoverCallback = fn
}
