// Code generated by applegen; DO NOT EDIT.

import Charts
import SwiftUI

@_cdecl("CHBuildChart")
@MainActor
public func CHBuildChart(_ specPtr: UnsafePointer<CChar>, _ specLen: Int32) -> UnsafeMutableRawPointer {
    let data = Data(bytes: specPtr, count: Int(specLen))
    let decoder = JSONDecoder()

    guard let spec = try? decoder.decode(ChartSpec.self, from: data) else {
        return Unmanaged.passRetained(Box(AnyView(EmptyView()))).toOpaque()
    }

    let marks = spec.marks.map(buildMark)
    var chart = AnyView(Chart {
        ForEach(marks.indices, id: \.self) { index in
            marks[index]
        }
    })

    chart = applyScale(chart, axis: "x", domain: spec.xDomain, range: spec.xRange, scaleType: spec.xScaleType)
    chart = applyScale(chart, axis: "y", domain: spec.yDomain, range: spec.yRange, scaleType: spec.yScaleType)
    if let xAxis = spec.xAxis {
        chart = applyAxis(chart, axis: "x", config: xAxis)
    }
    if let yAxis = spec.yAxis {
        chart = applyAxis(chart, axis: "y", config: yAxis)
    }
    if let xAxisLabel = spec.xAxisLabel {
        chart = applyAxisLabel(chart, axis: "x", label: xAxisLabel)
    }
    if let yAxisLabel = spec.yAxisLabel {
        chart = applyAxisLabel(chart, axis: "y", label: yAxisLabel)
    }
    if let xAxisStyle = spec.xAxisStyle {
        chart = applyAxisStyle(chart, axis: "x", style: xAxisStyle)
    }
    if let yAxisStyle = spec.yAxisStyle {
        chart = applyAxisStyle(chart, axis: "y", style: yAxisStyle)
    }
    if let styleScale = spec.styleScale {
        chart = applyForegroundStyleScale(chart, scale: styleScale)
    }
    if let symbolScale = spec.symbolScale {
        chart = applySymbolScale(chart, scale: symbolScale)
    }
    if let lineStyleScale = spec.lineStyleScale {
        chart = applyLineStyleScale(chart, scale: lineStyleScale)
    }
    if let symbolSizeScale = spec.symbolSizeScale {
        chart = applySymbolSizeScale(chart, scale: symbolSizeScale)
    }
    if let legend = spec.legend {
        chart = applyLegend(chart, legend: legend)
    }
    if let plot = spec.plot, !plot.isEmpty {
        chart = applyPlotStyle(chart, plot: plot)
    }
    chart = applyScrolling(chart, axes: spec.scrollAxes, position: spec.scrollPosition, target: spec.scrollTarget, xBinding: spec.xScrollBinding, yBinding: spec.yScrollBinding, xVisibleLength: spec.xVisibleLength, yVisibleLength: spec.yVisibleLength)
    chart = applySelections(chart, spec: spec)
    chart = applyProxyLayers(chart, overlays: spec.overlays, backgrounds: spec.backgrounds)
    chart = applyProxyGesture(chart, gesture: spec.gesture)

    return Unmanaged.passRetained(Box(chart)).toOpaque()
}

@MainActor
private func applyScale(_ view: AnyView, axis: String, domain: DomainSpec?, range: PositionScaleRangeSpec?, scaleType: ScaleTypeSpec) -> AnyView {
    switch axis {
    case "x":
        return applyXScale(view, domain: domain, range: range, scaleType: decodeScaleType(scaleType))
    case "y":
        return applyYScale(view, domain: domain, range: range, scaleType: decodeScaleType(scaleType))
    default:
        return view
    }
}

@MainActor
private func applyXScale(_ view: AnyView, domain: DomainSpec?, range: PositionScaleRangeSpec?, scaleType: Charts.ScaleType?) -> AnyView {
    switch (domain?.kind, range?.kind) {
    case (.some(0), .some(0)):
        return AnyView(view.chartXScale(domain: domain!.minInt ... domain!.maxInt, range: decodePositionScaleRange(range!), type: scaleType))
    case (.some(1), .some(0)):
        return AnyView(view.chartXScale(domain: domain!.minNumber ... domain!.maxNumber, range: decodePositionScaleRange(range!), type: scaleType))
    case (.some(2), .some(0)):
        return AnyView(view.chartXScale(domain: dateRange(domain!), range: decodePositionScaleRange(range!), type: scaleType))
    case (.some(3), .some(0)):
        return AnyView(view.chartXScale(domain: domain!.categories ?? [], range: decodePositionScaleRange(range!), type: scaleType))
    case (.some(0), _):
        return AnyView(view.chartXScale(domain: domain!.minInt ... domain!.maxInt, type: scaleType))
    case (.some(1), _):
        return AnyView(view.chartXScale(domain: domain!.minNumber ... domain!.maxNumber, type: scaleType))
    case (.some(2), _):
        return AnyView(view.chartXScale(domain: dateRange(domain!), type: scaleType))
    case (.some(3), _):
        return AnyView(view.chartXScale(domain: domain!.categories ?? [], type: scaleType))
    case (_, .some(0)):
        return AnyView(view.chartXScale(range: decodePositionScaleRange(range!), type: scaleType))
    default:
        if let scaleType {
            return AnyView(view.chartXScale(type: scaleType))
        }
        return view
    }
}

@MainActor
private func applyYScale(_ view: AnyView, domain: DomainSpec?, range: PositionScaleRangeSpec?, scaleType: Charts.ScaleType?) -> AnyView {
    switch (domain?.kind, range?.kind) {
    case (.some(0), .some(0)):
        return AnyView(view.chartYScale(domain: domain!.minInt ... domain!.maxInt, range: decodePositionScaleRange(range!), type: scaleType))
    case (.some(1), .some(0)):
        return AnyView(view.chartYScale(domain: domain!.minNumber ... domain!.maxNumber, range: decodePositionScaleRange(range!), type: scaleType))
    case (.some(2), .some(0)):
        return AnyView(view.chartYScale(domain: dateRange(domain!), range: decodePositionScaleRange(range!), type: scaleType))
    case (.some(3), .some(0)):
        return AnyView(view.chartYScale(domain: domain!.categories ?? [], range: decodePositionScaleRange(range!), type: scaleType))
    case (.some(0), _):
        return AnyView(view.chartYScale(domain: domain!.minInt ... domain!.maxInt, type: scaleType))
    case (.some(1), _):
        return AnyView(view.chartYScale(domain: domain!.minNumber ... domain!.maxNumber, type: scaleType))
    case (.some(2), _):
        return AnyView(view.chartYScale(domain: dateRange(domain!), type: scaleType))
    case (.some(3), _):
        return AnyView(view.chartYScale(domain: domain!.categories ?? [], type: scaleType))
    case (_, .some(0)):
        return AnyView(view.chartYScale(range: decodePositionScaleRange(range!), type: scaleType))
    default:
        if let scaleType {
            return AnyView(view.chartYScale(type: scaleType))
        }
        return view
    }
}

@MainActor
private func applyAxis(_ view: AnyView, axis: String, config: AxisConfigSpec) -> AnyView {
    if config.hidden {
        return axis == "x" ? AnyView(view.chartXAxis(.hidden)) : AnyView(view.chartYAxis(.hidden))
    }
    if axis == "x" {
        return AnyView(view.chartXAxis {
            buildAxisMarks(config)
        })
    }
    return AnyView(view.chartYAxis {
        buildAxisMarks(config)
    })
}

@AxisContentBuilder
private func buildAxisMarks(_ config: AxisConfigSpec) -> some AxisContent {
    switch config.values.kind {
    case 1:
        buildAxisMarks(config, values: .automatic(
            desiredCount: config.values.desiredCount > 0 ? config.values.desiredCount : nil,
            roundLowerBound: config.values.roundLowerBound,
            roundUpperBound: config.values.roundUpperBound
        ))
    case 2:
        buildAxisMarks(config, values: .automatic(
            minimumStride: config.values.step,
            desiredCount: config.values.desiredCount > 0 ? config.values.desiredCount : nil,
            roundLowerBound: config.values.roundLowerBound,
            roundUpperBound: config.values.roundUpperBound
        ))
    case 3:
        buildAxisMarks(config, values: .stride(
            by: config.values.step,
            roundLowerBound: config.values.roundLowerBound,
            roundUpperBound: config.values.roundUpperBound
        ))
    case 4:
        buildAxisMarks(config, values: .stride(
            by: calendarUnit(config.values.unit),
            count: max(config.values.count, 1),
            roundLowerBound: config.values.roundLowerBound,
            roundUpperBound: config.values.roundUpperBound
        ))
    case 5:
        buildExplicitAxisMarks(config, values: config.values.values ?? [])
    default:
        buildAxisMarks(config, values: .automatic)
    }
}

@AxisContentBuilder
private func buildAxisMarks(_ config: AxisConfigSpec, values: AxisMarkValues) -> some AxisContent {
    let preset = axisPreset(config.preset)
    let position = axisPosition(config.position)
    AxisMarks(preset: preset, position: position, values: values) { value in
        buildAxisMarkContents(config, value: value)
    }
}

@AxisContentBuilder
private func buildExplicitAxisMarks(_ config: AxisConfigSpec, values: [ValueSpec]) -> some AxisContent {
    if let first = values.first {
        switch first.kind {
        case 1:
            AxisMarks(preset: axisPreset(config.preset), position: axisPosition(config.position), values: values.map(\.integer)) { value in
                buildAxisMarkContents(config, value: value)
            }
        case 2:
            AxisMarks(preset: axisPreset(config.preset), position: axisPosition(config.position), values: values.map(\.number)) { value in
                buildAxisMarkContents(config, value: value)
            }
        case 3:
            AxisMarks(preset: axisPreset(config.preset), position: axisPosition(config.position), values: values.map { Date(timeIntervalSince1970: Double($0.timeUnixMS) / 1000) }) { value in
                buildAxisMarkContents(config, value: value)
            }
        default:
            AxisMarks(preset: axisPreset(config.preset), position: axisPosition(config.position), values: values.map(\.category)) { value in
                buildAxisMarkContents(config, value: value)
            }
        }
    } else {
        buildAxisMarks(config, values: .automatic)
    }
}

@AxisMarkBuilder
private func buildAxisMarkContents(_ config: AxisConfigSpec, value: AxisValue? = nil) -> some AxisMark {
    if config.showGrid {
        AxisGridLine(centered: config.gridCentered, stroke: decodeOptionalStrokeStyle(config.gridStyle))
    }
    if config.showTicks {
        AxisTick(
            centered: config.tickCentered,
            length: decodeAxisTickLength(config.tickLength),
            stroke: decodeOptionalStrokeStyle(config.tickStyle)
        )
    }
    if config.showLabels || (!config.showGrid && !config.showTicks) {
        if config.datePattern.isEmpty {
            if let value, let text = formattedAxisValueLabel(value, config: config) {
                AxisValueLabel {
                    Text(text).monospacedDigit()
                }
            } else {
                AxisValueLabel()
            }
        } else {
            AxisValueLabel(format: dateFormatStyle(config.datePattern), centered: config.labelCentered)
        }
    }
}

private func formattedAxisValueLabel(_ value: AxisValue, config: AxisConfigSpec) -> String? {
    switch config.valueFormat.kind {
    case 1:
        if let number = value.as(Double.self) {
            return fixedString(number, precision: config.valueFormat.precision)
        }
        if let integer = value.as(Int.self) {
            return fixedString(Double(integer), precision: config.valueFormat.precision)
        }
    case 2:
        if let number = value.as(Double.self) {
            return fixedString(number * 100, precision: config.valueFormat.precision) + "%"
        }
        if let integer = value.as(Int.self) {
            return fixedString(Double(integer) * 100, precision: config.valueFormat.precision) + "%"
        }
    case 3:
        if let number = value.as(Double.self) {
            return compactString(number, precision: config.valueFormat.precision)
        }
        if let integer = value.as(Int.self) {
            return compactString(Double(integer), precision: config.valueFormat.precision)
        }
    case 4:
        if let number = value.as(Double.self) {
            return durationString(number, format: config.valueFormat)
        }
        if let integer = value.as(Int.self) {
            return durationString(Double(integer), format: config.valueFormat)
        }
    case 5:
        if let number = value.as(Double.self) {
            return fixedString(number, precision: config.valueFormat.precision) + config.valueFormat.suffix
        }
        if let integer = value.as(Int.self) {
            return fixedString(Double(integer), precision: config.valueFormat.precision) + config.valueFormat.suffix
        }
    default:
        break
    }
    return nil
}

private func fixedString(_ value: Double, precision: Int) -> String {
    String(format: "%.\(max(precision, 0))f", value)
}

private func compactString(_ value: Double, precision: Int) -> String {
    let magnitude = abs(value)
    switch magnitude {
    case 1_000_000_000_000...:
        return fixedString(value / 1_000_000_000_000, precision: precision) + "T"
    case 1_000_000_000...:
        return fixedString(value / 1_000_000_000, precision: precision) + "B"
    case 1_000_000...:
        return fixedString(value / 1_000_000, precision: precision) + "M"
    case 1_000...:
        return fixedString(value / 1_000, precision: precision) + "K"
    default:
        return fixedString(value, precision: precision)
    }
}

private func durationString(_ value: Double, format: ValueFormatSpec) -> String {
    let scale: Double
    let suffix: String
    switch format.unit {
    case 4:
        scale = 1.0 / 60.0
        suffix = " min"
    case 1:
        scale = 1_000
        suffix = " ms"
    case 2:
        scale = 1_000_000
        suffix = " µs"
    case 3:
        scale = 1_000_000_000
        suffix = " ns"
    default:
        scale = 1
        suffix = " s"
    }
    return fixedString(value * scale, precision: format.precision) + suffix
}

private func axisPreset(_ raw: Int32) -> AxisMarkPreset {
    switch raw {
    case 1: return .aligned
    case 2: return .extended
    case 3: return .inset
    default: return .automatic
    }
}

private func axisPosition(_ raw: Int32) -> AxisMarkPosition {
    switch raw {
    case 1: return .bottom
    case 2: return .top
    case 3: return .leading
    case 4: return .trailing
    default: return .automatic
    }
}

@MainActor
private func applyAxisLabel(_ view: AnyView, axis: String, label: AxisLabelSpec) -> AnyView {
    let position = label.hasPosition ? annotationPosition(label.position) : .automatic
    let alignment = label.hasAlignment ? labelAlignment(label.alignment) : nil
    let spacing = label.hasSpacing ? CGFloat(label.spacing) : nil
    if axis == "x" {
        return AnyView(view.chartXAxisLabel(label.text, position: position, alignment: alignment, spacing: spacing))
    }
    return AnyView(view.chartYAxisLabel(label.text, position: position, alignment: alignment, spacing: spacing))
}

private func labelAlignment(_ raw: Int32) -> Alignment {
    switch raw {
    case 1: return .leading
    case 2: return .trailing
    case 3: return .top
    case 4: return .bottom
    case 5: return .topLeading
    case 6: return .topTrailing
    case 7: return .bottomLeading
    case 8: return .bottomTrailing
    default: return .center
    }
}

@MainActor
private func applyAxisStyle(_ view: AnyView, axis: String, style: AxisStyleSpec) -> AnyView {
    guard let entries = style.entries, !entries.isEmpty else {
        return view
    }
    if axis == "x" {
        return AnyView(view.chartXAxisStyle { axisContent in
            applyAxisStyleEntries(AnyView(axisContent), entries: entries)
        })
    }
    return AnyView(view.chartYAxisStyle { axisContent in
        applyAxisStyleEntries(AnyView(axisContent), entries: entries)
    })
}

private func applyAxisStyleEntries(_ base: AnyView, entries: [AxisStyleEntrySpec]) -> AnyView {
    var styled = base
    for entry in entries {
        let color = decodeColor(entry.colorR, entry.colorG, entry.colorB, entry.colorA)
        switch entry.kind {
        case 0:
            styled = AnyView(styled.foregroundStyle(color))
        case 1:
            styled = AnyView(styled.opacity(entry.opacity))
        case 2:
            styled = AnyView(styled.background(color))
        case 3:
            if let background = decodeView(entry.viewPtr) {
                styled = AnyView(styled.background(background))
            }
        case 4:
            if let overlay = decodeView(entry.viewPtr) {
                styled = AnyView(styled.overlay(overlay))
            }
        default:
            break
        }
    }
    return styled
}

@MainActor
private func applyForegroundStyleScale(_ view: AnyView, scale: ForegroundStyleScaleSpec) -> AnyView {
    let scaleType = scale.scaleType.flatMap(decodeScaleType)
    guard let entries = scale.entries, !entries.isEmpty else {
        if let scaleType {
            return AnyView(view.chartForegroundStyleScale(type: scaleType))
        }
        return view
    }
    let domain = entries.map(\.key)
    let range = entries.map { decodeColor($0.colorR, $0.colorG, $0.colorB, $0.colorA) }
    return AnyView(view.chartForegroundStyleScale(domain: domain, range: range, type: scaleType))
}

@MainActor
private func applySymbolScale(_ view: AnyView, scale: SymbolScaleSpec) -> AnyView {
    guard let entries = scale.entries, !entries.isEmpty else {
        return view
    }
    return AnyView(view.chartSymbolScale(
        domain: entries.map(\.key),
        range: entries.map { symbolShape($0.symbol) }
    ))
}

@MainActor
private func applyLineStyleScale(_ view: AnyView, scale: LineStyleScaleSpec) -> AnyView {
    guard let entries = scale.entries, !entries.isEmpty else {
        return view
    }
    return AnyView(view.chartLineStyleScale(
        domain: entries.map(\.key),
        range: entries.map { decodeStrokeStyle($0.style) }
    ))
}

@MainActor
private func applySymbolSizeScale(_ view: AnyView, scale: SymbolSizeScaleSpec) -> AnyView {
    let scaleType = scale.scaleType.flatMap(decodeScaleType)
    guard let entries = scale.entries, !entries.isEmpty else {
        if let scaleType {
            return AnyView(view.chartSymbolSizeScale(type: scaleType))
        }
        return view
    }
    return AnyView(view.chartSymbolSizeScale(
        domain: entries.map(\.key),
        range: entries.map { CGFloat($0.size) },
        type: scaleType
    ))
}

@MainActor
private func applyLegend(_ view: AnyView, legend: LegendConfigSpec) -> AnyView {
    if legend.visibility == 2 {
        return AnyView(view.chartLegend(.hidden))
    }
    if legend.visibility == 1 {
        return AnyView(view.chartLegend(position: legendPosition(legend.position), alignment: legendAlignment(legend.alignment), spacing: legend.spacing))
    }
    return view
}

private func legendPosition(_ raw: Int32) -> AnnotationPosition {
    switch raw {
    case 1: return .top
    case 2: return .bottom
    case 3: return .leading
    case 4: return .trailing
    case 5: return .overlay
    default: return .top
    }
}

private func legendAlignment(_ raw: Int32) -> Alignment {
    switch raw {
    case 1: return .leading
    case 2: return .trailing
    case 3: return .top
    case 4: return .bottom
    default: return .center
    }
}

@MainActor
private func applyPlotStyle(_ view: AnyView, plot: [PlotStyleSpec]) -> AnyView {
    AnyView(view.chartPlotStyle { chartContent in
        applyPlotEntries(AnyView(chartContent), plot: plot)
    })
}

private func applyPlotEntries(_ base: AnyView, plot: [PlotStyleSpec]) -> AnyView {
    var styled = base
    for entry in plot {
        let color = decodeColor(entry.colorR, entry.colorG, entry.colorB, entry.colorA)
        switch entry.kind {
        case 0:
            styled = AnyView(styled.background(color))
        case 1:
            styled = AnyView(styled.border(color, width: entry.width))
        case 2:
            if let background = decodeView(entry.viewPtr) {
                styled = AnyView(styled.background(background))
            }
        case 3:
            if let overlay = decodeView(entry.viewPtr) {
                styled = AnyView(styled.overlay(overlay))
            }
        case 4:
            styled = AnyView(styled.padding(EdgeInsets(top: entry.top, leading: entry.left, bottom: entry.bottom, trailing: entry.right)))
        default:
            break
        }
    }
    return styled
}

private func decodeScaleType(_ spec: ScaleTypeSpec) -> Charts.ScaleType? {
    switch spec.kind {
    case 1:
        return .linear
    case 2:
        return .log
    case 3:
        return .date
    case 4:
        return .category
    case 5:
        return .power(exponent: spec.value)
    case 6:
        return .squareRoot
    case 7:
        return .symmetricLog(slopeAtZero: spec.value)
    default:
        return nil
    }
}

private func decodePositionScaleRange(_ spec: PositionScaleRangeSpec) -> PlotDimensionScaleRange {
    switch spec.kind {
    default:
        return .plotDimension(startPadding: spec.startPadding, endPadding: spec.endPadding)
    }
}

private func dateRange(_ domain: DomainSpec) -> ClosedRange<Date> {
    Date(timeIntervalSince1970: Double(domain.startUnixMS) / 1000) ... Date(timeIntervalSince1970: Double(domain.endUnixMS) / 1000)
}

private func decodeAxisTickLength(_ spec: AxisTickLengthSpec) -> AxisTick.Length {
    switch spec.kind {
    case 1:
        return .label(extendPastBy: spec.value)
    case 2:
        return .longestLabel(extendPastBy: spec.value)
    default:
        return .automatic
    }
}

private func decodeOptionalStrokeStyle(_ spec: LineStyleSpec) -> StrokeStyle? {
    if spec.width == 0 && (spec.dash ?? []).isEmpty {
        return nil
    }
    return decodeStrokeStyle(spec)
}

private func decodeStrokeStyle(_ spec: LineStyleSpec) -> StrokeStyle {
    decodeStrokeStyle(width: spec.width, dash: spec.dash)
}
