// Code generated by applegen; DO NOT EDIT.

package avkit

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/tmc/swiftui/internal/bridgeutil"

	embeddedbridge "github.com/tmc/swiftui/avkit/internal/embeddedbridge"

	"github.com/ebitengine/purego"
)

// libHandle is the handle to the loaded libAVKitSwiftUIBridge dylib.
var libHandle uintptr
var loadErr error

// Err reports the error encountered while loading the AVKit bridge, or
// nil if the bridge loaded successfully.
func Err() error { return loadErr }

// Available reports whether the AVKit bridge dylib loaded successfully.
func Available() bool { return libHandle != 0 && loadErr == nil }

// swiftBridgeDir returns the path to the vendored Swift bridge source directory.
func swiftBridgeDir() string {
	_, file, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(file), "internal/swift")
}

// discoverBuiltDylib locates a built bridge dylib across SwiftPM layouts.
func discoverBuiltDylib() (string, error) {
	path, err := bridgeutil.DiscoverBuiltDylib(swiftBridgeDir(), "libAVKitSwiftUIBridge.dylib")
	if err != nil {
		return "", fmt.Errorf("avkit: %w", err)
	}
	return path, nil
}

// buildSwiftBridge builds the vendored Swift bridge dylib if needed.
func buildSwiftBridge() (string, error) {
	return bridgeutil.BuildSwiftBridge(swiftBridgeDir(), "libAVKitSwiftUIBridge.dylib", "avkit")
}

// materializeEmbeddedBridge writes the embedded bridge payload to a cache directory.
func materializeEmbeddedBridge(data []byte, name string) (string, error) {
	if len(data) == 0 {
		return "", nil
	}
	if name == "" {
		name = "libAVKitSwiftUIBridge.dylib"
	}
	sum := sha256.Sum256(data)
	cacheDir := filepath.Join(os.TempDir(), "avkit-bridge-cache")
	if err := os.MkdirAll(cacheDir, 0o755); err != nil {
		return "", fmt.Errorf("avkit: create bridge cache: %w", err)
	}
	path := filepath.Join(cacheDir, hex.EncodeToString(sum[:])+"-"+name)
	if _, err := os.Stat(path); err == nil {
		return path, nil
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o755); err != nil {
		return "", fmt.Errorf("avkit: write embedded bridge: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		if _, statErr := os.Stat(path); statErr == nil {
			_ = os.Remove(tmp)
			return path, nil
		}
		return "", fmt.Errorf("avkit: finalize embedded bridge: %w", err)
	}
	return path, nil
}

// loadEmbeddedBridge attempts to load the bridge from an embedded payload.
func loadEmbeddedBridge() (uintptr, error) {
	data, name := embeddedbridge.Payload()
	if len(data) == 0 {
		return 0, nil
	}
	path, err := materializeEmbeddedBridge(data, name)
	if err != nil {
		return 0, err
	}
	handle, err := purego.Dlopen(path, purego.RTLD_LAZY|purego.RTLD_GLOBAL)
	if err != nil {
		return 0, fmt.Errorf("avkit: dlopen embedded bridge %s: %w", path, err)
	}
	return handle, nil
}

// tryRegisterLibFunc attempts to register a C function from the dylib.
func tryRegisterLibFunc(fptr any, handle uintptr, name string) bool {
	defer func() { recover() }()
	purego.RegisterLibFunc(fptr, handle, name)
	return true
}

// C function variables registered via purego.RegisterLibFunc.
var (
	_AVS_VideoPlayerCreate            func(uintptr) uintptr
	_AVS_VideoPlayerWithOverlayCreate func(uintptr, uintptr) uintptr
	_AVS_Retain                       func(uintptr) uintptr
	_AVS_Release                      func(uintptr)
	_AVS_FreeString                   func(*byte)
)

func init() {
	envKey := "LIB" + strings.ToUpper("AVKitSwiftUIBridge") + "_PATH"
	var lastErr error

	if path := os.Getenv(envKey); path != "" {
		var err error
		libHandle, err = purego.Dlopen(path, purego.RTLD_LAZY|purego.RTLD_GLOBAL)
		if err != nil {
			lastErr = err
		}
	}

	if libHandle == 0 {
		if path, err := discoverBuiltDylib(); err == nil {
			libHandle, err = purego.Dlopen(path, purego.RTLD_LAZY|purego.RTLD_GLOBAL)
			if err != nil {
				lastErr = err
			}
		} else {
			lastErr = err
		}
	}

	// Try embedded bridge payload before local Swift build.
	if libHandle == 0 {
		if handle, err := loadEmbeddedBridge(); err == nil && handle != 0 {
			libHandle = handle
		}
	}

	if libHandle == 0 {
		if path, err := buildSwiftBridge(); err == nil {
			libHandle, err = purego.Dlopen(path, purego.RTLD_LAZY|purego.RTLD_GLOBAL)
			if err != nil {
				lastErr = err
			}
		} else {
			lastErr = err
		}
	}

	if libHandle == 0 {
		for _, path := range []string{
			"libAVKitSwiftUIBridge.dylib",
			"/usr/local/lib/libAVKitSwiftUIBridge.dylib",
		} {
			var err error
			libHandle, err = purego.Dlopen(path, purego.RTLD_LAZY|purego.RTLD_GLOBAL)
			if err == nil {
				break
			}
			lastErr = err
		}
	}

	if libHandle == 0 {
		if _, err := exec.LookPath("swift"); err != nil {
			loadErr = fmt.Errorf("avkit: swift toolchain not found; install Xcode or Command Line Tools")
		} else if lastErr != nil {
			loadErr = fmt.Errorf("avkit: failed to load bridge dylib: %w", lastErr)
		} else {
			loadErr = fmt.Errorf("avkit: bridge dylib not loaded")
		}
		setUnavailableStubs()
		return
	}
	tryRegisterLibFunc(&_AVS_VideoPlayerCreate, libHandle, "AVS_VideoPlayerCreate")
	tryRegisterLibFunc(&_AVS_VideoPlayerWithOverlayCreate, libHandle, "AVS_VideoPlayerWithOverlayCreate")
	tryRegisterLibFunc(&_AVS_Retain, libHandle, "AVS_Retain")
	tryRegisterLibFunc(&_AVS_Release, libHandle, "AVS_Release")
	tryRegisterLibFunc(&_AVS_FreeString, libHandle, "AVS_FreeString")

	setUnavailableStubs()
}

func setUnavailableStubs() {
	stub := func(name string) {
		if loadErr != nil {
			panic("avkit: " + name + ": " + loadErr.Error())
		}
		panic("avkit: " + name + ": dylib not loaded")
	}
	if _AVS_VideoPlayerCreate == nil {
		_AVS_VideoPlayerCreate = func(uintptr) uintptr { stub("AVS_VideoPlayerCreate"); return 0 }
	}
	if _AVS_VideoPlayerWithOverlayCreate == nil {
		_AVS_VideoPlayerWithOverlayCreate = func(uintptr, uintptr) uintptr { stub("AVS_VideoPlayerWithOverlayCreate"); return 0 }
	}
	if _AVS_Retain == nil {
		_AVS_Retain = func(uintptr) uintptr { stub("AVS_Retain"); return 0 }
	}
	if _AVS_Release == nil {
		_AVS_Release = func(uintptr) { stub("AVS_Release") }
	}
	if _AVS_FreeString == nil {
		_AVS_FreeString = func(*byte) { stub("AVS_FreeString") }
	}
}
