// Code generated by applegen; DO NOT EDIT.

//go:build charts_embed

package embeddedbridge

import _ "embed"

//go:embed libChartsBridge.dylib
var bridge []byte

// Payload returns the embedded ChartsBridge bridge dylib payload.
func Payload() ([]byte, string) {
	return bridge, "libChartsBridge.dylib"
}
