// Code generated by applegen; DO NOT EDIT.

//go:build translation_embed

package embeddedbridge

import _ "embed"

//go:embed libTranslationSwiftUIBridge.dylib
var bridge []byte

// Payload returns the embedded TranslationSwiftUIBridge bridge dylib payload.
func Payload() ([]byte, string) {
	return bridge, "libTranslationSwiftUIBridge.dylib"
}
